// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &acceptedDomainResource{}
	_ resource.ResourceWithConfigure   = &acceptedDomainResource{}
	_ resource.ResourceWithImportState = &acceptedDomainResource{}
	_ resource.ResourceWithModifyPlan  = &acceptedDomainResource{}
)

type acceptedDomainResource struct{ client *clients.Client }

// NewAcceptedDomainResource manages the AcceptedDomain configuration (Get-AcceptedDomain / Set-AcceptedDomain); it adopts the existing object and is not deleted on destroy.
func NewAcceptedDomainResource() resource.Resource { return &acceptedDomainResource{} }

type acceptedDomainModel struct {
	ID                        types.String `tfsdk:"id"`
	Identity                  types.String `tfsdk:"identity"`
	CanHaveCloudCache         types.Bool   `tfsdk:"can_have_cloud_cache"`
	DomainType                types.String `tfsdk:"domain_type"`
	EnableNego2Authentication types.Bool   `tfsdk:"enable_nego2_authentication"`
	MailFlowRegion            types.String `tfsdk:"mail_flow_region"`
	MatchSubDomains           types.Bool   `tfsdk:"match_sub_domains"`
	OutboundOnly              types.Bool   `tfsdk:"outbound_only"`
	SendingFromDomainDisabled types.Bool   `tfsdk:"sending_from_domain_disabled"`
	SendingToDomainDisabled   types.Bool   `tfsdk:"sending_to_domain_disabled"`
}

func (r *acceptedDomainResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_accepted_domain"
}

func (r *acceptedDomainResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the AcceptedDomain configuration via Set-AcceptedDomain.",
		Attributes: map[string]schema.Attribute{
			"id":                           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                     schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"can_have_cloud_cache":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CanHaveCloudCache parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"domain_type":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DomainType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enable_nego2_authentication":  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableNego2Authentication parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mail_flow_region":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MailFlowRegion parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"match_sub_domains":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MatchSubDomains parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"outbound_only":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -OutboundOnly parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"sending_from_domain_disabled": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SendingFromDomainDisabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"sending_to_domain_disabled":   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SendingToDomainDisabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *acceptedDomainResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *acceptedDomainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan acceptedDomainModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config acceptedDomainModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetAcceptedDomainParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.CanHaveCloudCache.IsNull() {
		if !plan.CanHaveCloudCache.IsUnknown() {
			sp.CanHaveCloudCache = plan.CanHaveCloudCache.ValueBoolPointer()
		}
	}
	if v := config.DomainType.ValueString(); v != "" {
		sp.DomainType = objectParam(v)
	}
	if !config.EnableNego2Authentication.IsNull() {
		if !plan.EnableNego2Authentication.IsUnknown() {
			sp.EnableNego2Authentication = plan.EnableNego2Authentication.ValueBoolPointer()
		}
	}
	if !config.MailFlowRegion.IsNull() {
		sp.MailFlowRegion = plan.MailFlowRegion.ValueString()
	}
	if !config.MatchSubDomains.IsNull() {
		if !plan.MatchSubDomains.IsUnknown() {
			sp.MatchSubDomains = plan.MatchSubDomains.ValueBoolPointer()
		}
	}
	if !config.OutboundOnly.IsNull() {
		if !plan.OutboundOnly.IsUnknown() {
			sp.OutboundOnly = plan.OutboundOnly.ValueBoolPointer()
		}
	}
	if !config.SendingFromDomainDisabled.IsNull() {
		if !plan.SendingFromDomainDisabled.IsUnknown() {
			sp.SendingFromDomainDisabled = plan.SendingFromDomainDisabled.ValueBoolPointer()
		}
	}
	if !config.SendingToDomainDisabled.IsNull() {
		if !plan.SendingToDomainDisabled.IsUnknown() {
			sp.SendingToDomainDisabled = plan.SendingToDomainDisabled.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetAcceptedDomain(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AcceptedDomain failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *acceptedDomainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state acceptedDomainModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *acceptedDomainResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state acceptedDomainModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetAcceptedDomainParams{}
	sp.Identity = id
	if !plan.CanHaveCloudCache.Equal(state.CanHaveCloudCache) {
		if !plan.CanHaveCloudCache.IsUnknown() {
			sp.CanHaveCloudCache = plan.CanHaveCloudCache.ValueBoolPointer()
		}
	}
	if v := plan.DomainType.ValueString(); v != "" {
		sp.DomainType = objectParam(v)
	}
	if !plan.EnableNego2Authentication.Equal(state.EnableNego2Authentication) {
		if !plan.EnableNego2Authentication.IsUnknown() {
			sp.EnableNego2Authentication = plan.EnableNego2Authentication.ValueBoolPointer()
		}
	}
	if !plan.MailFlowRegion.Equal(state.MailFlowRegion) {
		sp.MailFlowRegion = plan.MailFlowRegion.ValueString()
	}
	if !plan.MatchSubDomains.Equal(state.MatchSubDomains) {
		if !plan.MatchSubDomains.IsUnknown() {
			sp.MatchSubDomains = plan.MatchSubDomains.ValueBoolPointer()
		}
	}
	if !plan.OutboundOnly.Equal(state.OutboundOnly) {
		if !plan.OutboundOnly.IsUnknown() {
			sp.OutboundOnly = plan.OutboundOnly.ValueBoolPointer()
		}
	}
	if !plan.SendingFromDomainDisabled.Equal(state.SendingFromDomainDisabled) {
		if !plan.SendingFromDomainDisabled.IsUnknown() {
			sp.SendingFromDomainDisabled = plan.SendingFromDomainDisabled.ValueBoolPointer()
		}
	}
	if !plan.SendingToDomainDisabled.Equal(state.SendingToDomainDisabled) {
		if !plan.SendingToDomainDisabled.IsUnknown() {
			sp.SendingToDomainDisabled = plan.SendingToDomainDisabled.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetAcceptedDomain(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AcceptedDomain failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"MailFlowRegion": cfg.MailFlowRegion,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *acceptedDomainResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("AcceptedDomain configuration not deleted", "This resource manages an existing AcceptedDomain configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *acceptedDomainResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *acceptedDomainResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan acceptedDomainModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.EXO.GetAcceptedDomain(ctx, exo.GetAcceptedDomainParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur acceptedDomainModel
	readAcceptedDomain(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.CanHaveCloudCache.IsUnknown() {
		plan.CanHaveCloudCache = cur.CanHaveCloudCache
	}
	if plan.DomainType.IsUnknown() {
		plan.DomainType = cur.DomainType
	}
	if plan.EnableNego2Authentication.IsUnknown() {
		plan.EnableNego2Authentication = cur.EnableNego2Authentication
	}
	if plan.MailFlowRegion.IsUnknown() {
		plan.MailFlowRegion = cur.MailFlowRegion
	}
	if plan.MatchSubDomains.IsUnknown() {
		plan.MatchSubDomains = cur.MatchSubDomains
	}
	if plan.OutboundOnly.IsUnknown() {
		plan.OutboundOnly = cur.OutboundOnly
	}
	if plan.SendingFromDomainDisabled.IsUnknown() {
		plan.SendingFromDomainDisabled = cur.SendingFromDomainDisabled
	}
	if plan.SendingToDomainDisabled.IsUnknown() {
		plan.SendingToDomainDisabled = cur.SendingToDomainDisabled
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *acceptedDomainResource) identityOf(m acceptedDomainModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *acceptedDomainResource) refresh(ctx context.Context, identity string, m *acceptedDomainModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetAcceptedDomain(ctx, exo.GetAcceptedDomainParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-AcceptedDomain failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readAcceptedDomain(ctx, obj, m)
	return true
}

func readAcceptedDomain(ctx context.Context, obj map[string]any, m *acceptedDomainModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.CanHaveCloudCache = types.BoolValue(getBool(obj, "CanHaveCloudCache"))
	m.DomainType = types.StringValue(getObjectJSON(obj, "DomainType"))
	m.EnableNego2Authentication = types.BoolValue(getBool(obj, "EnableNego2Authentication"))
	m.MailFlowRegion = types.StringValue(getString(obj, "MailFlowRegion"))
	m.MatchSubDomains = types.BoolValue(getBool(obj, "MatchSubDomains"))
	m.OutboundOnly = types.BoolValue(getBool(obj, "OutboundOnly"))
	m.SendingFromDomainDisabled = types.BoolValue(getBool(obj, "SendingFromDomainDisabled"))
	m.SendingToDomainDisabled = types.BoolValue(getBool(obj, "SendingToDomainDisabled"))
	_ = ctx
}

func (r *acceptedDomainResource) reconcileState(cfg, read *acceptedDomainModel) {
	read.CanHaveCloudCache = reconcile.KeepBool(cfg.CanHaveCloudCache, read.CanHaveCloudCache)
	read.DomainType = reconcile.KeepStr(cfg.DomainType, read.DomainType)
	read.EnableNego2Authentication = reconcile.KeepBool(cfg.EnableNego2Authentication, read.EnableNego2Authentication)
	read.MailFlowRegion = reconcile.KeepStr(cfg.MailFlowRegion, read.MailFlowRegion)
	read.MatchSubDomains = reconcile.KeepBool(cfg.MatchSubDomains, read.MatchSubDomains)
	read.OutboundOnly = reconcile.KeepBool(cfg.OutboundOnly, read.OutboundOnly)
	read.SendingFromDomainDisabled = reconcile.KeepBool(cfg.SendingFromDomainDisabled, read.SendingFromDomainDisabled)
	read.SendingToDomainDisabled = reconcile.KeepBool(cfg.SendingToDomainDisabled, read.SendingToDomainDisabled)
}
