// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &accessToCustomerDataRequestResource{}
	_ resource.ResourceWithConfigure   = &accessToCustomerDataRequestResource{}
	_ resource.ResourceWithImportState = &accessToCustomerDataRequestResource{}
	_ resource.ResourceWithModifyPlan  = &accessToCustomerDataRequestResource{}
)

type accessToCustomerDataRequestResource struct{ client *clients.Client }

// NewAccessToCustomerDataRequestResource manages the AccessToCustomerDataRequest configuration (Get-AccessToCustomerDataRequest / Set-AccessToCustomerDataRequest); it adopts the existing object and is not deleted on destroy.
func NewAccessToCustomerDataRequestResource() resource.Resource {
	return &accessToCustomerDataRequestResource{}
}

type accessToCustomerDataRequestModel struct {
	ID               types.String `tfsdk:"id"`
	Identity         types.String `tfsdk:"identity"`
	ApprovalDecision types.String `tfsdk:"approval_decision"`
	Comment          types.String `tfsdk:"comment"`
	RequestId        types.String `tfsdk:"request_id"`
	ServiceName      types.String `tfsdk:"service_name"`
}

func (r *accessToCustomerDataRequestResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_access_to_customer_data_request"
}

func (r *accessToCustomerDataRequestResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the AccessToCustomerDataRequest configuration via Set-AccessToCustomerDataRequest.",
		Attributes: map[string]schema.Attribute{
			"id":                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":          schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"approval_decision": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApprovalDecision parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"request_id":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RequestId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"service_name":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ServiceName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *accessToCustomerDataRequestResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *accessToCustomerDataRequestResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan accessToCustomerDataRequestModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config accessToCustomerDataRequestModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetAccessToCustomerDataRequestParams{}
	if v := config.ApprovalDecision.ValueString(); v != "" {
		sp.ApprovalDecision = objectParam(v)
	}
	if !config.Comment.IsNull() {
		sp.Comment = plan.Comment.ValueString()
	}
	if !config.RequestId.IsNull() {
		sp.RequestId = plan.RequestId.ValueString()
	}
	if v := config.ServiceName.ValueString(); v != "" {
		sp.ServiceName = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetAccessToCustomerDataRequest(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AccessToCustomerDataRequest failed", err.Error())
		return
	}
	cfg := plan
	identity := ""
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *accessToCustomerDataRequestResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state accessToCustomerDataRequestModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *accessToCustomerDataRequestResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state accessToCustomerDataRequestModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetAccessToCustomerDataRequestParams{}
	if !plan.ApprovalDecision.Equal(state.ApprovalDecision) {
		if v := plan.ApprovalDecision.ValueString(); v != "" {
			sp.ApprovalDecision = objectParam(v)
		}
	}
	if !plan.Comment.Equal(state.Comment) {
		sp.Comment = plan.Comment.ValueString()
	}
	if !plan.RequestId.Equal(state.RequestId) {
		sp.RequestId = plan.RequestId.ValueString()
	}
	if !plan.ServiceName.Equal(state.ServiceName) {
		if v := plan.ServiceName.ValueString(); v != "" {
			sp.ServiceName = objectParam(v)
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetAccessToCustomerDataRequest(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AccessToCustomerDataRequest failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Comment":   cfg.Comment,
		"RequestId": cfg.RequestId,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *accessToCustomerDataRequestResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("AccessToCustomerDataRequest configuration not deleted", "This resource manages an existing AccessToCustomerDataRequest configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *accessToCustomerDataRequestResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *accessToCustomerDataRequestResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan accessToCustomerDataRequestModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.GetAccessToCustomerDataRequest(ctx, exo.GetAccessToCustomerDataRequestParams{})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur accessToCustomerDataRequestModel
	readAccessToCustomerDataRequest(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.ApprovalDecision.IsUnknown() {
		plan.ApprovalDecision = cur.ApprovalDecision
	}
	if plan.Comment.IsUnknown() {
		plan.Comment = cur.Comment
	}
	if plan.RequestId.IsUnknown() {
		plan.RequestId = cur.RequestId
	}
	if plan.ServiceName.IsUnknown() {
		plan.ServiceName = cur.ServiceName
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *accessToCustomerDataRequestResource) identityOf(m accessToCustomerDataRequestModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *accessToCustomerDataRequestResource) refresh(ctx context.Context, identity string, m *accessToCustomerDataRequestModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := r.client.EXO.GetAccessToCustomerDataRequest(ctx, exo.GetAccessToCustomerDataRequestParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-AccessToCustomerDataRequest failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readAccessToCustomerDataRequest(ctx, obj, m)
	return true
}

func readAccessToCustomerDataRequest(ctx context.Context, obj map[string]any, m *accessToCustomerDataRequestModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.ApprovalDecision = types.StringValue(getObjectJSON(obj, "ApprovalDecision"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.RequestId = types.StringValue(getString(obj, "RequestId"))
	m.ServiceName = types.StringValue(getObjectJSON(obj, "ServiceName"))
	_ = ctx
}

func (r *accessToCustomerDataRequestResource) reconcileState(cfg, read *accessToCustomerDataRequestModel) {
	read.ApprovalDecision = reconcile.KeepStr(cfg.ApprovalDecision, read.ApprovalDecision)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.RequestId = reconcile.KeepStr(cfg.RequestId, read.RequestId)
	read.ServiceName = reconcile.KeepStr(cfg.ServiceName, read.ServiceName)
}
