// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &cASMailboxResource{}
	_ resource.ResourceWithConfigure   = &cASMailboxResource{}
	_ resource.ResourceWithImportState = &cASMailboxResource{}
	_ resource.ResourceWithModifyPlan  = &cASMailboxResource{}
)

type cASMailboxResource struct{ client *clients.Client }

// NewCASMailboxResource manages the CASMailbox configuration (Get-CASMailbox / Set-CASMailbox); it adopts the existing object and is not deleted on destroy.
func NewCASMailboxResource() resource.Resource { return &cASMailboxResource{} }

type cASMailboxModel struct {
	ID                                      types.String `tfsdk:"id"`
	Identity                                types.String `tfsdk:"identity"`
	ActiveSyncAllowedDeviceIDs              types.Set    `tfsdk:"active_sync_allowed_device_i_ds"`
	ActiveSyncBlockedDeviceIDs              types.Set    `tfsdk:"active_sync_blocked_device_i_ds"`
	ActiveSyncDebugLogging                  types.Bool   `tfsdk:"active_sync_debug_logging"`
	ActiveSyncEnabled                       types.Bool   `tfsdk:"active_sync_enabled"`
	ActiveSyncMailboxPolicy                 types.String `tfsdk:"active_sync_mailbox_policy"`
	ActiveSyncSuppressReadReceipt           types.Bool   `tfsdk:"active_sync_suppress_read_receipt"`
	EwsAllowEntourage                       types.Bool   `tfsdk:"ews_allow_entourage"`
	EwsAllowList                            types.Set    `tfsdk:"ews_allow_list"`
	EwsAllowMacOutlook                      types.Bool   `tfsdk:"ews_allow_mac_outlook"`
	EwsAllowOutlook                         types.Bool   `tfsdk:"ews_allow_outlook"`
	EwsApplicationAccessPolicy              types.String `tfsdk:"ews_application_access_policy"`
	EwsBlockList                            types.Set    `tfsdk:"ews_block_list"`
	EwsEnabled                              types.Bool   `tfsdk:"ews_enabled"`
	ImapEnabled                             types.Bool   `tfsdk:"imap_enabled"`
	ImapForceICalForCalendarRetrievalOption types.Bool   `tfsdk:"imap_force_i_cal_for_calendar_retrieval_option"`
	ImapMessagesRetrievalMimeFormat         types.String `tfsdk:"imap_messages_retrieval_mime_format"`
	ImapSuppressReadReceipt                 types.Bool   `tfsdk:"imap_suppress_read_receipt"`
	ImapUseProtocolDefaults                 types.Bool   `tfsdk:"imap_use_protocol_defaults"`
	IsOptimizedForAccessibility             types.Bool   `tfsdk:"is_optimized_for_accessibility"`
	MAPIEnabled                             types.Bool   `tfsdk:"mapi_enabled"`
	MacOutlookEnabled                       types.Bool   `tfsdk:"mac_outlook_enabled"`
	OWAEnabled                              types.Bool   `tfsdk:"owa_enabled"`
	OWAforDevicesEnabled                    types.Bool   `tfsdk:"ow_afor_devices_enabled"`
	OneWinNativeOutlookEnabled              types.Bool   `tfsdk:"one_win_native_outlook_enabled"`
	OutlookMobileEnabled                    types.Bool   `tfsdk:"outlook_mobile_enabled"`
	OwaMailboxPolicy                        types.String `tfsdk:"owa_mailbox_policy"`
	PopEnabled                              types.Bool   `tfsdk:"pop_enabled"`
	PopForceICalForCalendarRetrievalOption  types.Bool   `tfsdk:"pop_force_i_cal_for_calendar_retrieval_option"`
	PopMessagesRetrievalMimeFormat          types.String `tfsdk:"pop_messages_retrieval_mime_format"`
	PopSuppressReadReceipt                  types.Bool   `tfsdk:"pop_suppress_read_receipt"`
	PopUseProtocolDefaults                  types.Bool   `tfsdk:"pop_use_protocol_defaults"`
	PublicFolderClientAccess                types.Bool   `tfsdk:"public_folder_client_access"`
	ShowGalAsDefaultView                    types.Bool   `tfsdk:"show_gal_as_default_view"`
	SmtpClientAuthenticationDisabled        types.Bool   `tfsdk:"smtp_client_authentication_disabled"`
	UniversalOutlookEnabled                 types.Bool   `tfsdk:"universal_outlook_enabled"`
}

func (r *cASMailboxResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cas_mailbox"
}

func (r *cASMailboxResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the CASMailbox configuration via Set-CASMailbox.",
		Attributes: map[string]schema.Attribute{
			"id":                                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                          schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"active_sync_allowed_device_i_ds":   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ActiveSyncAllowedDeviceIDs parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"active_sync_blocked_device_i_ds":   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ActiveSyncBlockedDeviceIDs parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"active_sync_debug_logging":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ActiveSyncDebugLogging parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"active_sync_enabled":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ActiveSyncEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"active_sync_mailbox_policy":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ActiveSyncMailboxPolicy parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"active_sync_suppress_read_receipt": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ActiveSyncSuppressReadReceipt parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"ews_allow_entourage":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EwsAllowEntourage parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"ews_allow_list":                    schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -EwsAllowList parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"ews_allow_mac_outlook":             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EwsAllowMacOutlook parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"ews_allow_outlook":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EwsAllowOutlook parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"ews_application_access_policy":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EwsApplicationAccessPolicy parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"ews_block_list":                    schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -EwsBlockList parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"ews_enabled":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EwsEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"imap_enabled":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ImapEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"imap_force_i_cal_for_calendar_retrieval_option": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ImapForceICalForCalendarRetrievalOption parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"imap_messages_retrieval_mime_format":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ImapMessagesRetrievalMimeFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"imap_suppress_read_receipt":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ImapSuppressReadReceipt parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"imap_use_protocol_defaults":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ImapUseProtocolDefaults parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_optimized_for_accessibility":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsOptimizedForAccessibility parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mapi_enabled":                                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MAPIEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mac_outlook_enabled":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MacOutlookEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"owa_enabled":                                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -OWAEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"ow_afor_devices_enabled":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -OWAforDevicesEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"one_win_native_outlook_enabled":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -OneWinNativeOutlookEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"outlook_mobile_enabled":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -OutlookMobileEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"owa_mailbox_policy":                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -OwaMailboxPolicy parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pop_enabled":                                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PopEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"pop_force_i_cal_for_calendar_retrieval_option":  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PopForceICalForCalendarRetrievalOption parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"pop_messages_retrieval_mime_format":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PopMessagesRetrievalMimeFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"pop_suppress_read_receipt":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PopSuppressReadReceipt parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"pop_use_protocol_defaults":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PopUseProtocolDefaults parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"public_folder_client_access":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PublicFolderClientAccess parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_gal_as_default_view":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowGalAsDefaultView parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"smtp_client_authentication_disabled":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SmtpClientAuthenticationDisabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"universal_outlook_enabled":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UniversalOutlookEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *cASMailboxResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *cASMailboxResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan cASMailboxModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config cASMailboxModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetCASMailboxParams{}
	sp.Identity = plan.Identity.ValueString()
	var cur *cASMailboxModel
	current := func() *cASMailboxModel {
		if cur == nil {
			var m cASMailboxModel
			if !r.refresh(ctx, plan.Identity.ValueString(), &m, &resp.Diagnostics, nil) {
				return nil
			}
			cur = &m
		}
		return cur
	}
	if !config.ActiveSyncAllowedDeviceIDs.IsNull() {
		if !plan.ActiveSyncAllowedDeviceIDs.IsNull() && !plan.ActiveSyncAllowedDeviceIDs.IsUnknown() {
			if v := toStringSlice(ctx, plan.ActiveSyncAllowedDeviceIDs, &resp.Diagnostics); len(v) > 0 {
				sp.ActiveSyncAllowedDeviceIDs = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ActiveSyncAllowedDeviceIDs, &resp.Diagnostics); len(rm) > 0 {
						sp.ActiveSyncAllowedDeviceIDsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !config.ActiveSyncBlockedDeviceIDs.IsNull() {
		if !plan.ActiveSyncBlockedDeviceIDs.IsNull() && !plan.ActiveSyncBlockedDeviceIDs.IsUnknown() {
			if v := toStringSlice(ctx, plan.ActiveSyncBlockedDeviceIDs, &resp.Diagnostics); len(v) > 0 {
				sp.ActiveSyncBlockedDeviceIDs = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ActiveSyncBlockedDeviceIDs, &resp.Diagnostics); len(rm) > 0 {
						sp.ActiveSyncBlockedDeviceIDsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !config.ActiveSyncDebugLogging.IsNull() {
		if !plan.ActiveSyncDebugLogging.IsUnknown() {
			sp.ActiveSyncDebugLogging = plan.ActiveSyncDebugLogging.ValueBoolPointer()
		}
	}
	if !config.ActiveSyncEnabled.IsNull() {
		if !plan.ActiveSyncEnabled.IsUnknown() {
			sp.ActiveSyncEnabled = plan.ActiveSyncEnabled.ValueBoolPointer()
		}
	}
	if v := config.ActiveSyncMailboxPolicy.ValueString(); v != "" {
		sp.ActiveSyncMailboxPolicy = objectParam(v)
	}
	if !config.ActiveSyncSuppressReadReceipt.IsNull() {
		if !plan.ActiveSyncSuppressReadReceipt.IsUnknown() {
			sp.ActiveSyncSuppressReadReceipt = plan.ActiveSyncSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !config.EwsAllowEntourage.IsNull() {
		if !plan.EwsAllowEntourage.IsUnknown() {
			sp.EwsAllowEntourage = plan.EwsAllowEntourage.ValueBoolPointer()
		}
	}
	if !config.EwsAllowList.IsNull() {
		if !plan.EwsAllowList.IsNull() && !plan.EwsAllowList.IsUnknown() {
			if v := toStringSlice(ctx, plan.EwsAllowList, &resp.Diagnostics); len(v) > 0 {
				sp.EwsAllowList = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.EwsAllowList, &resp.Diagnostics); len(rm) > 0 {
						sp.EwsAllowListDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !config.EwsAllowMacOutlook.IsNull() {
		if !plan.EwsAllowMacOutlook.IsUnknown() {
			sp.EwsAllowMacOutlook = plan.EwsAllowMacOutlook.ValueBoolPointer()
		}
	}
	if !config.EwsAllowOutlook.IsNull() {
		if !plan.EwsAllowOutlook.IsUnknown() {
			sp.EwsAllowOutlook = plan.EwsAllowOutlook.ValueBoolPointer()
		}
	}
	if v := config.EwsApplicationAccessPolicy.ValueString(); v != "" {
		sp.EwsApplicationAccessPolicy = objectParam(v)
	}
	if !config.EwsBlockList.IsNull() {
		if !plan.EwsBlockList.IsNull() && !plan.EwsBlockList.IsUnknown() {
			if v := toStringSlice(ctx, plan.EwsBlockList, &resp.Diagnostics); len(v) > 0 {
				sp.EwsBlockList = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.EwsBlockList, &resp.Diagnostics); len(rm) > 0 {
						sp.EwsBlockListDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !config.EwsEnabled.IsNull() {
		if !plan.EwsEnabled.IsUnknown() {
			sp.EwsEnabled = plan.EwsEnabled.ValueBoolPointer()
		}
	}
	if !config.ImapEnabled.IsNull() {
		if !plan.ImapEnabled.IsUnknown() {
			sp.ImapEnabled = plan.ImapEnabled.ValueBoolPointer()
		}
	}
	if !config.ImapForceICalForCalendarRetrievalOption.IsNull() {
		if !plan.ImapForceICalForCalendarRetrievalOption.IsUnknown() {
			sp.ImapForceICalForCalendarRetrievalOption = plan.ImapForceICalForCalendarRetrievalOption.ValueBoolPointer()
		}
	}
	if v := config.ImapMessagesRetrievalMimeFormat.ValueString(); v != "" {
		sp.ImapMessagesRetrievalMimeFormat = objectParam(v)
	}
	if !config.ImapSuppressReadReceipt.IsNull() {
		if !plan.ImapSuppressReadReceipt.IsUnknown() {
			sp.ImapSuppressReadReceipt = plan.ImapSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !config.ImapUseProtocolDefaults.IsNull() {
		if !plan.ImapUseProtocolDefaults.IsUnknown() {
			sp.ImapUseProtocolDefaults = plan.ImapUseProtocolDefaults.ValueBoolPointer()
		}
	}
	if !config.IsOptimizedForAccessibility.IsNull() {
		if !plan.IsOptimizedForAccessibility.IsUnknown() {
			sp.IsOptimizedForAccessibility = plan.IsOptimizedForAccessibility.ValueBoolPointer()
		}
	}
	if !config.MAPIEnabled.IsNull() {
		if !plan.MAPIEnabled.IsUnknown() {
			sp.MAPIEnabled = plan.MAPIEnabled.ValueBoolPointer()
		}
	}
	if !config.MacOutlookEnabled.IsNull() {
		if !plan.MacOutlookEnabled.IsUnknown() {
			sp.MacOutlookEnabled = plan.MacOutlookEnabled.ValueBoolPointer()
		}
	}
	if !config.OWAEnabled.IsNull() {
		if !plan.OWAEnabled.IsUnknown() {
			sp.OWAEnabled = plan.OWAEnabled.ValueBoolPointer()
		}
	}
	if !config.OWAforDevicesEnabled.IsNull() {
		if !plan.OWAforDevicesEnabled.IsUnknown() {
			sp.OWAforDevicesEnabled = plan.OWAforDevicesEnabled.ValueBoolPointer()
		}
	}
	if !config.OneWinNativeOutlookEnabled.IsNull() {
		if !plan.OneWinNativeOutlookEnabled.IsUnknown() {
			sp.OneWinNativeOutlookEnabled = plan.OneWinNativeOutlookEnabled.ValueBoolPointer()
		}
	}
	if !config.OutlookMobileEnabled.IsNull() {
		if !plan.OutlookMobileEnabled.IsUnknown() {
			sp.OutlookMobileEnabled = plan.OutlookMobileEnabled.ValueBoolPointer()
		}
	}
	if v := config.OwaMailboxPolicy.ValueString(); v != "" {
		sp.OwaMailboxPolicy = objectParam(v)
	}
	if !config.PopEnabled.IsNull() {
		if !plan.PopEnabled.IsUnknown() {
			sp.PopEnabled = plan.PopEnabled.ValueBoolPointer()
		}
	}
	if !config.PopForceICalForCalendarRetrievalOption.IsNull() {
		if !plan.PopForceICalForCalendarRetrievalOption.IsUnknown() {
			sp.PopForceICalForCalendarRetrievalOption = plan.PopForceICalForCalendarRetrievalOption.ValueBoolPointer()
		}
	}
	if v := config.PopMessagesRetrievalMimeFormat.ValueString(); v != "" {
		sp.PopMessagesRetrievalMimeFormat = objectParam(v)
	}
	if !config.PopSuppressReadReceipt.IsNull() {
		if !plan.PopSuppressReadReceipt.IsUnknown() {
			sp.PopSuppressReadReceipt = plan.PopSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !config.PopUseProtocolDefaults.IsNull() {
		if !plan.PopUseProtocolDefaults.IsUnknown() {
			sp.PopUseProtocolDefaults = plan.PopUseProtocolDefaults.ValueBoolPointer()
		}
	}
	if !config.PublicFolderClientAccess.IsNull() {
		if !plan.PublicFolderClientAccess.IsUnknown() {
			sp.PublicFolderClientAccess = plan.PublicFolderClientAccess.ValueBoolPointer()
		}
	}
	if !config.ShowGalAsDefaultView.IsNull() {
		if !plan.ShowGalAsDefaultView.IsUnknown() {
			sp.ShowGalAsDefaultView = plan.ShowGalAsDefaultView.ValueBoolPointer()
		}
	}
	if !config.SmtpClientAuthenticationDisabled.IsNull() {
		if !plan.SmtpClientAuthenticationDisabled.IsUnknown() {
			sp.SmtpClientAuthenticationDisabled = plan.SmtpClientAuthenticationDisabled.ValueBoolPointer()
		}
	}
	if !config.UniversalOutlookEnabled.IsNull() {
		if !plan.UniversalOutlookEnabled.IsUnknown() {
			sp.UniversalOutlookEnabled = plan.UniversalOutlookEnabled.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetCASMailbox(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-CASMailbox failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cASMailboxResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state cASMailboxModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *cASMailboxResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state cASMailboxModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetCASMailboxParams{}
	sp.Identity = id
	var cur *cASMailboxModel
	current := func() *cASMailboxModel {
		if cur == nil {
			var m cASMailboxModel
			if !r.refresh(ctx, id, &m, &resp.Diagnostics, nil) {
				return nil
			}
			cur = &m
		}
		return cur
	}
	if !plan.ActiveSyncAllowedDeviceIDs.Equal(state.ActiveSyncAllowedDeviceIDs) {
		if !plan.ActiveSyncAllowedDeviceIDs.IsNull() && !plan.ActiveSyncAllowedDeviceIDs.IsUnknown() {
			if v := toStringSlice(ctx, plan.ActiveSyncAllowedDeviceIDs, &resp.Diagnostics); len(v) > 0 {
				sp.ActiveSyncAllowedDeviceIDs = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ActiveSyncAllowedDeviceIDs, &resp.Diagnostics); len(rm) > 0 {
						sp.ActiveSyncAllowedDeviceIDsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ActiveSyncBlockedDeviceIDs.Equal(state.ActiveSyncBlockedDeviceIDs) {
		if !plan.ActiveSyncBlockedDeviceIDs.IsNull() && !plan.ActiveSyncBlockedDeviceIDs.IsUnknown() {
			if v := toStringSlice(ctx, plan.ActiveSyncBlockedDeviceIDs, &resp.Diagnostics); len(v) > 0 {
				sp.ActiveSyncBlockedDeviceIDs = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ActiveSyncBlockedDeviceIDs, &resp.Diagnostics); len(rm) > 0 {
						sp.ActiveSyncBlockedDeviceIDsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ActiveSyncDebugLogging.Equal(state.ActiveSyncDebugLogging) {
		if !plan.ActiveSyncDebugLogging.IsUnknown() {
			sp.ActiveSyncDebugLogging = plan.ActiveSyncDebugLogging.ValueBoolPointer()
		}
	}
	if !plan.ActiveSyncEnabled.Equal(state.ActiveSyncEnabled) {
		if !plan.ActiveSyncEnabled.IsUnknown() {
			sp.ActiveSyncEnabled = plan.ActiveSyncEnabled.ValueBoolPointer()
		}
	}
	if v := plan.ActiveSyncMailboxPolicy.ValueString(); v != "" {
		sp.ActiveSyncMailboxPolicy = objectParam(v)
	}
	if !plan.ActiveSyncSuppressReadReceipt.Equal(state.ActiveSyncSuppressReadReceipt) {
		if !plan.ActiveSyncSuppressReadReceipt.IsUnknown() {
			sp.ActiveSyncSuppressReadReceipt = plan.ActiveSyncSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !plan.EwsAllowEntourage.Equal(state.EwsAllowEntourage) {
		if !plan.EwsAllowEntourage.IsUnknown() {
			sp.EwsAllowEntourage = plan.EwsAllowEntourage.ValueBoolPointer()
		}
	}
	if !plan.EwsAllowList.Equal(state.EwsAllowList) {
		if !plan.EwsAllowList.IsNull() && !plan.EwsAllowList.IsUnknown() {
			if v := toStringSlice(ctx, plan.EwsAllowList, &resp.Diagnostics); len(v) > 0 {
				sp.EwsAllowList = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.EwsAllowList, &resp.Diagnostics); len(rm) > 0 {
						sp.EwsAllowListDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.EwsAllowMacOutlook.Equal(state.EwsAllowMacOutlook) {
		if !plan.EwsAllowMacOutlook.IsUnknown() {
			sp.EwsAllowMacOutlook = plan.EwsAllowMacOutlook.ValueBoolPointer()
		}
	}
	if !plan.EwsAllowOutlook.Equal(state.EwsAllowOutlook) {
		if !plan.EwsAllowOutlook.IsUnknown() {
			sp.EwsAllowOutlook = plan.EwsAllowOutlook.ValueBoolPointer()
		}
	}
	if v := plan.EwsApplicationAccessPolicy.ValueString(); v != "" {
		sp.EwsApplicationAccessPolicy = objectParam(v)
	}
	if !plan.EwsBlockList.Equal(state.EwsBlockList) {
		if !plan.EwsBlockList.IsNull() && !plan.EwsBlockList.IsUnknown() {
			if v := toStringSlice(ctx, plan.EwsBlockList, &resp.Diagnostics); len(v) > 0 {
				sp.EwsBlockList = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.EwsBlockList, &resp.Diagnostics); len(rm) > 0 {
						sp.EwsBlockListDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.EwsEnabled.Equal(state.EwsEnabled) {
		if !plan.EwsEnabled.IsUnknown() {
			sp.EwsEnabled = plan.EwsEnabled.ValueBoolPointer()
		}
	}
	if !plan.ImapEnabled.Equal(state.ImapEnabled) {
		if !plan.ImapEnabled.IsUnknown() {
			sp.ImapEnabled = plan.ImapEnabled.ValueBoolPointer()
		}
	}
	if !plan.ImapForceICalForCalendarRetrievalOption.Equal(state.ImapForceICalForCalendarRetrievalOption) {
		if !plan.ImapForceICalForCalendarRetrievalOption.IsUnknown() {
			sp.ImapForceICalForCalendarRetrievalOption = plan.ImapForceICalForCalendarRetrievalOption.ValueBoolPointer()
		}
	}
	if v := plan.ImapMessagesRetrievalMimeFormat.ValueString(); v != "" {
		sp.ImapMessagesRetrievalMimeFormat = objectParam(v)
	}
	if !plan.ImapSuppressReadReceipt.Equal(state.ImapSuppressReadReceipt) {
		if !plan.ImapSuppressReadReceipt.IsUnknown() {
			sp.ImapSuppressReadReceipt = plan.ImapSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !plan.ImapUseProtocolDefaults.Equal(state.ImapUseProtocolDefaults) {
		if !plan.ImapUseProtocolDefaults.IsUnknown() {
			sp.ImapUseProtocolDefaults = plan.ImapUseProtocolDefaults.ValueBoolPointer()
		}
	}
	if !plan.IsOptimizedForAccessibility.Equal(state.IsOptimizedForAccessibility) {
		if !plan.IsOptimizedForAccessibility.IsUnknown() {
			sp.IsOptimizedForAccessibility = plan.IsOptimizedForAccessibility.ValueBoolPointer()
		}
	}
	if !plan.MAPIEnabled.Equal(state.MAPIEnabled) {
		if !plan.MAPIEnabled.IsUnknown() {
			sp.MAPIEnabled = plan.MAPIEnabled.ValueBoolPointer()
		}
	}
	if !plan.MacOutlookEnabled.Equal(state.MacOutlookEnabled) {
		if !plan.MacOutlookEnabled.IsUnknown() {
			sp.MacOutlookEnabled = plan.MacOutlookEnabled.ValueBoolPointer()
		}
	}
	if !plan.OWAEnabled.Equal(state.OWAEnabled) {
		if !plan.OWAEnabled.IsUnknown() {
			sp.OWAEnabled = plan.OWAEnabled.ValueBoolPointer()
		}
	}
	if !plan.OWAforDevicesEnabled.Equal(state.OWAforDevicesEnabled) {
		if !plan.OWAforDevicesEnabled.IsUnknown() {
			sp.OWAforDevicesEnabled = plan.OWAforDevicesEnabled.ValueBoolPointer()
		}
	}
	if !plan.OneWinNativeOutlookEnabled.Equal(state.OneWinNativeOutlookEnabled) {
		if !plan.OneWinNativeOutlookEnabled.IsUnknown() {
			sp.OneWinNativeOutlookEnabled = plan.OneWinNativeOutlookEnabled.ValueBoolPointer()
		}
	}
	if !plan.OutlookMobileEnabled.Equal(state.OutlookMobileEnabled) {
		if !plan.OutlookMobileEnabled.IsUnknown() {
			sp.OutlookMobileEnabled = plan.OutlookMobileEnabled.ValueBoolPointer()
		}
	}
	if v := plan.OwaMailboxPolicy.ValueString(); v != "" {
		sp.OwaMailboxPolicy = objectParam(v)
	}
	if !plan.PopEnabled.Equal(state.PopEnabled) {
		if !plan.PopEnabled.IsUnknown() {
			sp.PopEnabled = plan.PopEnabled.ValueBoolPointer()
		}
	}
	if !plan.PopForceICalForCalendarRetrievalOption.Equal(state.PopForceICalForCalendarRetrievalOption) {
		if !plan.PopForceICalForCalendarRetrievalOption.IsUnknown() {
			sp.PopForceICalForCalendarRetrievalOption = plan.PopForceICalForCalendarRetrievalOption.ValueBoolPointer()
		}
	}
	if v := plan.PopMessagesRetrievalMimeFormat.ValueString(); v != "" {
		sp.PopMessagesRetrievalMimeFormat = objectParam(v)
	}
	if !plan.PopSuppressReadReceipt.Equal(state.PopSuppressReadReceipt) {
		if !plan.PopSuppressReadReceipt.IsUnknown() {
			sp.PopSuppressReadReceipt = plan.PopSuppressReadReceipt.ValueBoolPointer()
		}
	}
	if !plan.PopUseProtocolDefaults.Equal(state.PopUseProtocolDefaults) {
		if !plan.PopUseProtocolDefaults.IsUnknown() {
			sp.PopUseProtocolDefaults = plan.PopUseProtocolDefaults.ValueBoolPointer()
		}
	}
	if !plan.PublicFolderClientAccess.Equal(state.PublicFolderClientAccess) {
		if !plan.PublicFolderClientAccess.IsUnknown() {
			sp.PublicFolderClientAccess = plan.PublicFolderClientAccess.ValueBoolPointer()
		}
	}
	if !plan.ShowGalAsDefaultView.Equal(state.ShowGalAsDefaultView) {
		if !plan.ShowGalAsDefaultView.IsUnknown() {
			sp.ShowGalAsDefaultView = plan.ShowGalAsDefaultView.ValueBoolPointer()
		}
	}
	if !plan.SmtpClientAuthenticationDisabled.Equal(state.SmtpClientAuthenticationDisabled) {
		if !plan.SmtpClientAuthenticationDisabled.IsUnknown() {
			sp.SmtpClientAuthenticationDisabled = plan.SmtpClientAuthenticationDisabled.ValueBoolPointer()
		}
	}
	if !plan.UniversalOutlookEnabled.Equal(state.UniversalOutlookEnabled) {
		if !plan.UniversalOutlookEnabled.IsUnknown() {
			sp.UniversalOutlookEnabled = plan.UniversalOutlookEnabled.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetCASMailbox(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-CASMailbox failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cASMailboxResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("CASMailbox configuration not deleted", "This resource manages an existing CASMailbox configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *cASMailboxResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *cASMailboxResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan cASMailboxModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.EXO.GetCASMailbox(ctx, exo.GetCASMailboxParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur cASMailboxModel
	readCASMailbox(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.ActiveSyncAllowedDeviceIDs.IsUnknown() {
		plan.ActiveSyncAllowedDeviceIDs = cur.ActiveSyncAllowedDeviceIDs
	}
	if plan.ActiveSyncBlockedDeviceIDs.IsUnknown() {
		plan.ActiveSyncBlockedDeviceIDs = cur.ActiveSyncBlockedDeviceIDs
	}
	if plan.ActiveSyncDebugLogging.IsUnknown() {
		plan.ActiveSyncDebugLogging = cur.ActiveSyncDebugLogging
	}
	if plan.ActiveSyncEnabled.IsUnknown() {
		plan.ActiveSyncEnabled = cur.ActiveSyncEnabled
	}
	if plan.ActiveSyncMailboxPolicy.IsUnknown() {
		plan.ActiveSyncMailboxPolicy = cur.ActiveSyncMailboxPolicy
	}
	if plan.ActiveSyncSuppressReadReceipt.IsUnknown() {
		plan.ActiveSyncSuppressReadReceipt = cur.ActiveSyncSuppressReadReceipt
	}
	if plan.EwsAllowEntourage.IsUnknown() {
		plan.EwsAllowEntourage = cur.EwsAllowEntourage
	}
	if plan.EwsAllowList.IsUnknown() {
		plan.EwsAllowList = cur.EwsAllowList
	}
	if plan.EwsAllowMacOutlook.IsUnknown() {
		plan.EwsAllowMacOutlook = cur.EwsAllowMacOutlook
	}
	if plan.EwsAllowOutlook.IsUnknown() {
		plan.EwsAllowOutlook = cur.EwsAllowOutlook
	}
	if plan.EwsApplicationAccessPolicy.IsUnknown() {
		plan.EwsApplicationAccessPolicy = cur.EwsApplicationAccessPolicy
	}
	if plan.EwsBlockList.IsUnknown() {
		plan.EwsBlockList = cur.EwsBlockList
	}
	if plan.EwsEnabled.IsUnknown() {
		plan.EwsEnabled = cur.EwsEnabled
	}
	if plan.ImapEnabled.IsUnknown() {
		plan.ImapEnabled = cur.ImapEnabled
	}
	if plan.ImapForceICalForCalendarRetrievalOption.IsUnknown() {
		plan.ImapForceICalForCalendarRetrievalOption = cur.ImapForceICalForCalendarRetrievalOption
	}
	if plan.ImapMessagesRetrievalMimeFormat.IsUnknown() {
		plan.ImapMessagesRetrievalMimeFormat = cur.ImapMessagesRetrievalMimeFormat
	}
	if plan.ImapSuppressReadReceipt.IsUnknown() {
		plan.ImapSuppressReadReceipt = cur.ImapSuppressReadReceipt
	}
	if plan.ImapUseProtocolDefaults.IsUnknown() {
		plan.ImapUseProtocolDefaults = cur.ImapUseProtocolDefaults
	}
	if plan.IsOptimizedForAccessibility.IsUnknown() {
		plan.IsOptimizedForAccessibility = cur.IsOptimizedForAccessibility
	}
	if plan.MAPIEnabled.IsUnknown() {
		plan.MAPIEnabled = cur.MAPIEnabled
	}
	if plan.MacOutlookEnabled.IsUnknown() {
		plan.MacOutlookEnabled = cur.MacOutlookEnabled
	}
	if plan.OWAEnabled.IsUnknown() {
		plan.OWAEnabled = cur.OWAEnabled
	}
	if plan.OWAforDevicesEnabled.IsUnknown() {
		plan.OWAforDevicesEnabled = cur.OWAforDevicesEnabled
	}
	if plan.OneWinNativeOutlookEnabled.IsUnknown() {
		plan.OneWinNativeOutlookEnabled = cur.OneWinNativeOutlookEnabled
	}
	if plan.OutlookMobileEnabled.IsUnknown() {
		plan.OutlookMobileEnabled = cur.OutlookMobileEnabled
	}
	if plan.OwaMailboxPolicy.IsUnknown() {
		plan.OwaMailboxPolicy = cur.OwaMailboxPolicy
	}
	if plan.PopEnabled.IsUnknown() {
		plan.PopEnabled = cur.PopEnabled
	}
	if plan.PopForceICalForCalendarRetrievalOption.IsUnknown() {
		plan.PopForceICalForCalendarRetrievalOption = cur.PopForceICalForCalendarRetrievalOption
	}
	if plan.PopMessagesRetrievalMimeFormat.IsUnknown() {
		plan.PopMessagesRetrievalMimeFormat = cur.PopMessagesRetrievalMimeFormat
	}
	if plan.PopSuppressReadReceipt.IsUnknown() {
		plan.PopSuppressReadReceipt = cur.PopSuppressReadReceipt
	}
	if plan.PopUseProtocolDefaults.IsUnknown() {
		plan.PopUseProtocolDefaults = cur.PopUseProtocolDefaults
	}
	if plan.PublicFolderClientAccess.IsUnknown() {
		plan.PublicFolderClientAccess = cur.PublicFolderClientAccess
	}
	if plan.ShowGalAsDefaultView.IsUnknown() {
		plan.ShowGalAsDefaultView = cur.ShowGalAsDefaultView
	}
	if plan.SmtpClientAuthenticationDisabled.IsUnknown() {
		plan.SmtpClientAuthenticationDisabled = cur.SmtpClientAuthenticationDisabled
	}
	if plan.UniversalOutlookEnabled.IsUnknown() {
		plan.UniversalOutlookEnabled = cur.UniversalOutlookEnabled
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *cASMailboxResource) identityOf(m cASMailboxModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *cASMailboxResource) refresh(ctx context.Context, identity string, m *cASMailboxModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetCASMailbox(ctx, exo.GetCASMailboxParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-CASMailbox failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readCASMailbox(ctx, obj, m)
	return true
}

func readCASMailbox(ctx context.Context, obj map[string]any, m *cASMailboxModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.ActiveSyncAllowedDeviceIDs = stringSetValue(ctx, getStringSlice(obj, "ActiveSyncAllowedDeviceIDs"))
	m.ActiveSyncBlockedDeviceIDs = stringSetValue(ctx, getStringSlice(obj, "ActiveSyncBlockedDeviceIDs"))
	m.ActiveSyncDebugLogging = types.BoolValue(getBool(obj, "ActiveSyncDebugLogging"))
	m.ActiveSyncEnabled = types.BoolValue(getBool(obj, "ActiveSyncEnabled"))
	m.ActiveSyncMailboxPolicy = types.StringValue(getObjectJSON(obj, "ActiveSyncMailboxPolicy"))
	m.ActiveSyncSuppressReadReceipt = types.BoolValue(getBool(obj, "ActiveSyncSuppressReadReceipt"))
	m.EwsAllowEntourage = types.BoolValue(getBool(obj, "EwsAllowEntourage"))
	m.EwsAllowList = stringSetValue(ctx, getStringSlice(obj, "EwsAllowList"))
	m.EwsAllowMacOutlook = types.BoolValue(getBool(obj, "EwsAllowMacOutlook"))
	m.EwsAllowOutlook = types.BoolValue(getBool(obj, "EwsAllowOutlook"))
	m.EwsApplicationAccessPolicy = types.StringValue(getObjectJSON(obj, "EwsApplicationAccessPolicy"))
	m.EwsBlockList = stringSetValue(ctx, getStringSlice(obj, "EwsBlockList"))
	m.EwsEnabled = types.BoolValue(getBool(obj, "EwsEnabled"))
	m.ImapEnabled = types.BoolValue(getBool(obj, "ImapEnabled"))
	m.ImapForceICalForCalendarRetrievalOption = types.BoolValue(getBool(obj, "ImapForceICalForCalendarRetrievalOption"))
	m.ImapMessagesRetrievalMimeFormat = types.StringValue(getObjectJSON(obj, "ImapMessagesRetrievalMimeFormat"))
	m.ImapSuppressReadReceipt = types.BoolValue(getBool(obj, "ImapSuppressReadReceipt"))
	m.ImapUseProtocolDefaults = types.BoolValue(getBool(obj, "ImapUseProtocolDefaults"))
	m.IsOptimizedForAccessibility = types.BoolValue(getBool(obj, "IsOptimizedForAccessibility"))
	m.MAPIEnabled = types.BoolValue(getBool(obj, "MAPIEnabled"))
	m.MacOutlookEnabled = types.BoolValue(getBool(obj, "MacOutlookEnabled"))
	m.OWAEnabled = types.BoolValue(getBool(obj, "OWAEnabled"))
	m.OWAforDevicesEnabled = types.BoolValue(getBool(obj, "OWAforDevicesEnabled"))
	m.OneWinNativeOutlookEnabled = types.BoolValue(getBool(obj, "OneWinNativeOutlookEnabled"))
	m.OutlookMobileEnabled = types.BoolValue(getBool(obj, "OutlookMobileEnabled"))
	m.OwaMailboxPolicy = types.StringValue(getObjectJSON(obj, "OwaMailboxPolicy"))
	m.PopEnabled = types.BoolValue(getBool(obj, "PopEnabled"))
	m.PopForceICalForCalendarRetrievalOption = types.BoolValue(getBool(obj, "PopForceICalForCalendarRetrievalOption"))
	m.PopMessagesRetrievalMimeFormat = types.StringValue(getObjectJSON(obj, "PopMessagesRetrievalMimeFormat"))
	m.PopSuppressReadReceipt = types.BoolValue(getBool(obj, "PopSuppressReadReceipt"))
	m.PopUseProtocolDefaults = types.BoolValue(getBool(obj, "PopUseProtocolDefaults"))
	m.PublicFolderClientAccess = types.BoolValue(getBool(obj, "PublicFolderClientAccess"))
	m.ShowGalAsDefaultView = types.BoolValue(getBool(obj, "ShowGalAsDefaultView"))
	m.SmtpClientAuthenticationDisabled = types.BoolValue(getBool(obj, "SmtpClientAuthenticationDisabled"))
	m.UniversalOutlookEnabled = types.BoolValue(getBool(obj, "UniversalOutlookEnabled"))
	_ = ctx
}

func (r *cASMailboxResource) reconcileState(cfg, read *cASMailboxModel) {
	read.ActiveSyncAllowedDeviceIDs = reconcile.KeepSet(cfg.ActiveSyncAllowedDeviceIDs, read.ActiveSyncAllowedDeviceIDs)
	read.ActiveSyncBlockedDeviceIDs = reconcile.KeepSet(cfg.ActiveSyncBlockedDeviceIDs, read.ActiveSyncBlockedDeviceIDs)
	read.ActiveSyncDebugLogging = reconcile.KeepBool(cfg.ActiveSyncDebugLogging, read.ActiveSyncDebugLogging)
	read.ActiveSyncEnabled = reconcile.KeepBool(cfg.ActiveSyncEnabled, read.ActiveSyncEnabled)
	read.ActiveSyncMailboxPolicy = reconcile.KeepStr(cfg.ActiveSyncMailboxPolicy, read.ActiveSyncMailboxPolicy)
	read.ActiveSyncSuppressReadReceipt = reconcile.KeepBool(cfg.ActiveSyncSuppressReadReceipt, read.ActiveSyncSuppressReadReceipt)
	read.EwsAllowEntourage = reconcile.KeepBool(cfg.EwsAllowEntourage, read.EwsAllowEntourage)
	read.EwsAllowList = reconcile.KeepSet(cfg.EwsAllowList, read.EwsAllowList)
	read.EwsAllowMacOutlook = reconcile.KeepBool(cfg.EwsAllowMacOutlook, read.EwsAllowMacOutlook)
	read.EwsAllowOutlook = reconcile.KeepBool(cfg.EwsAllowOutlook, read.EwsAllowOutlook)
	read.EwsApplicationAccessPolicy = reconcile.KeepStr(cfg.EwsApplicationAccessPolicy, read.EwsApplicationAccessPolicy)
	read.EwsBlockList = reconcile.KeepSet(cfg.EwsBlockList, read.EwsBlockList)
	read.EwsEnabled = reconcile.KeepBool(cfg.EwsEnabled, read.EwsEnabled)
	read.ImapEnabled = reconcile.KeepBool(cfg.ImapEnabled, read.ImapEnabled)
	read.ImapForceICalForCalendarRetrievalOption = reconcile.KeepBool(cfg.ImapForceICalForCalendarRetrievalOption, read.ImapForceICalForCalendarRetrievalOption)
	read.ImapMessagesRetrievalMimeFormat = reconcile.KeepStr(cfg.ImapMessagesRetrievalMimeFormat, read.ImapMessagesRetrievalMimeFormat)
	read.ImapSuppressReadReceipt = reconcile.KeepBool(cfg.ImapSuppressReadReceipt, read.ImapSuppressReadReceipt)
	read.ImapUseProtocolDefaults = reconcile.KeepBool(cfg.ImapUseProtocolDefaults, read.ImapUseProtocolDefaults)
	read.IsOptimizedForAccessibility = reconcile.KeepBool(cfg.IsOptimizedForAccessibility, read.IsOptimizedForAccessibility)
	read.MAPIEnabled = reconcile.KeepBool(cfg.MAPIEnabled, read.MAPIEnabled)
	read.MacOutlookEnabled = reconcile.KeepBool(cfg.MacOutlookEnabled, read.MacOutlookEnabled)
	read.OWAEnabled = reconcile.KeepBool(cfg.OWAEnabled, read.OWAEnabled)
	read.OWAforDevicesEnabled = reconcile.KeepBool(cfg.OWAforDevicesEnabled, read.OWAforDevicesEnabled)
	read.OneWinNativeOutlookEnabled = reconcile.KeepBool(cfg.OneWinNativeOutlookEnabled, read.OneWinNativeOutlookEnabled)
	read.OutlookMobileEnabled = reconcile.KeepBool(cfg.OutlookMobileEnabled, read.OutlookMobileEnabled)
	read.OwaMailboxPolicy = reconcile.KeepStr(cfg.OwaMailboxPolicy, read.OwaMailboxPolicy)
	read.PopEnabled = reconcile.KeepBool(cfg.PopEnabled, read.PopEnabled)
	read.PopForceICalForCalendarRetrievalOption = reconcile.KeepBool(cfg.PopForceICalForCalendarRetrievalOption, read.PopForceICalForCalendarRetrievalOption)
	read.PopMessagesRetrievalMimeFormat = reconcile.KeepStr(cfg.PopMessagesRetrievalMimeFormat, read.PopMessagesRetrievalMimeFormat)
	read.PopSuppressReadReceipt = reconcile.KeepBool(cfg.PopSuppressReadReceipt, read.PopSuppressReadReceipt)
	read.PopUseProtocolDefaults = reconcile.KeepBool(cfg.PopUseProtocolDefaults, read.PopUseProtocolDefaults)
	read.PublicFolderClientAccess = reconcile.KeepBool(cfg.PublicFolderClientAccess, read.PublicFolderClientAccess)
	read.ShowGalAsDefaultView = reconcile.KeepBool(cfg.ShowGalAsDefaultView, read.ShowGalAsDefaultView)
	read.SmtpClientAuthenticationDisabled = reconcile.KeepBool(cfg.SmtpClientAuthenticationDisabled, read.SmtpClientAuthenticationDisabled)
	read.UniversalOutlookEnabled = reconcile.KeepBool(cfg.UniversalOutlookEnabled, read.UniversalOutlookEnabled)
}
