// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
)

var (
	_ datasource.DataSource              = &dlpPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &dlpPolicyListDataSource{}
)

type dlpPolicyListDataSource struct{ client *clients.Client }

// NewDlpPolicyListDataSource lists every DlpPolicy object (Get-DlpPolicy).
func NewDlpPolicyListDataSource() datasource.DataSource { return &dlpPolicyListDataSource{} }

type dlpPolicyListModel struct {
	Items []dlpPolicyModel `tfsdk:"dlp_policies"`
}

func (d *dlpPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dlp_policies"
}

func (d *dlpPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every DlpPolicy object (Get-DlpPolicy).",
		Attributes: map[string]schema.Attribute{
			"dlp_policies": schema.ListNestedAttribute{Computed: true, Description: "All DlpPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":      schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"description":   schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
				"mode":          schema.StringAttribute{Computed: true, Description: "Maps to the -Mode parameter."},
				"name":          schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"parameters":    schema.StringAttribute{Computed: true, Description: "Maps to the -Parameters parameter."},
				"state":         schema.StringAttribute{Computed: true, Description: "Maps to the -State parameter."},
				"template":      schema.StringAttribute{Computed: true, Description: "Maps to the -Template parameter."},
				"template_data": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -TemplateData parameter."},
			}}},
		},
	}
}

func (d *dlpPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *dlpPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.EXO.GetDlpPolicy(ctx, exo.GetDlpPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-DlpPolicy failed", err.Error())
		return
	}
	var data dlpPolicyListModel
	for _, obj := range res.Value {
		var e dlpPolicyModel
		readDlpPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
