// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
)

var (
	_ datasource.DataSource              = &dynamicDistributionGroupListDataSource{}
	_ datasource.DataSourceWithConfigure = &dynamicDistributionGroupListDataSource{}
)

type dynamicDistributionGroupListDataSource struct{ client *clients.Client }

// NewDynamicDistributionGroupListDataSource lists every DynamicDistributionGroup object (Get-DynamicDistributionGroup).
func NewDynamicDistributionGroupListDataSource() datasource.DataSource {
	return &dynamicDistributionGroupListDataSource{}
}

type dynamicDistributionGroupListModel struct {
	Items []dynamicDistributionGroupModel `tfsdk:"dynamic_distribution_groups"`
}

func (d *dynamicDistributionGroupListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_distribution_groups"
}

func (d *dynamicDistributionGroupListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every DynamicDistributionGroup object (Get-DynamicDistributionGroup).",
		Attributes: map[string]schema.Attribute{
			"dynamic_distribution_groups": schema.ListNestedAttribute{Computed: true, Description: "All DynamicDistributionGroup objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                             schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"accept_messages_only_from":            schema.StringAttribute{Computed: true, Description: "Maps to the -AcceptMessagesOnlyFrom parameter."},
				"accept_messages_only_from_dl_members": schema.StringAttribute{Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromDLMembers parameter."},
				"accept_messages_only_from_senders_or_members": schema.StringAttribute{Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromSendersOrMembers parameter."},
				"alias_": schema.StringAttribute{Computed: true, Description: "Maps to the -Alias parameter."},
				"bypass_moderation_from_senders_or_members": schema.StringAttribute{Computed: true, Description: "Maps to the -BypassModerationFromSendersOrMembers parameter."},
				"conditional_company":                       schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCompany parameter."},
				"conditional_custom_attribute1":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute1 parameter."},
				"conditional_custom_attribute10":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute10 parameter."},
				"conditional_custom_attribute11":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute11 parameter."},
				"conditional_custom_attribute12":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute12 parameter."},
				"conditional_custom_attribute13":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute13 parameter."},
				"conditional_custom_attribute14":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute14 parameter."},
				"conditional_custom_attribute15":            schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute15 parameter."},
				"conditional_custom_attribute2":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute2 parameter."},
				"conditional_custom_attribute3":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute3 parameter."},
				"conditional_custom_attribute4":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute4 parameter."},
				"conditional_custom_attribute5":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute5 parameter."},
				"conditional_custom_attribute6":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute6 parameter."},
				"conditional_custom_attribute7":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute7 parameter."},
				"conditional_custom_attribute8":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute8 parameter."},
				"conditional_custom_attribute9":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalCustomAttribute9 parameter."},
				"conditional_department":                    schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalDepartment parameter."},
				"conditional_state_or_province":             schema.StringAttribute{Computed: true, Description: "Maps to the -ConditionalStateOrProvince parameter."},
				"custom_attribute1":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute1 parameter."},
				"custom_attribute10":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute10 parameter."},
				"custom_attribute11":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute11 parameter."},
				"custom_attribute12":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute12 parameter."},
				"custom_attribute13":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute13 parameter."},
				"custom_attribute14":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute14 parameter."},
				"custom_attribute15":                        schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute15 parameter."},
				"custom_attribute2":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute2 parameter."},
				"custom_attribute3":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute3 parameter."},
				"custom_attribute4":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute4 parameter."},
				"custom_attribute5":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute5 parameter."},
				"custom_attribute6":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute6 parameter."},
				"custom_attribute7":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute7 parameter."},
				"custom_attribute8":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute8 parameter."},
				"custom_attribute9":                         schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute9 parameter."},
				"direct_membership_only":                    schema.BoolAttribute{Computed: true, Description: "Maps to the -DirectMembershipOnly parameter."},
				"display_name":                              schema.StringAttribute{Computed: true, Description: "Maps to the -DisplayName parameter."},
				"email_addresses":                           schema.StringAttribute{Computed: true, Description: "Maps to the -EmailAddresses parameter."},
				"extension_custom_attribute1":               schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute1 parameter."},
				"extension_custom_attribute2":               schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute2 parameter."},
				"extension_custom_attribute3":               schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute3 parameter."},
				"extension_custom_attribute4":               schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute4 parameter."},
				"extension_custom_attribute5":               schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute5 parameter."},
				"force_membership_refresh":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -ForceMembershipRefresh parameter."},
				"force_upgrade":                             schema.BoolAttribute{Computed: true, Description: "Maps to the -ForceUpgrade parameter."},
				"grant_send_on_behalf_to":                   schema.StringAttribute{Computed: true, Description: "Maps to the -GrantSendOnBehalfTo parameter."},
				"hidden_from_address_lists_enabled":         schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenFromAddressListsEnabled parameter."},
				"included_recipients":                       schema.StringAttribute{Computed: true, Description: "Maps to the -IncludedRecipients parameter."},
				"mail_tip":                                  schema.StringAttribute{Computed: true, Description: "Maps to the -MailTip parameter."},
				"mail_tip_translations":                     schema.StringAttribute{Computed: true, Description: "Maps to the -MailTipTranslations parameter."},
				"managed_by":                                schema.StringAttribute{Computed: true, Description: "Maps to the -ManagedBy parameter."},
				"moderated_by":                              schema.StringAttribute{Computed: true, Description: "Maps to the -ModeratedBy parameter."},
				"moderation_enabled":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -ModerationEnabled parameter."},
				"name":                                      schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"notes":                                     schema.StringAttribute{Computed: true, Description: "Maps to the -Notes parameter."},
				"organizational_unit":                       schema.StringAttribute{Computed: true, Description: "Maps to the -OrganizationalUnit parameter."},
				"phonetic_display_name":                     schema.StringAttribute{Computed: true, Description: "Maps to the -PhoneticDisplayName parameter."},
				"primary_smtp_address":                      schema.StringAttribute{Computed: true, Description: "Maps to the -PrimarySmtpAddress parameter."},
				"recipient_container":                       schema.StringAttribute{Computed: true, Description: "Maps to the -RecipientContainer parameter."},
				"recipient_filter":                          schema.StringAttribute{Computed: true, Description: "Maps to the -RecipientFilter parameter."},
				"reject_messages_from":                      schema.StringAttribute{Computed: true, Description: "Maps to the -RejectMessagesFrom parameter."},
				"reject_messages_from_dl_members":           schema.StringAttribute{Computed: true, Description: "Maps to the -RejectMessagesFromDLMembers parameter."},
				"reject_messages_from_senders_or_members":   schema.StringAttribute{Computed: true, Description: "Maps to the -RejectMessagesFromSendersOrMembers parameter."},
				"report_to_manager_enabled":                 schema.BoolAttribute{Computed: true, Description: "Maps to the -ReportToManagerEnabled parameter."},
				"report_to_originator_enabled":              schema.BoolAttribute{Computed: true, Description: "Maps to the -ReportToOriginatorEnabled parameter."},
				"require_sender_authentication_enabled":     schema.BoolAttribute{Computed: true, Description: "Maps to the -RequireSenderAuthenticationEnabled parameter."},
				"send_moderation_notifications":             schema.StringAttribute{Computed: true, Description: "Maps to the -SendModerationNotifications parameter."},
				"send_oof_message_to_originator_enabled":    schema.BoolAttribute{Computed: true, Description: "Maps to the -SendOofMessageToOriginatorEnabled parameter."},
				"simple_display_name":                       schema.StringAttribute{Computed: true, Description: "Maps to the -SimpleDisplayName parameter."},
				"update_member_count":                       schema.BoolAttribute{Computed: true, Description: "Maps to the -UpdateMemberCount parameter."},
				"windows_email_address":                     schema.StringAttribute{Computed: true, Description: "Maps to the -WindowsEmailAddress parameter."},
			}}},
		},
	}
}

func (d *dynamicDistributionGroupListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *dynamicDistributionGroupListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.EXO.GetDynamicDistributionGroup(ctx, exo.GetDynamicDistributionGroupParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-DynamicDistributionGroup failed", err.Error())
		return
	}
	var data dynamicDistributionGroupListModel
	for _, obj := range res.Value {
		var e dynamicDistributionGroupModel
		readDynamicDistributionGroup(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
