// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &emailAddressPolicyResource{}
	_ resource.ResourceWithConfigure   = &emailAddressPolicyResource{}
	_ resource.ResourceWithImportState = &emailAddressPolicyResource{}
)

type emailAddressPolicyResource struct{ client *clients.Client }

// NewEmailAddressPolicyResource manages the EmailAddressPolicy object (New-EmailAddressPolicy / Get-EmailAddressPolicy / Set-EmailAddressPolicy / Remove-EmailAddressPolicy).
func NewEmailAddressPolicyResource() resource.Resource { return &emailAddressPolicyResource{} }

type emailAddressPolicyModel struct {
	ID                                types.String `tfsdk:"id"`
	Identity                          types.String `tfsdk:"identity"`
	EnabledEmailAddressTemplates      types.String `tfsdk:"enabled_email_address_templates"`
	EnabledPrimarySMTPAddressTemplate types.String `tfsdk:"enabled_primary_smtp_address_template"`
	ForceUpgrade                      types.Bool   `tfsdk:"force_upgrade"`
	IncludeUnifiedGroupRecipients     types.Bool   `tfsdk:"include_unified_group_recipients"`
	ManagedByFilter                   types.String `tfsdk:"managed_by_filter"`
	Name                              types.String `tfsdk:"name"`
	Priority                          types.String `tfsdk:"priority"`
}

func (r *emailAddressPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_email_address_policy"
}

func (r *emailAddressPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the EmailAddressPolicy object via New-EmailAddressPolicy / Get-EmailAddressPolicy / Set-EmailAddressPolicy / Remove-EmailAddressPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                              schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"enabled_email_address_templates":       schema.StringAttribute{Required: true, Description: "Maps to the -EnabledEmailAddressTemplates parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"enabled_primary_smtp_address_template": schema.StringAttribute{Required: true, Description: "Maps to the -EnabledPrimarySMTPAddressTemplate parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"force_upgrade":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ForceUpgrade parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"include_unified_group_recipients":      schema.BoolAttribute{Required: true, Description: "Maps to the -IncludeUnifiedGroupRecipients parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"managed_by_filter":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ManagedByFilter parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"name":                                  schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"priority":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Priority parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *emailAddressPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *emailAddressPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan emailAddressPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewEmailAddressPolicyParams{
		EnabledPrimarySMTPAddressTemplate: plan.EnabledPrimarySMTPAddressTemplate.ValueString(),
		IncludeUnifiedGroupRecipients:     plan.IncludeUnifiedGroupRecipients.ValueBool(),
		ManagedByFilter:                   plan.ManagedByFilter.ValueString(),
		Name:                              plan.Name.ValueString(),
	}
	if v := plan.EnabledEmailAddressTemplates.ValueString(); v != "" {
		p.EnabledEmailAddressTemplates = v
	}
	if v := plan.Priority.ValueString(); v != "" {
		p.Priority = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.NewEmailAddressPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-EmailAddressPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-EmailAddressPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readEmailAddressPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emailAddressPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state emailAddressPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *emailAddressPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state emailAddressPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetEmailAddressPolicyParams{}
	sp.Identity = id
	sp.ForceUpgrade = plan.ForceUpgrade.ValueBool()
	if v := plan.Priority.ValueString(); v != "" {
		sp.Priority = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetEmailAddressPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-EmailAddressPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Priority": cfg.Priority,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emailAddressPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state emailAddressPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveEmailAddressPolicy(ctx, exo.RemoveEmailAddressPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-EmailAddressPolicy failed", err.Error())
		}
	}
}

func (r *emailAddressPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *emailAddressPolicyResource) identityOf(m emailAddressPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *emailAddressPolicyResource) refresh(ctx context.Context, identity string, m *emailAddressPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetEmailAddressPolicy(ctx, exo.GetEmailAddressPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-EmailAddressPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readEmailAddressPolicy(ctx, obj, m)
	return true
}

func readEmailAddressPolicy(ctx context.Context, obj map[string]any, m *emailAddressPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.EnabledEmailAddressTemplates = types.StringValue(getString(obj, "EnabledEmailAddressTemplates"))
	m.EnabledPrimarySMTPAddressTemplate = types.StringValue(getString(obj, "EnabledPrimarySMTPAddressTemplate"))
	m.ForceUpgrade = types.BoolValue(getBool(obj, "ForceUpgrade"))
	m.IncludeUnifiedGroupRecipients = types.BoolValue(getBool(obj, "IncludeUnifiedGroupRecipients"))
	m.ManagedByFilter = types.StringValue(getString(obj, "ManagedByFilter"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Priority = types.StringValue(getString(obj, "Priority"))
	_ = ctx
}

func (r *emailAddressPolicyResource) reconcileState(cfg, read *emailAddressPolicyModel) {
	read.EnabledEmailAddressTemplates = reconcile.KeepStr(cfg.EnabledEmailAddressTemplates, read.EnabledEmailAddressTemplates)
	read.EnabledPrimarySMTPAddressTemplate = reconcile.KeepStr(cfg.EnabledPrimarySMTPAddressTemplate, read.EnabledPrimarySMTPAddressTemplate)
	read.ForceUpgrade = reconcile.KeepBool(cfg.ForceUpgrade, read.ForceUpgrade)
	read.IncludeUnifiedGroupRecipients = reconcile.KeepBool(cfg.IncludeUnifiedGroupRecipients, read.IncludeUnifiedGroupRecipients)
	read.ManagedByFilter = reconcile.KeepStr(cfg.ManagedByFilter, read.ManagedByFilter)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Priority = reconcile.KeepStr(cfg.Priority, read.Priority)
}
