// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &eventsFromEmailConfigurationResource{}
	_ resource.ResourceWithConfigure   = &eventsFromEmailConfigurationResource{}
	_ resource.ResourceWithImportState = &eventsFromEmailConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &eventsFromEmailConfigurationResource{}
)

type eventsFromEmailConfigurationResource struct{ client *clients.Client }

// NewEventsFromEmailConfigurationResource manages the EventsFromEmailConfiguration configuration (Get-EventsFromEmailConfiguration / Set-EventsFromEmailConfiguration); it adopts the existing object and is not deleted on destroy.
func NewEventsFromEmailConfigurationResource() resource.Resource {
	return &eventsFromEmailConfigurationResource{}
}

type eventsFromEmailConfigurationModel struct {
	ID                                          types.String `tfsdk:"id"`
	Identity                                    types.String `tfsdk:"identity"`
	CreateEventsFromEmailAsPrivate              types.Bool   `tfsdk:"create_events_from_email_as_private"`
	EventReservationProcessingLevel             types.String `tfsdk:"event_reservation_processing_level"`
	FlightReservationProcessingLevel            types.String `tfsdk:"flight_reservation_processing_level"`
	FoodEstablishmentReservationProcessingLevel types.String `tfsdk:"food_establishment_reservation_processing_level"`
	InvoiceProcessingLevel                      types.String `tfsdk:"invoice_processing_level"`
	LodgingReservationProcessingLevel           types.String `tfsdk:"lodging_reservation_processing_level"`
	ParcelDeliveryProcessingLevel               types.String `tfsdk:"parcel_delivery_processing_level"`
	RentalCarReservationProcessingLevel         types.String `tfsdk:"rental_car_reservation_processing_level"`
	ResetSettings                               types.Bool   `tfsdk:"reset_settings"`
	ServiceReservationProcessingLevel           types.String `tfsdk:"service_reservation_processing_level"`
}

func (r *eventsFromEmailConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_events_from_email_configuration"
}

func (r *eventsFromEmailConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the EventsFromEmailConfiguration configuration via Set-EventsFromEmailConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                  schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                            schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"create_events_from_email_as_private": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CreateEventsFromEmailAsPrivate parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"event_reservation_processing_level":  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EventReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"flight_reservation_processing_level": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -FlightReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"food_establishment_reservation_processing_level": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -FoodEstablishmentReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"invoice_processing_level":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -InvoiceProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"lodging_reservation_processing_level":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LodgingReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"parcel_delivery_processing_level":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ParcelDeliveryProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"rental_car_reservation_processing_level":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RentalCarReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"reset_settings":                                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ResetSettings parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"service_reservation_processing_level":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ServiceReservationProcessingLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *eventsFromEmailConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *eventsFromEmailConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan eventsFromEmailConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config eventsFromEmailConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetEventsFromEmailConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if !config.CreateEventsFromEmailAsPrivate.IsNull() {
		if !plan.CreateEventsFromEmailAsPrivate.IsUnknown() {
			sp.CreateEventsFromEmailAsPrivate = plan.CreateEventsFromEmailAsPrivate.ValueBoolPointer()
		}
	}
	if !config.EventReservationProcessingLevel.IsNull() {
		sp.EventReservationProcessingLevel = plan.EventReservationProcessingLevel.ValueString()
	}
	if !config.FlightReservationProcessingLevel.IsNull() {
		sp.FlightReservationProcessingLevel = plan.FlightReservationProcessingLevel.ValueString()
	}
	if !config.FoodEstablishmentReservationProcessingLevel.IsNull() {
		sp.FoodEstablishmentReservationProcessingLevel = plan.FoodEstablishmentReservationProcessingLevel.ValueString()
	}
	if !config.InvoiceProcessingLevel.IsNull() {
		sp.InvoiceProcessingLevel = plan.InvoiceProcessingLevel.ValueString()
	}
	if !config.LodgingReservationProcessingLevel.IsNull() {
		sp.LodgingReservationProcessingLevel = plan.LodgingReservationProcessingLevel.ValueString()
	}
	if !config.ParcelDeliveryProcessingLevel.IsNull() {
		sp.ParcelDeliveryProcessingLevel = plan.ParcelDeliveryProcessingLevel.ValueString()
	}
	if !config.RentalCarReservationProcessingLevel.IsNull() {
		sp.RentalCarReservationProcessingLevel = plan.RentalCarReservationProcessingLevel.ValueString()
	}
	if !config.ResetSettings.IsNull() {
		sp.ResetSettings = plan.ResetSettings.ValueBool()
	}
	if !config.ServiceReservationProcessingLevel.IsNull() {
		sp.ServiceReservationProcessingLevel = plan.ServiceReservationProcessingLevel.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.SetEventsFromEmailConfiguration, sp, isNotFound); err != nil {
		resp.Diagnostics.AddError("Set-EventsFromEmailConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *eventsFromEmailConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state eventsFromEmailConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *eventsFromEmailConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state eventsFromEmailConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetEventsFromEmailConfigurationParams{}
	sp.Identity = id
	if !plan.CreateEventsFromEmailAsPrivate.Equal(state.CreateEventsFromEmailAsPrivate) {
		if !plan.CreateEventsFromEmailAsPrivate.IsUnknown() {
			sp.CreateEventsFromEmailAsPrivate = plan.CreateEventsFromEmailAsPrivate.ValueBoolPointer()
		}
	}
	if !plan.EventReservationProcessingLevel.Equal(state.EventReservationProcessingLevel) {
		sp.EventReservationProcessingLevel = plan.EventReservationProcessingLevel.ValueString()
	}
	if !plan.FlightReservationProcessingLevel.Equal(state.FlightReservationProcessingLevel) {
		sp.FlightReservationProcessingLevel = plan.FlightReservationProcessingLevel.ValueString()
	}
	if !plan.FoodEstablishmentReservationProcessingLevel.Equal(state.FoodEstablishmentReservationProcessingLevel) {
		sp.FoodEstablishmentReservationProcessingLevel = plan.FoodEstablishmentReservationProcessingLevel.ValueString()
	}
	if !plan.InvoiceProcessingLevel.Equal(state.InvoiceProcessingLevel) {
		sp.InvoiceProcessingLevel = plan.InvoiceProcessingLevel.ValueString()
	}
	if !plan.LodgingReservationProcessingLevel.Equal(state.LodgingReservationProcessingLevel) {
		sp.LodgingReservationProcessingLevel = plan.LodgingReservationProcessingLevel.ValueString()
	}
	if !plan.ParcelDeliveryProcessingLevel.Equal(state.ParcelDeliveryProcessingLevel) {
		sp.ParcelDeliveryProcessingLevel = plan.ParcelDeliveryProcessingLevel.ValueString()
	}
	if !plan.RentalCarReservationProcessingLevel.Equal(state.RentalCarReservationProcessingLevel) {
		sp.RentalCarReservationProcessingLevel = plan.RentalCarReservationProcessingLevel.ValueString()
	}
	if !plan.ResetSettings.Equal(state.ResetSettings) {
		sp.ResetSettings = plan.ResetSettings.ValueBool()
	}
	if !plan.ServiceReservationProcessingLevel.Equal(state.ServiceReservationProcessingLevel) {
		sp.ServiceReservationProcessingLevel = plan.ServiceReservationProcessingLevel.ValueString()
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.SetEventsFromEmailConfiguration, sp, isNotFound); err != nil {
		resp.Diagnostics.AddError("Set-EventsFromEmailConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"EventReservationProcessingLevel":             cfg.EventReservationProcessingLevel,
		"FlightReservationProcessingLevel":            cfg.FlightReservationProcessingLevel,
		"FoodEstablishmentReservationProcessingLevel": cfg.FoodEstablishmentReservationProcessingLevel,
		"InvoiceProcessingLevel":                      cfg.InvoiceProcessingLevel,
		"LodgingReservationProcessingLevel":           cfg.LodgingReservationProcessingLevel,
		"ParcelDeliveryProcessingLevel":               cfg.ParcelDeliveryProcessingLevel,
		"RentalCarReservationProcessingLevel":         cfg.RentalCarReservationProcessingLevel,
		"ServiceReservationProcessingLevel":           cfg.ServiceReservationProcessingLevel,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	if !cfg.ID.IsUnknown() && !cfg.ID.IsNull() {
		plan.ID = cfg.ID
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *eventsFromEmailConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("EventsFromEmailConfiguration configuration not deleted", "This resource manages an existing EventsFromEmailConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *eventsFromEmailConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *eventsFromEmailConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan eventsFromEmailConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.EXO.GetEventsFromEmailConfiguration(ctx, exo.GetEventsFromEmailConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur eventsFromEmailConfigurationModel
	readEventsFromEmailConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.CreateEventsFromEmailAsPrivate.IsUnknown() {
		plan.CreateEventsFromEmailAsPrivate = cur.CreateEventsFromEmailAsPrivate
	}
	if plan.EventReservationProcessingLevel.IsUnknown() {
		plan.EventReservationProcessingLevel = cur.EventReservationProcessingLevel
	}
	if plan.FlightReservationProcessingLevel.IsUnknown() {
		plan.FlightReservationProcessingLevel = cur.FlightReservationProcessingLevel
	}
	if plan.FoodEstablishmentReservationProcessingLevel.IsUnknown() {
		plan.FoodEstablishmentReservationProcessingLevel = cur.FoodEstablishmentReservationProcessingLevel
	}
	if plan.InvoiceProcessingLevel.IsUnknown() {
		plan.InvoiceProcessingLevel = cur.InvoiceProcessingLevel
	}
	if plan.LodgingReservationProcessingLevel.IsUnknown() {
		plan.LodgingReservationProcessingLevel = cur.LodgingReservationProcessingLevel
	}
	if plan.ParcelDeliveryProcessingLevel.IsUnknown() {
		plan.ParcelDeliveryProcessingLevel = cur.ParcelDeliveryProcessingLevel
	}
	if plan.RentalCarReservationProcessingLevel.IsUnknown() {
		plan.RentalCarReservationProcessingLevel = cur.RentalCarReservationProcessingLevel
	}
	if plan.ResetSettings.IsUnknown() {
		plan.ResetSettings = cur.ResetSettings
	}
	if plan.ServiceReservationProcessingLevel.IsUnknown() {
		plan.ServiceReservationProcessingLevel = cur.ServiceReservationProcessingLevel
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *eventsFromEmailConfigurationResource) identityOf(m eventsFromEmailConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *eventsFromEmailConfigurationResource) refresh(ctx context.Context, identity string, m *eventsFromEmailConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetEventsFromEmailConfiguration(ctx, exo.GetEventsFromEmailConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-EventsFromEmailConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readEventsFromEmailConfiguration(ctx, obj, m)
	return true
}

func readEventsFromEmailConfiguration(ctx context.Context, obj map[string]any, m *eventsFromEmailConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.CreateEventsFromEmailAsPrivate = types.BoolValue(getBool(obj, "CreateEventsFromEmailAsPrivate"))
	m.EventReservationProcessingLevel = types.StringValue(getString(obj, "EventReservationProcessingLevel"))
	m.FlightReservationProcessingLevel = types.StringValue(getString(obj, "FlightReservationProcessingLevel"))
	m.FoodEstablishmentReservationProcessingLevel = types.StringValue(getString(obj, "FoodEstablishmentReservationProcessingLevel"))
	m.InvoiceProcessingLevel = types.StringValue(getString(obj, "InvoiceProcessingLevel"))
	m.LodgingReservationProcessingLevel = types.StringValue(getString(obj, "LodgingReservationProcessingLevel"))
	m.ParcelDeliveryProcessingLevel = types.StringValue(getString(obj, "ParcelDeliveryProcessingLevel"))
	m.RentalCarReservationProcessingLevel = types.StringValue(getString(obj, "RentalCarReservationProcessingLevel"))
	m.ResetSettings = types.BoolValue(getBool(obj, "ResetSettings"))
	m.ServiceReservationProcessingLevel = types.StringValue(getString(obj, "ServiceReservationProcessingLevel"))
	_ = ctx
}

func (r *eventsFromEmailConfigurationResource) reconcileState(cfg, read *eventsFromEmailConfigurationModel) {
	read.CreateEventsFromEmailAsPrivate = reconcile.KeepBool(cfg.CreateEventsFromEmailAsPrivate, read.CreateEventsFromEmailAsPrivate)
	read.EventReservationProcessingLevel = reconcile.KeepStr(cfg.EventReservationProcessingLevel, read.EventReservationProcessingLevel)
	read.FlightReservationProcessingLevel = reconcile.KeepStr(cfg.FlightReservationProcessingLevel, read.FlightReservationProcessingLevel)
	read.FoodEstablishmentReservationProcessingLevel = reconcile.KeepStr(cfg.FoodEstablishmentReservationProcessingLevel, read.FoodEstablishmentReservationProcessingLevel)
	read.InvoiceProcessingLevel = reconcile.KeepStr(cfg.InvoiceProcessingLevel, read.InvoiceProcessingLevel)
	read.LodgingReservationProcessingLevel = reconcile.KeepStr(cfg.LodgingReservationProcessingLevel, read.LodgingReservationProcessingLevel)
	read.ParcelDeliveryProcessingLevel = reconcile.KeepStr(cfg.ParcelDeliveryProcessingLevel, read.ParcelDeliveryProcessingLevel)
	read.RentalCarReservationProcessingLevel = reconcile.KeepStr(cfg.RentalCarReservationProcessingLevel, read.RentalCarReservationProcessingLevel)
	read.ResetSettings = reconcile.KeepBool(cfg.ResetSettings, read.ResetSettings)
	read.ServiceReservationProcessingLevel = reconcile.KeepStr(cfg.ServiceReservationProcessingLevel, read.ServiceReservationProcessingLevel)
}
