// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &exoSecOpsOverrideRuleDataSource{}
	_ datasource.DataSourceWithConfigure = &exoSecOpsOverrideRuleDataSource{}
)

type exoSecOpsOverrideRuleDataSource struct{ client *clients.Client }

// NewExoSecOpsOverrideRuleDataSource looks up a ExoSecOpsOverrideRule object (Get-ExoSecOpsOverrideRule).
func NewExoSecOpsOverrideRuleDataSource() datasource.DataSource {
	return &exoSecOpsOverrideRuleDataSource{}
}

func (d *exoSecOpsOverrideRuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_exo_sec_ops_override_rule"
}

func (d *exoSecOpsOverrideRuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing ExoSecOpsOverrideRule object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"comment":  schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"name":     schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"policy":   schema.StringAttribute{Computed: true, Description: "Maps to the -Policy parameter."},
		},
	}
}

func (d *exoSecOpsOverrideRuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *exoSecOpsOverrideRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data exoSecOpsOverrideRuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.EXO.GetExoSecOpsOverrideRule(ctx, exo.GetExoSecOpsOverrideRuleParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-ExoSecOpsOverrideRule failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("ExoSecOpsOverrideRule not found", "no ExoSecOpsOverrideRule object for identity "+identity)
		return
	}
	readExoSecOpsOverrideRule(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
