// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &federatedOrganizationIdentifierResource{}
	_ resource.ResourceWithConfigure   = &federatedOrganizationIdentifierResource{}
	_ resource.ResourceWithImportState = &federatedOrganizationIdentifierResource{}
	_ resource.ResourceWithModifyPlan  = &federatedOrganizationIdentifierResource{}
)

type federatedOrganizationIdentifierResource struct{ client *clients.Client }

// NewFederatedOrganizationIdentifierResource manages the FederatedOrganizationIdentifier configuration (Get-FederatedOrganizationIdentifier / Set-FederatedOrganizationIdentifier); it adopts the existing object and is not deleted on destroy.
func NewFederatedOrganizationIdentifierResource() resource.Resource {
	return &federatedOrganizationIdentifierResource{}
}

type federatedOrganizationIdentifierModel struct {
	ID                        types.String `tfsdk:"id"`
	Identity                  types.String `tfsdk:"identity"`
	AccountNamespace          types.String `tfsdk:"account_namespace"`
	DefaultDomain             types.String `tfsdk:"default_domain"`
	DelegationFederationTrust types.String `tfsdk:"delegation_federation_trust"`
	Enabled                   types.Bool   `tfsdk:"enabled"`
	OrganizationContact       types.String `tfsdk:"organization_contact"`
}

func (r *federatedOrganizationIdentifierResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_federated_organization_identifier"
}

func (r *federatedOrganizationIdentifierResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FederatedOrganizationIdentifier configuration via Set-FederatedOrganizationIdentifier.",
		Attributes: map[string]schema.Attribute{
			"id":                          schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                    schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"account_namespace":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AccountNamespace parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_domain":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultDomain parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"delegation_federation_trust": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DelegationFederationTrust parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"organization_contact":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -OrganizationContact parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *federatedOrganizationIdentifierResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *federatedOrganizationIdentifierResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan federatedOrganizationIdentifierModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config federatedOrganizationIdentifierModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetFederatedOrganizationIdentifierParams{}
	sp.Identity = plan.Identity.ValueString()
	if v := config.AccountNamespace.ValueString(); v != "" {
		sp.AccountNamespace = objectParam(v)
	}
	if v := config.DefaultDomain.ValueString(); v != "" {
		sp.DefaultDomain = objectParam(v)
	}
	if v := config.DelegationFederationTrust.ValueString(); v != "" {
		sp.DelegationFederationTrust = objectParam(v)
	}
	if !config.Enabled.IsNull() {
		if !plan.Enabled.IsUnknown() {
			sp.Enabled = plan.Enabled.ValueBoolPointer()
		}
	}
	if v := config.OrganizationContact.ValueString(); v != "" {
		sp.OrganizationContact = objectParam(v)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.SetFederatedOrganizationIdentifier, sp, isNotFound); err != nil {
		resp.Diagnostics.AddError("Set-FederatedOrganizationIdentifier failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *federatedOrganizationIdentifierResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state federatedOrganizationIdentifierModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *federatedOrganizationIdentifierResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state federatedOrganizationIdentifierModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetFederatedOrganizationIdentifierParams{}
	sp.Identity = id
	if !plan.AccountNamespace.Equal(state.AccountNamespace) {
		if v := plan.AccountNamespace.ValueString(); v != "" {
			sp.AccountNamespace = objectParam(v)
		}
	}
	if !plan.DefaultDomain.Equal(state.DefaultDomain) {
		if v := plan.DefaultDomain.ValueString(); v != "" {
			sp.DefaultDomain = objectParam(v)
		}
	}
	if !plan.DelegationFederationTrust.Equal(state.DelegationFederationTrust) {
		if v := plan.DelegationFederationTrust.ValueString(); v != "" {
			sp.DelegationFederationTrust = objectParam(v)
		}
	}
	if !plan.Enabled.Equal(state.Enabled) {
		if !plan.Enabled.IsUnknown() {
			sp.Enabled = plan.Enabled.ValueBoolPointer()
		}
	}
	if !plan.OrganizationContact.Equal(state.OrganizationContact) {
		if v := plan.OrganizationContact.ValueString(); v != "" {
			sp.OrganizationContact = objectParam(v)
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.SetFederatedOrganizationIdentifier, sp, isNotFound); err != nil {
		resp.Diagnostics.AddError("Set-FederatedOrganizationIdentifier failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	if !cfg.ID.IsUnknown() && !cfg.ID.IsNull() {
		plan.ID = cfg.ID
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *federatedOrganizationIdentifierResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("FederatedOrganizationIdentifier configuration not deleted", "This resource manages an existing FederatedOrganizationIdentifier configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *federatedOrganizationIdentifierResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *federatedOrganizationIdentifierResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan federatedOrganizationIdentifierModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.EXO.GetFederatedOrganizationIdentifier(ctx, exo.GetFederatedOrganizationIdentifierParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur federatedOrganizationIdentifierModel
	readFederatedOrganizationIdentifier(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AccountNamespace.IsUnknown() {
		plan.AccountNamespace = cur.AccountNamespace
	}
	if plan.DefaultDomain.IsUnknown() {
		plan.DefaultDomain = cur.DefaultDomain
	}
	if plan.DelegationFederationTrust.IsUnknown() {
		plan.DelegationFederationTrust = cur.DelegationFederationTrust
	}
	if plan.Enabled.IsUnknown() {
		plan.Enabled = cur.Enabled
	}
	if plan.OrganizationContact.IsUnknown() {
		plan.OrganizationContact = cur.OrganizationContact
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *federatedOrganizationIdentifierResource) identityOf(m federatedOrganizationIdentifierModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *federatedOrganizationIdentifierResource) refresh(ctx context.Context, identity string, m *federatedOrganizationIdentifierModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetFederatedOrganizationIdentifier(ctx, exo.GetFederatedOrganizationIdentifierParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FederatedOrganizationIdentifier failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFederatedOrganizationIdentifier(ctx, obj, m)
	return true
}

func readFederatedOrganizationIdentifier(ctx context.Context, obj map[string]any, m *federatedOrganizationIdentifierModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AccountNamespace = types.StringValue(getObjectJSON(obj, "AccountNamespace"))
	m.DefaultDomain = types.StringValue(getObjectJSON(obj, "DefaultDomain"))
	m.DelegationFederationTrust = types.StringValue(getObjectJSON(obj, "DelegationFederationTrust"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.OrganizationContact = types.StringValue(getObjectJSON(obj, "OrganizationContact"))
	_ = ctx
}

func (r *federatedOrganizationIdentifierResource) reconcileState(cfg, read *federatedOrganizationIdentifierModel) {
	read.AccountNamespace = reconcile.KeepStr(cfg.AccountNamespace, read.AccountNamespace)
	read.DefaultDomain = reconcile.KeepStr(cfg.DefaultDomain, read.DefaultDomain)
	read.DelegationFederationTrust = reconcile.KeepStr(cfg.DelegationFederationTrust, read.DelegationFederationTrust)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.OrganizationContact = reconcile.KeepStr(cfg.OrganizationContact, read.OrganizationContact)
}
