// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &groupDataSource{}
	_ datasource.DataSourceWithConfigure = &groupDataSource{}
)

type groupDataSource struct{ client *clients.Client }

// NewGroupDataSource looks up a Group object (Get-Group).
func NewGroupDataSource() datasource.DataSource { return &groupDataSource{} }

func (d *groupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_group"
}

func (d *groupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing Group object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":              schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"description":           schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"display_name":          schema.StringAttribute{Computed: true, Description: "Maps to the -DisplayName parameter."},
			"is_hierarchical_group": schema.BoolAttribute{Computed: true, Description: "Maps to the -IsHierarchicalGroup parameter."},
			"managed_by":            schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ManagedBy parameter."},
			"name":                  schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"notes":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Notes parameter."},
			"phonetic_display_name": schema.StringAttribute{Computed: true, Description: "Maps to the -PhoneticDisplayName parameter."},
			"seniority_index":       schema.StringAttribute{Computed: true, Description: "Maps to the -SeniorityIndex parameter."},
			"simple_display_name":   schema.StringAttribute{Computed: true, Description: "Maps to the -SimpleDisplayName parameter."},
			"universal":             schema.BoolAttribute{Computed: true, Description: "Maps to the -Universal parameter."},
			"windows_email_address": schema.StringAttribute{Computed: true, Description: "Maps to the -WindowsEmailAddress parameter."},
		},
	}
}

func (d *groupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *groupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data groupModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.EXO.GetGroup(ctx, exo.GetGroupParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-Group failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("Group not found", "no Group object for identity "+identity)
		return
	}
	readGroup(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
