// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &hVEAccountSettingsResource{}
	_ resource.ResourceWithConfigure   = &hVEAccountSettingsResource{}
	_ resource.ResourceWithImportState = &hVEAccountSettingsResource{}
)

type hVEAccountSettingsResource struct{ client *clients.Client }

// NewHVEAccountSettingsResource manages the HVEAccountSettings configuration (Get-HVEAccountSettings / Set-HVEAccountSettings); it adopts the existing object and is not deleted on destroy.
func NewHVEAccountSettingsResource() resource.Resource { return &hVEAccountSettingsResource{} }

type hVEAccountSettingsModel struct {
	ID       types.String `tfsdk:"id"`
	Identity types.String `tfsdk:"identity"`
	ReplyTo  types.String `tfsdk:"reply_to"`
}

func (r *hVEAccountSettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hve_account_settings"
}

func (r *hVEAccountSettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the HVEAccountSettings configuration via Set-HVEAccountSettings.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"reply_to": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReplyTo parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *hVEAccountSettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *hVEAccountSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan hVEAccountSettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetHVEAccountSettingsParams{}
	sp.Identity = plan.Identity.ValueString()
	if v := plan.ReplyTo.ValueString(); v != "" {
		sp.ReplyTo = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetHVEAccountSettings(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-HVEAccountSettings failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *hVEAccountSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state hVEAccountSettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *hVEAccountSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state hVEAccountSettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetHVEAccountSettingsParams{}
	sp.Identity = id
	if v := plan.ReplyTo.ValueString(); v != "" {
		sp.ReplyTo = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetHVEAccountSettings(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-HVEAccountSettings failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"ReplyTo": cfg.ReplyTo,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *hVEAccountSettingsResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("HVEAccountSettings configuration not deleted", "This resource manages an existing HVEAccountSettings configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *hVEAccountSettingsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *hVEAccountSettingsResource) identityOf(m hVEAccountSettingsModel) any {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *hVEAccountSettingsResource) refresh(ctx context.Context, identity any, m *hVEAccountSettingsModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetHVEAccountSettings(ctx, exo.GetHVEAccountSettingsParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-HVEAccountSettings failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readHVEAccountSettings(ctx, obj, m)
	return true
}

func readHVEAccountSettings(ctx context.Context, obj map[string]any, m *hVEAccountSettingsModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.ReplyTo = types.StringValue(getString(obj, "ReplyTo"))
	_ = ctx
}

func (r *hVEAccountSettingsResource) reconcileState(cfg, read *hVEAccountSettingsModel) {
	read.ReplyTo = reconcile.KeepStr(cfg.ReplyTo, read.ReplyTo)
}
