// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &iRMConfigurationResource{}
	_ resource.ResourceWithConfigure   = &iRMConfigurationResource{}
	_ resource.ResourceWithImportState = &iRMConfigurationResource{}
)

type iRMConfigurationResource struct{ client *clients.Client }

// NewIRMConfigurationResource manages the IRMConfiguration configuration (Get-IRMConfiguration / Set-IRMConfiguration); it adopts the existing object and is not deleted on destroy.
func NewIRMConfigurationResource() resource.Resource { return &iRMConfigurationResource{} }

type iRMConfigurationModel struct {
	ID                                         types.String `tfsdk:"id"`
	Identity                                   types.String `tfsdk:"identity"`
	AutomaticServiceUpdateEnabled              types.Bool   `tfsdk:"automatic_service_update_enabled"`
	AzureRMSLicensingEnabled                   types.Bool   `tfsdk:"azure_rms_licensing_enabled"`
	DecryptAttachmentForEncryptOnly            types.Bool   `tfsdk:"decrypt_attachment_for_encrypt_only"`
	EDiscoverySuperUserEnabled                 types.Bool   `tfsdk:"e_discovery_super_user_enabled"`
	EnablePdfEncryption                        types.Bool   `tfsdk:"enable_pdf_encryption"`
	EnablePortalTrackingLogs                   types.Bool   `tfsdk:"enable_portal_tracking_logs"`
	InternalLicensingEnabled                   types.Bool   `tfsdk:"internal_licensing_enabled"`
	JournalReportDecryptionEnabled             types.Bool   `tfsdk:"journal_report_decryption_enabled"`
	LicensingLocation                          types.String `tfsdk:"licensing_location"`
	RMSOnlineKeySharingLocation                types.String `tfsdk:"rms_online_key_sharing_location"`
	RejectIfRecipientHasNoRights               types.Bool   `tfsdk:"reject_if_recipient_has_no_rights"`
	SearchEnabled                              types.Bool   `tfsdk:"search_enabled"`
	SimplifiedClientAccessDoNotForwardDisabled types.Bool   `tfsdk:"simplified_client_access_do_not_forward_disabled"`
	SimplifiedClientAccessEnabled              types.Bool   `tfsdk:"simplified_client_access_enabled"`
	SimplifiedClientAccessEncryptOnlyDisabled  types.Bool   `tfsdk:"simplified_client_access_encrypt_only_disabled"`
	TransportDecryptionSetting                 types.String `tfsdk:"transport_decryption_setting"`
}

func (r *iRMConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_irm_configuration"
}

func (r *iRMConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the IRMConfiguration configuration via Set-IRMConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                                         schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"automatic_service_update_enabled":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutomaticServiceUpdateEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"azure_rms_licensing_enabled":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AzureRMSLicensingEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"decrypt_attachment_for_encrypt_only":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DecryptAttachmentForEncryptOnly parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"e_discovery_super_user_enabled":                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EDiscoverySuperUserEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_pdf_encryption":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnablePdfEncryption parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_portal_tracking_logs":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnablePortalTrackingLogs parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"internal_licensing_enabled":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -InternalLicensingEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"journal_report_decryption_enabled":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -JournalReportDecryptionEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"licensing_location":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LicensingLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"rms_online_key_sharing_location":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RMSOnlineKeySharingLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"reject_if_recipient_has_no_rights":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RejectIfRecipientHasNoRights parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"search_enabled":                                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SearchEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"simplified_client_access_do_not_forward_disabled": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SimplifiedClientAccessDoNotForwardDisabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"simplified_client_access_enabled":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SimplifiedClientAccessEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"simplified_client_access_encrypt_only_disabled":   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SimplifiedClientAccessEncryptOnlyDisabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"transport_decryption_setting":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TransportDecryptionSetting parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *iRMConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *iRMConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan iRMConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetIRMConfigurationParams{}
	sp.AutomaticServiceUpdateEnabled = plan.AutomaticServiceUpdateEnabled.ValueBool()
	sp.AzureRMSLicensingEnabled = plan.AzureRMSLicensingEnabled.ValueBool()
	sp.DecryptAttachmentForEncryptOnly = plan.DecryptAttachmentForEncryptOnly.ValueBool()
	sp.EDiscoverySuperUserEnabled = plan.EDiscoverySuperUserEnabled.ValueBool()
	sp.EnablePdfEncryption = plan.EnablePdfEncryption.ValueBool()
	sp.EnablePortalTrackingLogs = plan.EnablePortalTrackingLogs.ValueBool()
	sp.InternalLicensingEnabled = plan.InternalLicensingEnabled.ValueBool()
	sp.JournalReportDecryptionEnabled = plan.JournalReportDecryptionEnabled.ValueBool()
	if v := plan.LicensingLocation.ValueString(); v != "" {
		sp.LicensingLocation = v
	}
	if v := plan.RMSOnlineKeySharingLocation.ValueString(); v != "" {
		sp.RMSOnlineKeySharingLocation = v
	}
	sp.RejectIfRecipientHasNoRights = plan.RejectIfRecipientHasNoRights.ValueBool()
	sp.SearchEnabled = plan.SearchEnabled.ValueBool()
	sp.SimplifiedClientAccessDoNotForwardDisabled = plan.SimplifiedClientAccessDoNotForwardDisabled.ValueBool()
	sp.SimplifiedClientAccessEnabled = plan.SimplifiedClientAccessEnabled.ValueBool()
	sp.SimplifiedClientAccessEncryptOnlyDisabled = plan.SimplifiedClientAccessEncryptOnlyDisabled.ValueBool()
	if v := plan.TransportDecryptionSetting.ValueString(); v != "" {
		sp.TransportDecryptionSetting = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetIRMConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-IRMConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := ""
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *iRMConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state iRMConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *iRMConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state iRMConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetIRMConfigurationParams{}
	sp.AutomaticServiceUpdateEnabled = plan.AutomaticServiceUpdateEnabled.ValueBool()
	sp.AzureRMSLicensingEnabled = plan.AzureRMSLicensingEnabled.ValueBool()
	sp.DecryptAttachmentForEncryptOnly = plan.DecryptAttachmentForEncryptOnly.ValueBool()
	sp.EDiscoverySuperUserEnabled = plan.EDiscoverySuperUserEnabled.ValueBool()
	sp.EnablePdfEncryption = plan.EnablePdfEncryption.ValueBool()
	sp.EnablePortalTrackingLogs = plan.EnablePortalTrackingLogs.ValueBool()
	sp.InternalLicensingEnabled = plan.InternalLicensingEnabled.ValueBool()
	sp.JournalReportDecryptionEnabled = plan.JournalReportDecryptionEnabled.ValueBool()
	if v := plan.LicensingLocation.ValueString(); v != "" {
		sp.LicensingLocation = v
	}
	if v := plan.RMSOnlineKeySharingLocation.ValueString(); v != "" {
		sp.RMSOnlineKeySharingLocation = v
	}
	sp.RejectIfRecipientHasNoRights = plan.RejectIfRecipientHasNoRights.ValueBool()
	sp.SearchEnabled = plan.SearchEnabled.ValueBool()
	sp.SimplifiedClientAccessDoNotForwardDisabled = plan.SimplifiedClientAccessDoNotForwardDisabled.ValueBool()
	sp.SimplifiedClientAccessEnabled = plan.SimplifiedClientAccessEnabled.ValueBool()
	sp.SimplifiedClientAccessEncryptOnlyDisabled = plan.SimplifiedClientAccessEncryptOnlyDisabled.ValueBool()
	if v := plan.TransportDecryptionSetting.ValueString(); v != "" {
		sp.TransportDecryptionSetting = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetIRMConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-IRMConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"LicensingLocation":           cfg.LicensingLocation,
		"RMSOnlineKeySharingLocation": cfg.RMSOnlineKeySharingLocation,
		"TransportDecryptionSetting":  cfg.TransportDecryptionSetting,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *iRMConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("IRMConfiguration configuration not deleted", "This resource manages an existing IRMConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *iRMConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *iRMConfigurationResource) identityOf(m iRMConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *iRMConfigurationResource) refresh(ctx context.Context, identity string, m *iRMConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := r.client.EXO.GetIRMConfiguration(ctx, exo.GetIRMConfigurationParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-IRMConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readIRMConfiguration(ctx, obj, m)
	return true
}

func readIRMConfiguration(ctx context.Context, obj map[string]any, m *iRMConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AutomaticServiceUpdateEnabled = types.BoolValue(getBool(obj, "AutomaticServiceUpdateEnabled"))
	m.AzureRMSLicensingEnabled = types.BoolValue(getBool(obj, "AzureRMSLicensingEnabled"))
	m.DecryptAttachmentForEncryptOnly = types.BoolValue(getBool(obj, "DecryptAttachmentForEncryptOnly"))
	m.EDiscoverySuperUserEnabled = types.BoolValue(getBool(obj, "EDiscoverySuperUserEnabled"))
	m.EnablePdfEncryption = types.BoolValue(getBool(obj, "EnablePdfEncryption"))
	m.EnablePortalTrackingLogs = types.BoolValue(getBool(obj, "EnablePortalTrackingLogs"))
	m.InternalLicensingEnabled = types.BoolValue(getBool(obj, "InternalLicensingEnabled"))
	m.JournalReportDecryptionEnabled = types.BoolValue(getBool(obj, "JournalReportDecryptionEnabled"))
	m.LicensingLocation = types.StringValue(getString(obj, "LicensingLocation"))
	m.RMSOnlineKeySharingLocation = types.StringValue(getString(obj, "RMSOnlineKeySharingLocation"))
	m.RejectIfRecipientHasNoRights = types.BoolValue(getBool(obj, "RejectIfRecipientHasNoRights"))
	m.SearchEnabled = types.BoolValue(getBool(obj, "SearchEnabled"))
	m.SimplifiedClientAccessDoNotForwardDisabled = types.BoolValue(getBool(obj, "SimplifiedClientAccessDoNotForwardDisabled"))
	m.SimplifiedClientAccessEnabled = types.BoolValue(getBool(obj, "SimplifiedClientAccessEnabled"))
	m.SimplifiedClientAccessEncryptOnlyDisabled = types.BoolValue(getBool(obj, "SimplifiedClientAccessEncryptOnlyDisabled"))
	m.TransportDecryptionSetting = types.StringValue(getString(obj, "TransportDecryptionSetting"))
	_ = ctx
}

func (r *iRMConfigurationResource) reconcileState(cfg, read *iRMConfigurationModel) {
	read.AutomaticServiceUpdateEnabled = reconcile.KeepBool(cfg.AutomaticServiceUpdateEnabled, read.AutomaticServiceUpdateEnabled)
	read.AzureRMSLicensingEnabled = reconcile.KeepBool(cfg.AzureRMSLicensingEnabled, read.AzureRMSLicensingEnabled)
	read.DecryptAttachmentForEncryptOnly = reconcile.KeepBool(cfg.DecryptAttachmentForEncryptOnly, read.DecryptAttachmentForEncryptOnly)
	read.EDiscoverySuperUserEnabled = reconcile.KeepBool(cfg.EDiscoverySuperUserEnabled, read.EDiscoverySuperUserEnabled)
	read.EnablePdfEncryption = reconcile.KeepBool(cfg.EnablePdfEncryption, read.EnablePdfEncryption)
	read.EnablePortalTrackingLogs = reconcile.KeepBool(cfg.EnablePortalTrackingLogs, read.EnablePortalTrackingLogs)
	read.InternalLicensingEnabled = reconcile.KeepBool(cfg.InternalLicensingEnabled, read.InternalLicensingEnabled)
	read.JournalReportDecryptionEnabled = reconcile.KeepBool(cfg.JournalReportDecryptionEnabled, read.JournalReportDecryptionEnabled)
	read.LicensingLocation = reconcile.KeepStr(cfg.LicensingLocation, read.LicensingLocation)
	read.RMSOnlineKeySharingLocation = reconcile.KeepStr(cfg.RMSOnlineKeySharingLocation, read.RMSOnlineKeySharingLocation)
	read.RejectIfRecipientHasNoRights = reconcile.KeepBool(cfg.RejectIfRecipientHasNoRights, read.RejectIfRecipientHasNoRights)
	read.SearchEnabled = reconcile.KeepBool(cfg.SearchEnabled, read.SearchEnabled)
	read.SimplifiedClientAccessDoNotForwardDisabled = reconcile.KeepBool(cfg.SimplifiedClientAccessDoNotForwardDisabled, read.SimplifiedClientAccessDoNotForwardDisabled)
	read.SimplifiedClientAccessEnabled = reconcile.KeepBool(cfg.SimplifiedClientAccessEnabled, read.SimplifiedClientAccessEnabled)
	read.SimplifiedClientAccessEncryptOnlyDisabled = reconcile.KeepBool(cfg.SimplifiedClientAccessEncryptOnlyDisabled, read.SimplifiedClientAccessEncryptOnlyDisabled)
	read.TransportDecryptionSetting = reconcile.KeepStr(cfg.TransportDecryptionSetting, read.TransportDecryptionSetting)
}
