// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &mailContactResource{}
	_ resource.ResourceWithConfigure   = &mailContactResource{}
	_ resource.ResourceWithImportState = &mailContactResource{}
)

type mailContactResource struct{ client *clients.Client }

// NewMailContactResource manages the MailContact object (New-MailContact / Get-MailContact / Set-MailContact / Remove-MailContact).
func NewMailContactResource() resource.Resource { return &mailContactResource{} }

type mailContactModel struct {
	ID                                     types.String `tfsdk:"id"`
	Identity                               types.String `tfsdk:"identity"`
	AcceptMessagesOnlyFrom                 types.Set    `tfsdk:"accept_messages_only_from"`
	AcceptMessagesOnlyFromDLMembers        types.Set    `tfsdk:"accept_messages_only_from_dl_members"`
	AcceptMessagesOnlyFromSendersOrMembers types.Set    `tfsdk:"accept_messages_only_from_senders_or_members"`
	Alias                                  types.String `tfsdk:"alias_"`
	BypassModerationFromSendersOrMembers   types.Set    `tfsdk:"bypass_moderation_from_senders_or_members"`
	CustomAttribute1                       types.String `tfsdk:"custom_attribute1"`
	CustomAttribute10                      types.String `tfsdk:"custom_attribute10"`
	CustomAttribute11                      types.String `tfsdk:"custom_attribute11"`
	CustomAttribute12                      types.String `tfsdk:"custom_attribute12"`
	CustomAttribute13                      types.String `tfsdk:"custom_attribute13"`
	CustomAttribute14                      types.String `tfsdk:"custom_attribute14"`
	CustomAttribute15                      types.String `tfsdk:"custom_attribute15"`
	CustomAttribute2                       types.String `tfsdk:"custom_attribute2"`
	CustomAttribute3                       types.String `tfsdk:"custom_attribute3"`
	CustomAttribute4                       types.String `tfsdk:"custom_attribute4"`
	CustomAttribute5                       types.String `tfsdk:"custom_attribute5"`
	CustomAttribute6                       types.String `tfsdk:"custom_attribute6"`
	CustomAttribute7                       types.String `tfsdk:"custom_attribute7"`
	CustomAttribute8                       types.String `tfsdk:"custom_attribute8"`
	CustomAttribute9                       types.String `tfsdk:"custom_attribute9"`
	DisplayName                            types.String `tfsdk:"display_name"`
	EmailAddresses                         types.Set    `tfsdk:"email_addresses"`
	ExtensionCustomAttribute1              types.Set    `tfsdk:"extension_custom_attribute1"`
	ExtensionCustomAttribute2              types.Set    `tfsdk:"extension_custom_attribute2"`
	ExtensionCustomAttribute3              types.Set    `tfsdk:"extension_custom_attribute3"`
	ExtensionCustomAttribute4              types.Set    `tfsdk:"extension_custom_attribute4"`
	ExtensionCustomAttribute5              types.Set    `tfsdk:"extension_custom_attribute5"`
	ExternalEmailAddress                   types.String `tfsdk:"external_email_address"`
	FirstName                              types.String `tfsdk:"first_name"`
	ForceUpgrade                           types.Bool   `tfsdk:"force_upgrade"`
	GrantSendOnBehalfTo                    types.Set    `tfsdk:"grant_send_on_behalf_to"`
	HiddenFromAddressListsEnabled          types.Bool   `tfsdk:"hidden_from_address_lists_enabled"`
	Initials                               types.String `tfsdk:"initials"`
	LastName                               types.String `tfsdk:"last_name"`
	MacAttachmentFormat                    types.String `tfsdk:"mac_attachment_format"`
	MailTip                                types.String `tfsdk:"mail_tip"`
	MailTipTranslations                    types.Set    `tfsdk:"mail_tip_translations"`
	MessageBodyFormat                      types.String `tfsdk:"message_body_format"`
	MessageFormat                          types.String `tfsdk:"message_format"`
	ModeratedBy                            types.Set    `tfsdk:"moderated_by"`
	ModerationEnabled                      types.Bool   `tfsdk:"moderation_enabled"`
	Name                                   types.String `tfsdk:"name"`
	OrganizationalUnit                     types.String `tfsdk:"organizational_unit"`
	RejectMessagesFrom                     types.Set    `tfsdk:"reject_messages_from"`
	RejectMessagesFromDLMembers            types.Set    `tfsdk:"reject_messages_from_dl_members"`
	RejectMessagesFromSendersOrMembers     types.Set    `tfsdk:"reject_messages_from_senders_or_members"`
	RequireSenderAuthenticationEnabled     types.Bool   `tfsdk:"require_sender_authentication_enabled"`
	SendModerationNotifications            types.String `tfsdk:"send_moderation_notifications"`
	SimpleDisplayName                      types.String `tfsdk:"simple_display_name"`
	UseMapiRichTextFormat                  types.String `tfsdk:"use_mapi_rich_text_format"`
	UsePreferMessageFormat                 types.Bool   `tfsdk:"use_prefer_message_format"`
	UserCertificate                        types.Set    `tfsdk:"user_certificate"`
	UserSMimeCertificate                   types.Set    `tfsdk:"user_s_mime_certificate"`
	WindowsEmailAddress                    types.String `tfsdk:"windows_email_address"`
}

func (r *mailContactResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mail_contact"
}

func (r *mailContactResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MailContact object via New-MailContact / Get-MailContact / Set-MailContact / Remove-MailContact.",
		Attributes: map[string]schema.Attribute{
			"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                             schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"accept_messages_only_from":            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AcceptMessagesOnlyFrom parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"accept_messages_only_from_dl_members": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromDLMembers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"accept_messages_only_from_senders_or_members": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromSendersOrMembers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"alias_": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Alias parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"bypass_moderation_from_senders_or_members": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -BypassModerationFromSendersOrMembers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"custom_attribute1":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute1 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute10":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute10 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute11":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute11 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute12":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute12 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute13":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute13 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute14":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute14 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute15":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute15 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute2":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute2 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute3":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute3 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute4":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute4 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute5":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute5 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute6":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute6 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute7":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute7 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute8":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute8 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_attribute9":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomAttribute9 parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"display_name":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"email_addresses":                           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -EmailAddresses parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"extension_custom_attribute1":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExtensionCustomAttribute1 parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"extension_custom_attribute2":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExtensionCustomAttribute2 parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"extension_custom_attribute3":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExtensionCustomAttribute3 parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"extension_custom_attribute4":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExtensionCustomAttribute4 parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"extension_custom_attribute5":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExtensionCustomAttribute5 parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"external_email_address":                    schema.StringAttribute{Required: true, Description: "Maps to the -ExternalEmailAddress parameter."},
			"first_name":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -FirstName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"force_upgrade":                             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ForceUpgrade parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"grant_send_on_behalf_to":                   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -GrantSendOnBehalfTo parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"hidden_from_address_lists_enabled":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -HiddenFromAddressListsEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"initials":                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Initials parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"last_name":                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LastName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"mac_attachment_format":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MacAttachmentFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"mail_tip":                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MailTip parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"mail_tip_translations":                     schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -MailTipTranslations parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"message_body_format":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MessageBodyFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"message_format":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MessageFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"moderated_by":                              schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ModeratedBy parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"moderation_enabled":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ModerationEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":                                      schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"organizational_unit":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -OrganizationalUnit parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"reject_messages_from":                      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RejectMessagesFrom parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"reject_messages_from_dl_members":           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RejectMessagesFromDLMembers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"reject_messages_from_senders_or_members":   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RejectMessagesFromSendersOrMembers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"require_sender_authentication_enabled":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RequireSenderAuthenticationEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"send_moderation_notifications":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SendModerationNotifications parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"simple_display_name":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SimpleDisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"use_mapi_rich_text_format":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -UseMapiRichTextFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"use_prefer_message_format":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UsePreferMessageFormat parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"user_certificate":                          schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -UserCertificate parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"user_s_mime_certificate":                   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -UserSMimeCertificate parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"windows_email_address":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -WindowsEmailAddress parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *mailContactResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *mailContactResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mailContactModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config mailContactModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewMailContactParams{}
	if !config.Alias.IsNull() {
		p.Alias = plan.Alias.ValueString()
	}
	if !config.DisplayName.IsNull() {
		p.DisplayName = plan.DisplayName.ValueString()
	}
	if v := config.ExternalEmailAddress.ValueString(); v != "" {
		p.ExternalEmailAddress = objectParam(v)
	}
	if !config.FirstName.IsNull() {
		p.FirstName = plan.FirstName.ValueString()
	}
	if !config.Initials.IsNull() {
		p.Initials = plan.Initials.ValueString()
	}
	if !config.LastName.IsNull() {
		p.LastName = plan.LastName.ValueString()
	}
	if v := config.MacAttachmentFormat.ValueString(); v != "" {
		p.MacAttachmentFormat = objectParam(v)
	}
	if v := config.MessageBodyFormat.ValueString(); v != "" {
		p.MessageBodyFormat = objectParam(v)
	}
	if v := config.MessageFormat.ValueString(); v != "" {
		p.MessageFormat = objectParam(v)
	}
	if !config.ModeratedBy.IsNull() {
		if v := toStringSlice(ctx, plan.ModeratedBy, &resp.Diagnostics); len(v) > 0 {
			p.ModeratedBy = v
		}
	}
	if !config.ModerationEnabled.IsNull() {
		if !plan.ModerationEnabled.IsUnknown() {
			p.ModerationEnabled = plan.ModerationEnabled.ValueBoolPointer()
		}
	}
	if !config.Name.IsNull() {
		p.Name = plan.Name.ValueString()
	}
	if v := config.OrganizationalUnit.ValueString(); v != "" {
		p.OrganizationalUnit = objectParam(v)
	}
	if v := config.SendModerationNotifications.ValueString(); v != "" {
		p.SendModerationNotifications = objectParam(v)
	}
	if !config.UsePreferMessageFormat.IsNull() {
		if !plan.UsePreferMessageFormat.IsUnknown() {
			p.UsePreferMessageFormat = plan.UsePreferMessageFormat.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.NewMailContact, p, isNotFound)
	if err != nil {
		resp.Diagnostics.AddError("New-MailContact failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MailContact returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMailContact(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailContactResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mailContactModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mailContactResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mailContactModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetMailContactParams{}
	sp.Identity = id
	var cur *mailContactModel
	curRead := false
	current := func() *mailContactModel {
		if !curRead {
			curRead = true
			var m mailContactModel
			if r.refresh(ctx, id, &m, &resp.Diagnostics, nil) {
				cur = &m
			} else if !resp.Diagnostics.HasError() {
				resp.Diagnostics.AddError("Get-MailContact failed", "the object could not be read to determine the list values to remove; nothing was changed")
			}
		}
		return cur
	}
	if !plan.AcceptMessagesOnlyFrom.Equal(state.AcceptMessagesOnlyFrom) {
		if !plan.AcceptMessagesOnlyFrom.IsNull() && !plan.AcceptMessagesOnlyFrom.IsUnknown() {
			if v := toStringSlice(ctx, plan.AcceptMessagesOnlyFrom, &resp.Diagnostics); len(v) > 0 {
				sp.AcceptMessagesOnlyFrom = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.AcceptMessagesOnlyFrom, &resp.Diagnostics); len(rm) > 0 {
						sp.AcceptMessagesOnlyFromDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.AcceptMessagesOnlyFromDLMembers.Equal(state.AcceptMessagesOnlyFromDLMembers) {
		if !plan.AcceptMessagesOnlyFromDLMembers.IsNull() && !plan.AcceptMessagesOnlyFromDLMembers.IsUnknown() {
			if v := toStringSlice(ctx, plan.AcceptMessagesOnlyFromDLMembers, &resp.Diagnostics); len(v) > 0 {
				sp.AcceptMessagesOnlyFromDLMembers = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.AcceptMessagesOnlyFromDLMembers, &resp.Diagnostics); len(rm) > 0 {
						sp.AcceptMessagesOnlyFromDLMembersDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.AcceptMessagesOnlyFromSendersOrMembers.Equal(state.AcceptMessagesOnlyFromSendersOrMembers) {
		if !plan.AcceptMessagesOnlyFromSendersOrMembers.IsNull() && !plan.AcceptMessagesOnlyFromSendersOrMembers.IsUnknown() {
			if v := toStringSlice(ctx, plan.AcceptMessagesOnlyFromSendersOrMembers, &resp.Diagnostics); len(v) > 0 {
				sp.AcceptMessagesOnlyFromSendersOrMembers = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.AcceptMessagesOnlyFromSendersOrMembers, &resp.Diagnostics); len(rm) > 0 {
						sp.AcceptMessagesOnlyFromSendersOrMembersDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.Alias.Equal(state.Alias) {
		sp.Alias = plan.Alias.ValueString()
	}
	if !plan.BypassModerationFromSendersOrMembers.Equal(state.BypassModerationFromSendersOrMembers) {
		if !plan.BypassModerationFromSendersOrMembers.IsNull() && !plan.BypassModerationFromSendersOrMembers.IsUnknown() {
			if v := toStringSlice(ctx, plan.BypassModerationFromSendersOrMembers, &resp.Diagnostics); len(v) > 0 {
				sp.BypassModerationFromSendersOrMembers = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.BypassModerationFromSendersOrMembers, &resp.Diagnostics); len(rm) > 0 {
						sp.BypassModerationFromSendersOrMembersDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.CustomAttribute1.Equal(state.CustomAttribute1) {
		sp.CustomAttribute1 = plan.CustomAttribute1.ValueString()
	}
	if !plan.CustomAttribute10.Equal(state.CustomAttribute10) {
		sp.CustomAttribute10 = plan.CustomAttribute10.ValueString()
	}
	if !plan.CustomAttribute11.Equal(state.CustomAttribute11) {
		sp.CustomAttribute11 = plan.CustomAttribute11.ValueString()
	}
	if !plan.CustomAttribute12.Equal(state.CustomAttribute12) {
		sp.CustomAttribute12 = plan.CustomAttribute12.ValueString()
	}
	if !plan.CustomAttribute13.Equal(state.CustomAttribute13) {
		sp.CustomAttribute13 = plan.CustomAttribute13.ValueString()
	}
	if !plan.CustomAttribute14.Equal(state.CustomAttribute14) {
		sp.CustomAttribute14 = plan.CustomAttribute14.ValueString()
	}
	if !plan.CustomAttribute15.Equal(state.CustomAttribute15) {
		sp.CustomAttribute15 = plan.CustomAttribute15.ValueString()
	}
	if !plan.CustomAttribute2.Equal(state.CustomAttribute2) {
		sp.CustomAttribute2 = plan.CustomAttribute2.ValueString()
	}
	if !plan.CustomAttribute3.Equal(state.CustomAttribute3) {
		sp.CustomAttribute3 = plan.CustomAttribute3.ValueString()
	}
	if !plan.CustomAttribute4.Equal(state.CustomAttribute4) {
		sp.CustomAttribute4 = plan.CustomAttribute4.ValueString()
	}
	if !plan.CustomAttribute5.Equal(state.CustomAttribute5) {
		sp.CustomAttribute5 = plan.CustomAttribute5.ValueString()
	}
	if !plan.CustomAttribute6.Equal(state.CustomAttribute6) {
		sp.CustomAttribute6 = plan.CustomAttribute6.ValueString()
	}
	if !plan.CustomAttribute7.Equal(state.CustomAttribute7) {
		sp.CustomAttribute7 = plan.CustomAttribute7.ValueString()
	}
	if !plan.CustomAttribute8.Equal(state.CustomAttribute8) {
		sp.CustomAttribute8 = plan.CustomAttribute8.ValueString()
	}
	if !plan.CustomAttribute9.Equal(state.CustomAttribute9) {
		sp.CustomAttribute9 = plan.CustomAttribute9.ValueString()
	}
	if !plan.DisplayName.Equal(state.DisplayName) {
		sp.DisplayName = plan.DisplayName.ValueString()
	}
	if !plan.EmailAddresses.Equal(state.EmailAddresses) {
		if !plan.EmailAddresses.IsNull() && !plan.EmailAddresses.IsUnknown() {
			sp.EmailAddresses = append([]string{}, toStringSlice(ctx, plan.EmailAddresses, &resp.Diagnostics)...)
		}
	}
	if !plan.ExtensionCustomAttribute1.Equal(state.ExtensionCustomAttribute1) {
		if !plan.ExtensionCustomAttribute1.IsNull() && !plan.ExtensionCustomAttribute1.IsUnknown() {
			if v := toStringSlice(ctx, plan.ExtensionCustomAttribute1, &resp.Diagnostics); len(v) > 0 {
				sp.ExtensionCustomAttribute1 = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ExtensionCustomAttribute1, &resp.Diagnostics); len(rm) > 0 {
						sp.ExtensionCustomAttribute1Delta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ExtensionCustomAttribute2.Equal(state.ExtensionCustomAttribute2) {
		if !plan.ExtensionCustomAttribute2.IsNull() && !plan.ExtensionCustomAttribute2.IsUnknown() {
			if v := toStringSlice(ctx, plan.ExtensionCustomAttribute2, &resp.Diagnostics); len(v) > 0 {
				sp.ExtensionCustomAttribute2 = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ExtensionCustomAttribute2, &resp.Diagnostics); len(rm) > 0 {
						sp.ExtensionCustomAttribute2Delta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ExtensionCustomAttribute3.Equal(state.ExtensionCustomAttribute3) {
		if !plan.ExtensionCustomAttribute3.IsNull() && !plan.ExtensionCustomAttribute3.IsUnknown() {
			if v := toStringSlice(ctx, plan.ExtensionCustomAttribute3, &resp.Diagnostics); len(v) > 0 {
				sp.ExtensionCustomAttribute3 = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ExtensionCustomAttribute3, &resp.Diagnostics); len(rm) > 0 {
						sp.ExtensionCustomAttribute3Delta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ExtensionCustomAttribute4.Equal(state.ExtensionCustomAttribute4) {
		if !plan.ExtensionCustomAttribute4.IsNull() && !plan.ExtensionCustomAttribute4.IsUnknown() {
			if v := toStringSlice(ctx, plan.ExtensionCustomAttribute4, &resp.Diagnostics); len(v) > 0 {
				sp.ExtensionCustomAttribute4 = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ExtensionCustomAttribute4, &resp.Diagnostics); len(rm) > 0 {
						sp.ExtensionCustomAttribute4Delta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ExtensionCustomAttribute5.Equal(state.ExtensionCustomAttribute5) {
		if !plan.ExtensionCustomAttribute5.IsNull() && !plan.ExtensionCustomAttribute5.IsUnknown() {
			if v := toStringSlice(ctx, plan.ExtensionCustomAttribute5, &resp.Diagnostics); len(v) > 0 {
				sp.ExtensionCustomAttribute5 = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ExtensionCustomAttribute5, &resp.Diagnostics); len(rm) > 0 {
						sp.ExtensionCustomAttribute5Delta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ExternalEmailAddress.Equal(state.ExternalEmailAddress) {
		if v := plan.ExternalEmailAddress.ValueString(); v != "" {
			sp.ExternalEmailAddress = objectParam(v)
		}
	}
	if !plan.ForceUpgrade.Equal(state.ForceUpgrade) {
		sp.ForceUpgrade = plan.ForceUpgrade.ValueBool()
	}
	if !plan.GrantSendOnBehalfTo.Equal(state.GrantSendOnBehalfTo) {
		if !plan.GrantSendOnBehalfTo.IsNull() && !plan.GrantSendOnBehalfTo.IsUnknown() {
			if v := toStringSlice(ctx, plan.GrantSendOnBehalfTo, &resp.Diagnostics); len(v) > 0 {
				sp.GrantSendOnBehalfTo = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.GrantSendOnBehalfTo, &resp.Diagnostics); len(rm) > 0 {
						sp.GrantSendOnBehalfToDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.HiddenFromAddressListsEnabled.Equal(state.HiddenFromAddressListsEnabled) {
		if !plan.HiddenFromAddressListsEnabled.IsUnknown() {
			sp.HiddenFromAddressListsEnabled = plan.HiddenFromAddressListsEnabled.ValueBoolPointer()
		}
	}
	if !plan.MacAttachmentFormat.Equal(state.MacAttachmentFormat) {
		if v := plan.MacAttachmentFormat.ValueString(); v != "" {
			sp.MacAttachmentFormat = objectParam(v)
		}
	}
	if !plan.MailTip.Equal(state.MailTip) {
		sp.MailTip = plan.MailTip.ValueString()
	}
	if !plan.MailTipTranslations.Equal(state.MailTipTranslations) {
		if !plan.MailTipTranslations.IsNull() && !plan.MailTipTranslations.IsUnknown() {
			if v := toStringSlice(ctx, plan.MailTipTranslations, &resp.Diagnostics); len(v) > 0 {
				sp.MailTipTranslations = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.MailTipTranslations, &resp.Diagnostics); len(rm) > 0 {
						sp.MailTipTranslationsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.MessageBodyFormat.Equal(state.MessageBodyFormat) {
		if v := plan.MessageBodyFormat.ValueString(); v != "" {
			sp.MessageBodyFormat = objectParam(v)
		}
	}
	if !plan.MessageFormat.Equal(state.MessageFormat) {
		if v := plan.MessageFormat.ValueString(); v != "" {
			sp.MessageFormat = objectParam(v)
		}
	}
	if !plan.ModeratedBy.Equal(state.ModeratedBy) {
		if !plan.ModeratedBy.IsNull() && !plan.ModeratedBy.IsUnknown() {
			if v := toStringSlice(ctx, plan.ModeratedBy, &resp.Diagnostics); len(v) > 0 {
				sp.ModeratedBy = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.ModeratedBy, &resp.Diagnostics); len(rm) > 0 {
						sp.ModeratedByDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.ModerationEnabled.Equal(state.ModerationEnabled) {
		if !plan.ModerationEnabled.IsUnknown() {
			sp.ModerationEnabled = plan.ModerationEnabled.ValueBoolPointer()
		}
	}
	if !plan.RejectMessagesFrom.Equal(state.RejectMessagesFrom) {
		if !plan.RejectMessagesFrom.IsNull() && !plan.RejectMessagesFrom.IsUnknown() {
			if v := toStringSlice(ctx, plan.RejectMessagesFrom, &resp.Diagnostics); len(v) > 0 {
				sp.RejectMessagesFrom = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.RejectMessagesFrom, &resp.Diagnostics); len(rm) > 0 {
						sp.RejectMessagesFromDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.RejectMessagesFromDLMembers.Equal(state.RejectMessagesFromDLMembers) {
		if !plan.RejectMessagesFromDLMembers.IsNull() && !plan.RejectMessagesFromDLMembers.IsUnknown() {
			if v := toStringSlice(ctx, plan.RejectMessagesFromDLMembers, &resp.Diagnostics); len(v) > 0 {
				sp.RejectMessagesFromDLMembers = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.RejectMessagesFromDLMembers, &resp.Diagnostics); len(rm) > 0 {
						sp.RejectMessagesFromDLMembersDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.RejectMessagesFromSendersOrMembers.Equal(state.RejectMessagesFromSendersOrMembers) {
		if !plan.RejectMessagesFromSendersOrMembers.IsNull() && !plan.RejectMessagesFromSendersOrMembers.IsUnknown() {
			if v := toStringSlice(ctx, plan.RejectMessagesFromSendersOrMembers, &resp.Diagnostics); len(v) > 0 {
				sp.RejectMessagesFromSendersOrMembers = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.RejectMessagesFromSendersOrMembers, &resp.Diagnostics); len(rm) > 0 {
						sp.RejectMessagesFromSendersOrMembersDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.RequireSenderAuthenticationEnabled.Equal(state.RequireSenderAuthenticationEnabled) {
		if !plan.RequireSenderAuthenticationEnabled.IsUnknown() {
			sp.RequireSenderAuthenticationEnabled = plan.RequireSenderAuthenticationEnabled.ValueBoolPointer()
		}
	}
	if !plan.SendModerationNotifications.Equal(state.SendModerationNotifications) {
		if v := plan.SendModerationNotifications.ValueString(); v != "" {
			sp.SendModerationNotifications = objectParam(v)
		}
	}
	if !plan.SimpleDisplayName.Equal(state.SimpleDisplayName) {
		sp.SimpleDisplayName = plan.SimpleDisplayName.ValueString()
	}
	if !plan.UseMapiRichTextFormat.Equal(state.UseMapiRichTextFormat) {
		if v := plan.UseMapiRichTextFormat.ValueString(); v != "" {
			sp.UseMapiRichTextFormat = objectParam(v)
		}
	}
	if !plan.UsePreferMessageFormat.Equal(state.UsePreferMessageFormat) {
		if !plan.UsePreferMessageFormat.IsUnknown() {
			sp.UsePreferMessageFormat = plan.UsePreferMessageFormat.ValueBoolPointer()
		}
	}
	if !plan.UserCertificate.Equal(state.UserCertificate) {
		if !plan.UserCertificate.IsNull() && !plan.UserCertificate.IsUnknown() {
			if v := toStringSlice(ctx, plan.UserCertificate, &resp.Diagnostics); len(v) > 0 {
				sp.UserCertificate = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.UserCertificate, &resp.Diagnostics); len(rm) > 0 {
						sp.UserCertificateDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.UserSMimeCertificate.Equal(state.UserSMimeCertificate) {
		if !plan.UserSMimeCertificate.IsNull() && !plan.UserSMimeCertificate.IsUnknown() {
			if v := toStringSlice(ctx, plan.UserSMimeCertificate, &resp.Diagnostics); len(v) > 0 {
				sp.UserSMimeCertificate = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.UserSMimeCertificate, &resp.Diagnostics); len(rm) > 0 {
						sp.UserSMimeCertificateDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.WindowsEmailAddress.Equal(state.WindowsEmailAddress) {
		if v := plan.WindowsEmailAddress.ValueString(); v != "" {
			sp.WindowsEmailAddress = objectParam(v)
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := resourcex.RetryWriteCall(ctx, consistency.Config{}, r.client.EXO.SetMailContact, sp, isNotFound); err != nil {
		resp.Diagnostics.AddError("Set-MailContact failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Alias":             cfg.Alias,
		"CustomAttribute1":  cfg.CustomAttribute1,
		"CustomAttribute10": cfg.CustomAttribute10,
		"CustomAttribute11": cfg.CustomAttribute11,
		"CustomAttribute12": cfg.CustomAttribute12,
		"CustomAttribute13": cfg.CustomAttribute13,
		"CustomAttribute14": cfg.CustomAttribute14,
		"CustomAttribute15": cfg.CustomAttribute15,
		"CustomAttribute2":  cfg.CustomAttribute2,
		"CustomAttribute3":  cfg.CustomAttribute3,
		"CustomAttribute4":  cfg.CustomAttribute4,
		"CustomAttribute5":  cfg.CustomAttribute5,
		"CustomAttribute6":  cfg.CustomAttribute6,
		"CustomAttribute7":  cfg.CustomAttribute7,
		"CustomAttribute8":  cfg.CustomAttribute8,
		"CustomAttribute9":  cfg.CustomAttribute9,
		"DisplayName":       cfg.DisplayName,
		"MailTip":           cfg.MailTip,
		"SimpleDisplayName": cfg.SimpleDisplayName,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailContactResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mailContactModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveMailContact(ctx, exo.RemoveMailContactParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MailContact failed", err.Error())
		}
	}
}

func (r *mailContactResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *mailContactResource) identityOf(m mailContactModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *mailContactResource) refresh(ctx context.Context, identity string, m *mailContactModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetMailContact(ctx, exo.GetMailContactParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MailContact failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMailContact(ctx, obj, m)
	return true
}

func readMailContact(ctx context.Context, obj map[string]any, m *mailContactModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AcceptMessagesOnlyFrom = stringSetValue(ctx, getStringSlice(obj, "AcceptMessagesOnlyFrom"))
	m.AcceptMessagesOnlyFromDLMembers = stringSetValue(ctx, getStringSlice(obj, "AcceptMessagesOnlyFromDLMembers"))
	m.AcceptMessagesOnlyFromSendersOrMembers = stringSetValue(ctx, getStringSlice(obj, "AcceptMessagesOnlyFromSendersOrMembers"))
	m.Alias = types.StringValue(getString(obj, "Alias"))
	m.BypassModerationFromSendersOrMembers = stringSetValue(ctx, getStringSlice(obj, "BypassModerationFromSendersOrMembers"))
	m.CustomAttribute1 = types.StringValue(getString(obj, "CustomAttribute1"))
	m.CustomAttribute10 = types.StringValue(getString(obj, "CustomAttribute10"))
	m.CustomAttribute11 = types.StringValue(getString(obj, "CustomAttribute11"))
	m.CustomAttribute12 = types.StringValue(getString(obj, "CustomAttribute12"))
	m.CustomAttribute13 = types.StringValue(getString(obj, "CustomAttribute13"))
	m.CustomAttribute14 = types.StringValue(getString(obj, "CustomAttribute14"))
	m.CustomAttribute15 = types.StringValue(getString(obj, "CustomAttribute15"))
	m.CustomAttribute2 = types.StringValue(getString(obj, "CustomAttribute2"))
	m.CustomAttribute3 = types.StringValue(getString(obj, "CustomAttribute3"))
	m.CustomAttribute4 = types.StringValue(getString(obj, "CustomAttribute4"))
	m.CustomAttribute5 = types.StringValue(getString(obj, "CustomAttribute5"))
	m.CustomAttribute6 = types.StringValue(getString(obj, "CustomAttribute6"))
	m.CustomAttribute7 = types.StringValue(getString(obj, "CustomAttribute7"))
	m.CustomAttribute8 = types.StringValue(getString(obj, "CustomAttribute8"))
	m.CustomAttribute9 = types.StringValue(getString(obj, "CustomAttribute9"))
	m.DisplayName = types.StringValue(getString(obj, "DisplayName"))
	m.EmailAddresses = stringSetValue(ctx, getStringSlice(obj, "EmailAddresses"))
	m.ExtensionCustomAttribute1 = stringSetValue(ctx, getStringSlice(obj, "ExtensionCustomAttribute1"))
	m.ExtensionCustomAttribute2 = stringSetValue(ctx, getStringSlice(obj, "ExtensionCustomAttribute2"))
	m.ExtensionCustomAttribute3 = stringSetValue(ctx, getStringSlice(obj, "ExtensionCustomAttribute3"))
	m.ExtensionCustomAttribute4 = stringSetValue(ctx, getStringSlice(obj, "ExtensionCustomAttribute4"))
	m.ExtensionCustomAttribute5 = stringSetValue(ctx, getStringSlice(obj, "ExtensionCustomAttribute5"))
	m.ExternalEmailAddress = types.StringValue(getObjectJSON(obj, "ExternalEmailAddress"))
	m.FirstName = types.StringValue(getString(obj, "FirstName"))
	m.ForceUpgrade = types.BoolValue(getBool(obj, "ForceUpgrade"))
	m.GrantSendOnBehalfTo = stringSetValue(ctx, getStringSlice(obj, "GrantSendOnBehalfTo"))
	m.HiddenFromAddressListsEnabled = types.BoolValue(getBool(obj, "HiddenFromAddressListsEnabled"))
	m.Initials = types.StringValue(getString(obj, "Initials"))
	m.LastName = types.StringValue(getString(obj, "LastName"))
	m.MacAttachmentFormat = types.StringValue(getObjectJSON(obj, "MacAttachmentFormat"))
	m.MailTip = types.StringValue(getString(obj, "MailTip"))
	m.MailTipTranslations = stringSetValue(ctx, getStringSlice(obj, "MailTipTranslations"))
	m.MessageBodyFormat = types.StringValue(getObjectJSON(obj, "MessageBodyFormat"))
	m.MessageFormat = types.StringValue(getObjectJSON(obj, "MessageFormat"))
	m.ModeratedBy = stringSetValue(ctx, getStringSlice(obj, "ModeratedBy"))
	m.ModerationEnabled = types.BoolValue(getBool(obj, "ModerationEnabled"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.OrganizationalUnit = types.StringValue(getObjectJSON(obj, "OrganizationalUnit"))
	m.RejectMessagesFrom = stringSetValue(ctx, getStringSlice(obj, "RejectMessagesFrom"))
	m.RejectMessagesFromDLMembers = stringSetValue(ctx, getStringSlice(obj, "RejectMessagesFromDLMembers"))
	m.RejectMessagesFromSendersOrMembers = stringSetValue(ctx, getStringSlice(obj, "RejectMessagesFromSendersOrMembers"))
	m.RequireSenderAuthenticationEnabled = types.BoolValue(getBool(obj, "RequireSenderAuthenticationEnabled"))
	m.SendModerationNotifications = types.StringValue(getObjectJSON(obj, "SendModerationNotifications"))
	m.SimpleDisplayName = types.StringValue(getString(obj, "SimpleDisplayName"))
	m.UseMapiRichTextFormat = types.StringValue(getObjectJSON(obj, "UseMapiRichTextFormat"))
	m.UsePreferMessageFormat = types.BoolValue(getBool(obj, "UsePreferMessageFormat"))
	m.UserCertificate = stringSetValue(ctx, getStringSlice(obj, "UserCertificate"))
	m.UserSMimeCertificate = stringSetValue(ctx, getStringSlice(obj, "UserSMimeCertificate"))
	m.WindowsEmailAddress = types.StringValue(getObjectJSON(obj, "WindowsEmailAddress"))
	_ = ctx
}

func (r *mailContactResource) reconcileState(cfg, read *mailContactModel) {
	read.AcceptMessagesOnlyFrom = reconcile.KeepSet(cfg.AcceptMessagesOnlyFrom, read.AcceptMessagesOnlyFrom)
	read.AcceptMessagesOnlyFromDLMembers = reconcile.KeepSet(cfg.AcceptMessagesOnlyFromDLMembers, read.AcceptMessagesOnlyFromDLMembers)
	read.AcceptMessagesOnlyFromSendersOrMembers = reconcile.KeepSet(cfg.AcceptMessagesOnlyFromSendersOrMembers, read.AcceptMessagesOnlyFromSendersOrMembers)
	read.Alias = reconcile.KeepStr(cfg.Alias, read.Alias)
	read.BypassModerationFromSendersOrMembers = reconcile.KeepSet(cfg.BypassModerationFromSendersOrMembers, read.BypassModerationFromSendersOrMembers)
	read.CustomAttribute1 = reconcile.KeepStr(cfg.CustomAttribute1, read.CustomAttribute1)
	read.CustomAttribute10 = reconcile.KeepStr(cfg.CustomAttribute10, read.CustomAttribute10)
	read.CustomAttribute11 = reconcile.KeepStr(cfg.CustomAttribute11, read.CustomAttribute11)
	read.CustomAttribute12 = reconcile.KeepStr(cfg.CustomAttribute12, read.CustomAttribute12)
	read.CustomAttribute13 = reconcile.KeepStr(cfg.CustomAttribute13, read.CustomAttribute13)
	read.CustomAttribute14 = reconcile.KeepStr(cfg.CustomAttribute14, read.CustomAttribute14)
	read.CustomAttribute15 = reconcile.KeepStr(cfg.CustomAttribute15, read.CustomAttribute15)
	read.CustomAttribute2 = reconcile.KeepStr(cfg.CustomAttribute2, read.CustomAttribute2)
	read.CustomAttribute3 = reconcile.KeepStr(cfg.CustomAttribute3, read.CustomAttribute3)
	read.CustomAttribute4 = reconcile.KeepStr(cfg.CustomAttribute4, read.CustomAttribute4)
	read.CustomAttribute5 = reconcile.KeepStr(cfg.CustomAttribute5, read.CustomAttribute5)
	read.CustomAttribute6 = reconcile.KeepStr(cfg.CustomAttribute6, read.CustomAttribute6)
	read.CustomAttribute7 = reconcile.KeepStr(cfg.CustomAttribute7, read.CustomAttribute7)
	read.CustomAttribute8 = reconcile.KeepStr(cfg.CustomAttribute8, read.CustomAttribute8)
	read.CustomAttribute9 = reconcile.KeepStr(cfg.CustomAttribute9, read.CustomAttribute9)
	read.DisplayName = reconcile.KeepStr(cfg.DisplayName, read.DisplayName)
	read.EmailAddresses = reconcile.KeepSet(cfg.EmailAddresses, read.EmailAddresses)
	read.ExtensionCustomAttribute1 = reconcile.KeepSet(cfg.ExtensionCustomAttribute1, read.ExtensionCustomAttribute1)
	read.ExtensionCustomAttribute2 = reconcile.KeepSet(cfg.ExtensionCustomAttribute2, read.ExtensionCustomAttribute2)
	read.ExtensionCustomAttribute3 = reconcile.KeepSet(cfg.ExtensionCustomAttribute3, read.ExtensionCustomAttribute3)
	read.ExtensionCustomAttribute4 = reconcile.KeepSet(cfg.ExtensionCustomAttribute4, read.ExtensionCustomAttribute4)
	read.ExtensionCustomAttribute5 = reconcile.KeepSet(cfg.ExtensionCustomAttribute5, read.ExtensionCustomAttribute5)
	read.ExternalEmailAddress = reconcile.KeepStr(cfg.ExternalEmailAddress, read.ExternalEmailAddress)
	read.FirstName = reconcile.KeepStr(cfg.FirstName, read.FirstName)
	read.ForceUpgrade = reconcile.KeepBool(cfg.ForceUpgrade, read.ForceUpgrade)
	read.GrantSendOnBehalfTo = reconcile.KeepSet(cfg.GrantSendOnBehalfTo, read.GrantSendOnBehalfTo)
	read.HiddenFromAddressListsEnabled = reconcile.KeepBool(cfg.HiddenFromAddressListsEnabled, read.HiddenFromAddressListsEnabled)
	read.Initials = reconcile.KeepStr(cfg.Initials, read.Initials)
	read.LastName = reconcile.KeepStr(cfg.LastName, read.LastName)
	read.MacAttachmentFormat = reconcile.KeepStr(cfg.MacAttachmentFormat, read.MacAttachmentFormat)
	read.MailTip = reconcile.KeepStr(cfg.MailTip, read.MailTip)
	read.MailTipTranslations = reconcile.KeepSet(cfg.MailTipTranslations, read.MailTipTranslations)
	read.MessageBodyFormat = reconcile.KeepStr(cfg.MessageBodyFormat, read.MessageBodyFormat)
	read.MessageFormat = reconcile.KeepStr(cfg.MessageFormat, read.MessageFormat)
	read.ModeratedBy = reconcile.KeepSet(cfg.ModeratedBy, read.ModeratedBy)
	read.ModerationEnabled = reconcile.KeepBool(cfg.ModerationEnabled, read.ModerationEnabled)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.OrganizationalUnit = reconcile.KeepStr(cfg.OrganizationalUnit, read.OrganizationalUnit)
	read.RejectMessagesFrom = reconcile.KeepSet(cfg.RejectMessagesFrom, read.RejectMessagesFrom)
	read.RejectMessagesFromDLMembers = reconcile.KeepSet(cfg.RejectMessagesFromDLMembers, read.RejectMessagesFromDLMembers)
	read.RejectMessagesFromSendersOrMembers = reconcile.KeepSet(cfg.RejectMessagesFromSendersOrMembers, read.RejectMessagesFromSendersOrMembers)
	read.RequireSenderAuthenticationEnabled = reconcile.KeepBool(cfg.RequireSenderAuthenticationEnabled, read.RequireSenderAuthenticationEnabled)
	read.SendModerationNotifications = reconcile.KeepStr(cfg.SendModerationNotifications, read.SendModerationNotifications)
	read.SimpleDisplayName = reconcile.KeepStr(cfg.SimpleDisplayName, read.SimpleDisplayName)
	read.UseMapiRichTextFormat = reconcile.KeepStr(cfg.UseMapiRichTextFormat, read.UseMapiRichTextFormat)
	read.UsePreferMessageFormat = reconcile.KeepBool(cfg.UsePreferMessageFormat, read.UsePreferMessageFormat)
	read.UserCertificate = reconcile.KeepSet(cfg.UserCertificate, read.UserCertificate)
	read.UserSMimeCertificate = reconcile.KeepSet(cfg.UserSMimeCertificate, read.UserSMimeCertificate)
	read.WindowsEmailAddress = reconcile.KeepStr(cfg.WindowsEmailAddress, read.WindowsEmailAddress)
}
