// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &mailboxAutoReplyConfigurationResource{}
	_ resource.ResourceWithConfigure   = &mailboxAutoReplyConfigurationResource{}
	_ resource.ResourceWithImportState = &mailboxAutoReplyConfigurationResource{}
)

type mailboxAutoReplyConfigurationResource struct{ client *clients.Client }

// NewMailboxAutoReplyConfigurationResource manages the MailboxAutoReplyConfiguration configuration (Get-MailboxAutoReplyConfiguration / Set-MailboxAutoReplyConfiguration); it adopts the existing object and is not deleted on destroy.
func NewMailboxAutoReplyConfigurationResource() resource.Resource {
	return &mailboxAutoReplyConfigurationResource{}
}

type mailboxAutoReplyConfigurationModel struct {
	ID                               types.String `tfsdk:"id"`
	Identity                         types.String `tfsdk:"identity"`
	AutoDeclineFutureRequestsWhenOOF types.Bool   `tfsdk:"auto_decline_future_requests_when_oof"`
	AutoReplyState                   types.String `tfsdk:"auto_reply_state"`
	CreateOOFEvent                   types.Bool   `tfsdk:"create_oof_event"`
	DeclineAllEventsForScheduledOOF  types.Bool   `tfsdk:"decline_all_events_for_scheduled_oof"`
	DeclineEventsForScheduledOOF     types.Bool   `tfsdk:"decline_events_for_scheduled_oof"`
	DeclineMeetingMessage            types.String `tfsdk:"decline_meeting_message"`
	EndTime                          types.String `tfsdk:"end_time"`
	EventsToDeleteIDs                types.Set    `tfsdk:"events_to_delete_i_ds"`
	ExternalAudience                 types.String `tfsdk:"external_audience"`
	ExternalMessage                  types.String `tfsdk:"external_message"`
	InternalMessage                  types.String `tfsdk:"internal_message"`
	OOFEventSubject                  types.String `tfsdk:"oof_event_subject"`
	StartTime                        types.String `tfsdk:"start_time"`
}

func (r *mailboxAutoReplyConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mailbox_auto_reply_configuration"
}

func (r *mailboxAutoReplyConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MailboxAutoReplyConfiguration configuration via Set-MailboxAutoReplyConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                    schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                              schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"auto_decline_future_requests_when_oof": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoDeclineFutureRequestsWhenOOF parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"auto_reply_state":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoReplyState parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"create_oof_event":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CreateOOFEvent parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"decline_all_events_for_scheduled_oof":  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DeclineAllEventsForScheduledOOF parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"decline_events_for_scheduled_oof":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DeclineEventsForScheduledOOF parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"decline_meeting_message":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DeclineMeetingMessage parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"end_time":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EndTime parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"events_to_delete_i_ds":                 schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -EventsToDeleteIDs parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"external_audience":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExternalAudience parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"external_message":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExternalMessage parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"internal_message":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -InternalMessage parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"oof_event_subject":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -OOFEventSubject parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"start_time":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -StartTime parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *mailboxAutoReplyConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *mailboxAutoReplyConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mailboxAutoReplyConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetMailboxAutoReplyConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	sp.AutoDeclineFutureRequestsWhenOOF = plan.AutoDeclineFutureRequestsWhenOOF.ValueBool()
	if v := plan.AutoReplyState.ValueString(); v != "" {
		sp.AutoReplyState = v
	}
	sp.CreateOOFEvent = plan.CreateOOFEvent.ValueBool()
	sp.DeclineAllEventsForScheduledOOF = plan.DeclineAllEventsForScheduledOOF.ValueBool()
	sp.DeclineEventsForScheduledOOF = plan.DeclineEventsForScheduledOOF.ValueBool()
	sp.DeclineMeetingMessage = plan.DeclineMeetingMessage.ValueString()
	if v := plan.EndTime.ValueString(); v != "" {
		sp.EndTime = v
	}
	sp.EventsToDeleteIDs = toStringSlice(ctx, plan.EventsToDeleteIDs, &resp.Diagnostics)
	if v := plan.ExternalAudience.ValueString(); v != "" {
		sp.ExternalAudience = v
	}
	sp.ExternalMessage = plan.ExternalMessage.ValueString()
	sp.InternalMessage = plan.InternalMessage.ValueString()
	sp.OOFEventSubject = plan.OOFEventSubject.ValueString()
	if v := plan.StartTime.ValueString(); v != "" {
		sp.StartTime = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetMailboxAutoReplyConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MailboxAutoReplyConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailboxAutoReplyConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mailboxAutoReplyConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mailboxAutoReplyConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mailboxAutoReplyConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetMailboxAutoReplyConfigurationParams{}
	sp.Identity = id
	sp.AutoDeclineFutureRequestsWhenOOF = plan.AutoDeclineFutureRequestsWhenOOF.ValueBool()
	if v := plan.AutoReplyState.ValueString(); v != "" {
		sp.AutoReplyState = v
	}
	sp.CreateOOFEvent = plan.CreateOOFEvent.ValueBool()
	sp.DeclineAllEventsForScheduledOOF = plan.DeclineAllEventsForScheduledOOF.ValueBool()
	sp.DeclineEventsForScheduledOOF = plan.DeclineEventsForScheduledOOF.ValueBool()
	sp.DeclineMeetingMessage = plan.DeclineMeetingMessage.ValueString()
	if v := plan.EndTime.ValueString(); v != "" {
		sp.EndTime = v
	}
	sp.EventsToDeleteIDs = toStringSlice(ctx, plan.EventsToDeleteIDs, &resp.Diagnostics)
	if v := plan.ExternalAudience.ValueString(); v != "" {
		sp.ExternalAudience = v
	}
	sp.ExternalMessage = plan.ExternalMessage.ValueString()
	sp.InternalMessage = plan.InternalMessage.ValueString()
	sp.OOFEventSubject = plan.OOFEventSubject.ValueString()
	if v := plan.StartTime.ValueString(); v != "" {
		sp.StartTime = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetMailboxAutoReplyConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MailboxAutoReplyConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AutoReplyState":        cfg.AutoReplyState,
		"DeclineMeetingMessage": cfg.DeclineMeetingMessage,
		"EndTime":               cfg.EndTime,
		"ExternalAudience":      cfg.ExternalAudience,
		"ExternalMessage":       cfg.ExternalMessage,
		"InternalMessage":       cfg.InternalMessage,
		"OOFEventSubject":       cfg.OOFEventSubject,
		"StartTime":             cfg.StartTime,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailboxAutoReplyConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("MailboxAutoReplyConfiguration configuration not deleted", "This resource manages an existing MailboxAutoReplyConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *mailboxAutoReplyConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *mailboxAutoReplyConfigurationResource) identityOf(m mailboxAutoReplyConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *mailboxAutoReplyConfigurationResource) refresh(ctx context.Context, identity string, m *mailboxAutoReplyConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetMailboxAutoReplyConfiguration(ctx, exo.GetMailboxAutoReplyConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MailboxAutoReplyConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMailboxAutoReplyConfiguration(ctx, obj, m)
	return true
}

func readMailboxAutoReplyConfiguration(ctx context.Context, obj map[string]any, m *mailboxAutoReplyConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AutoDeclineFutureRequestsWhenOOF = types.BoolValue(getBool(obj, "AutoDeclineFutureRequestsWhenOOF"))
	m.AutoReplyState = types.StringValue(getString(obj, "AutoReplyState"))
	m.CreateOOFEvent = types.BoolValue(getBool(obj, "CreateOOFEvent"))
	m.DeclineAllEventsForScheduledOOF = types.BoolValue(getBool(obj, "DeclineAllEventsForScheduledOOF"))
	m.DeclineEventsForScheduledOOF = types.BoolValue(getBool(obj, "DeclineEventsForScheduledOOF"))
	m.DeclineMeetingMessage = types.StringValue(getString(obj, "DeclineMeetingMessage"))
	m.EndTime = types.StringValue(getString(obj, "EndTime"))
	m.EventsToDeleteIDs = stringSetValue(ctx, getStringSlice(obj, "EventsToDeleteIDs"))
	m.ExternalAudience = types.StringValue(getString(obj, "ExternalAudience"))
	m.ExternalMessage = types.StringValue(getString(obj, "ExternalMessage"))
	m.InternalMessage = types.StringValue(getString(obj, "InternalMessage"))
	m.OOFEventSubject = types.StringValue(getString(obj, "OOFEventSubject"))
	m.StartTime = types.StringValue(getString(obj, "StartTime"))
	_ = ctx
}

func (r *mailboxAutoReplyConfigurationResource) reconcileState(cfg, read *mailboxAutoReplyConfigurationModel) {
	read.AutoDeclineFutureRequestsWhenOOF = reconcile.KeepBool(cfg.AutoDeclineFutureRequestsWhenOOF, read.AutoDeclineFutureRequestsWhenOOF)
	read.AutoReplyState = reconcile.KeepStr(cfg.AutoReplyState, read.AutoReplyState)
	read.CreateOOFEvent = reconcile.KeepBool(cfg.CreateOOFEvent, read.CreateOOFEvent)
	read.DeclineAllEventsForScheduledOOF = reconcile.KeepBool(cfg.DeclineAllEventsForScheduledOOF, read.DeclineAllEventsForScheduledOOF)
	read.DeclineEventsForScheduledOOF = reconcile.KeepBool(cfg.DeclineEventsForScheduledOOF, read.DeclineEventsForScheduledOOF)
	read.DeclineMeetingMessage = reconcile.KeepStr(cfg.DeclineMeetingMessage, read.DeclineMeetingMessage)
	read.EndTime = reconcile.KeepStr(cfg.EndTime, read.EndTime)
	read.EventsToDeleteIDs = reconcile.KeepSet(cfg.EventsToDeleteIDs, read.EventsToDeleteIDs)
	read.ExternalAudience = reconcile.KeepStr(cfg.ExternalAudience, read.ExternalAudience)
	read.ExternalMessage = reconcile.KeepStr(cfg.ExternalMessage, read.ExternalMessage)
	read.InternalMessage = reconcile.KeepStr(cfg.InternalMessage, read.InternalMessage)
	read.OOFEventSubject = reconcile.KeepStr(cfg.OOFEventSubject, read.OOFEventSubject)
	read.StartTime = reconcile.KeepStr(cfg.StartTime, read.StartTime)
}
