// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &mailboxMessageConfigurationResource{}
	_ resource.ResourceWithConfigure   = &mailboxMessageConfigurationResource{}
	_ resource.ResourceWithImportState = &mailboxMessageConfigurationResource{}
	_ resource.ResourceWithModifyPlan  = &mailboxMessageConfigurationResource{}
)

type mailboxMessageConfigurationResource struct{ client *clients.Client }

// NewMailboxMessageConfigurationResource manages the MailboxMessageConfiguration configuration (Get-MailboxMessageConfiguration / Set-MailboxMessageConfiguration); it adopts the existing object and is not deleted on destroy.
func NewMailboxMessageConfigurationResource() resource.Resource {
	return &mailboxMessageConfigurationResource{}
}

type mailboxMessageConfigurationModel struct {
	ID                                     types.String `tfsdk:"id"`
	Identity                               types.String `tfsdk:"identity"`
	AfterMoveOrDeleteBehavior              types.String `tfsdk:"after_move_or_delete_behavior"`
	AlwaysShowBcc                          types.Bool   `tfsdk:"always_show_bcc"`
	AlwaysShowFrom                         types.Bool   `tfsdk:"always_show_from"`
	AutoAddSignature                       types.Bool   `tfsdk:"auto_add_signature"`
	AutoAddSignatureOnMobile               types.Bool   `tfsdk:"auto_add_signature_on_mobile"`
	AutoAddSignatureOnReply                types.Bool   `tfsdk:"auto_add_signature_on_reply"`
	CheckForForgottenAttachments           types.Bool   `tfsdk:"check_for_forgotten_attachments"`
	CheckForReportJunkDialog               types.Bool   `tfsdk:"check_for_report_junk_dialog"`
	ConversationSortOrder                  types.String `tfsdk:"conversation_sort_order"`
	DefaultFontColor                       types.String `tfsdk:"default_font_color"`
	DefaultFontFlags                       types.String `tfsdk:"default_font_flags"`
	DefaultFontName                        types.String `tfsdk:"default_font_name"`
	DefaultFontSize                        types.Int64  `tfsdk:"default_font_size"`
	DefaultFormat                          types.String `tfsdk:"default_format"`
	DefaultSignature                       types.String `tfsdk:"default_signature"`
	DefaultSignatureOnReply                types.String `tfsdk:"default_signature_on_reply"`
	DeleteSignatureName                    types.String `tfsdk:"delete_signature_name"`
	DisplayDensityMode                     types.String `tfsdk:"display_density_mode"`
	EchoGroupMessageBackToSubscribedSender types.Bool   `tfsdk:"echo_group_message_back_to_subscribed_sender"`
	EmailComposeMode                       types.String `tfsdk:"email_compose_mode"`
	EmptyDeletedItemsOnLogoff              types.Bool   `tfsdk:"empty_deleted_items_on_logoff"`
	FavoritesBitFlags                      types.Int64  `tfsdk:"favorites_bit_flags"`
	GlobalReadingPanePosition              types.String `tfsdk:"global_reading_pane_position"`
	HideDeletedItems                       types.Bool   `tfsdk:"hide_deleted_items"`
	IsDarkModeTheme                        types.Bool   `tfsdk:"is_dark_mode_theme"`
	IsFavoritesFolderTreeCollapsed         types.Bool   `tfsdk:"is_favorites_folder_tree_collapsed"`
	IsFocusedInboxEnabled                  types.Bool   `tfsdk:"is_focused_inbox_enabled"`
	IsMailRootFolderTreeCollapsed          types.Bool   `tfsdk:"is_mail_root_folder_tree_collapsed"`
	IsReplyAllTheDefaultResponse           types.Bool   `tfsdk:"is_reply_all_the_default_response"`
	LinkPreviewEnabled                     types.Bool   `tfsdk:"link_preview_enabled"`
	MailFolderPaneExpanded                 types.Bool   `tfsdk:"mail_folder_pane_expanded"`
	MailSendUndoInterval                   types.Int64  `tfsdk:"mail_send_undo_interval"`
	ManuallyPickCertificate                types.Bool   `tfsdk:"manually_pick_certificate"`
	NavigationBarWidth                     types.Int64  `tfsdk:"navigation_bar_width"`
	NavigationPaneViewOption               types.String `tfsdk:"navigation_pane_view_option"`
	NewEnabledPonts                        types.String `tfsdk:"new_enabled_ponts"`
	NewItemNotification                    types.String `tfsdk:"new_item_notification"`
	PreferAccessibleContent                types.Bool   `tfsdk:"prefer_accessible_content"`
	PreviewMarkAsReadBehavior              types.String `tfsdk:"preview_mark_as_read_behavior"`
	PreviewMarkAsReadDelaytime             types.Int64  `tfsdk:"preview_mark_as_read_delaytime"`
	ReadReceiptResponse                    types.String `tfsdk:"read_receipt_response"`
	ReportJunkSelected                     types.Bool   `tfsdk:"report_junk_selected"`
	SendAddressDefault                     types.String `tfsdk:"send_address_default"`
	ShowConversationAsTree                 types.Bool   `tfsdk:"show_conversation_as_tree"`
	ShowInlinePreviews                     types.Bool   `tfsdk:"show_inline_previews"`
	ShowNotificationBar                    types.Bool   `tfsdk:"show_notification_bar"`
	ShowPreviewTextInListView              types.Bool   `tfsdk:"show_preview_text_in_list_view"`
	ShowReadingPaneOnFirstLoad             types.Bool   `tfsdk:"show_reading_pane_on_first_load"`
	ShowSenderOnTopInListView              types.Bool   `tfsdk:"show_sender_on_top_in_list_view"`
	ShowUpNext                             types.Bool   `tfsdk:"show_up_next"`
	SignatureHtml                          types.String `tfsdk:"signature_html"`
	SignatureHtmlBody                      types.String `tfsdk:"signature_html_body"`
	SignatureName                          types.String `tfsdk:"signature_name"`
	SignatureText                          types.String `tfsdk:"signature_text"`
	SignatureTextOnMobile                  types.String `tfsdk:"signature_text_on_mobile"`
	SigningCertificateId                   types.String `tfsdk:"signing_certificate_id"`
	SigningCertificateSubject              types.String `tfsdk:"signing_certificate_subject"`
	SmimeEncrypt                           types.Bool   `tfsdk:"smime_encrypt"`
	SmimeSign                              types.Bool   `tfsdk:"smime_sign"`
	UseDefaultSignatureOnMobile            types.Bool   `tfsdk:"use_default_signature_on_mobile"`
	WebSuggestedRepliesEnabledForUser      types.Bool   `tfsdk:"web_suggested_replies_enabled_for_user"`
}

func (r *mailboxMessageConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mailbox_message_configuration"
}

func (r *mailboxMessageConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MailboxMessageConfiguration configuration via Set-MailboxMessageConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                                           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                                     schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"after_move_or_delete_behavior":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AfterMoveOrDeleteBehavior parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"always_show_bcc":                              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AlwaysShowBcc parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"always_show_from":                             schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AlwaysShowFrom parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"auto_add_signature":                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoAddSignature parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"auto_add_signature_on_mobile":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoAddSignatureOnMobile parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"auto_add_signature_on_reply":                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AutoAddSignatureOnReply parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"check_for_forgotten_attachments":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CheckForForgottenAttachments parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"check_for_report_junk_dialog":                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CheckForReportJunkDialog parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"conversation_sort_order":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ConversationSortOrder parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_font_color":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFontColor parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_font_flags":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFontFlags parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_font_name":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFontName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_font_size":                            schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFontSize parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"default_format":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultFormat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_signature":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultSignature parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_signature_on_reply":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultSignatureOnReply parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"delete_signature_name":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DeleteSignatureName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"display_density_mode":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DisplayDensityMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"echo_group_message_back_to_subscribed_sender": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EchoGroupMessageBackToSubscribedSender parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"email_compose_mode":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EmailComposeMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"empty_deleted_items_on_logoff":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EmptyDeletedItemsOnLogoff parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"favorites_bit_flags":                          schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -FavoritesBitFlags parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"global_reading_pane_position":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -GlobalReadingPanePosition parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"hide_deleted_items":                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -HideDeletedItems parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_dark_mode_theme":                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsDarkModeTheme parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_favorites_folder_tree_collapsed":           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsFavoritesFolderTreeCollapsed parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_focused_inbox_enabled":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsFocusedInboxEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_mail_root_folder_tree_collapsed":           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsMailRootFolderTreeCollapsed parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_reply_all_the_default_response":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsReplyAllTheDefaultResponse parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"link_preview_enabled":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -LinkPreviewEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mail_folder_pane_expanded":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MailFolderPaneExpanded parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"mail_send_undo_interval":                      schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -MailSendUndoInterval parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"manually_pick_certificate":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ManuallyPickCertificate parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"navigation_bar_width":                         schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -NavigationBarWidth parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"navigation_pane_view_option":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NavigationPaneViewOption parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"new_enabled_ponts":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NewEnabledPonts parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"new_item_notification":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NewItemNotification parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"prefer_accessible_content":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PreferAccessibleContent parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"preview_mark_as_read_behavior":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PreviewMarkAsReadBehavior parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"preview_mark_as_read_delaytime":               schema.Int64Attribute{Optional: true, Computed: true, Description: "Maps to the -PreviewMarkAsReadDelaytime parameter.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"read_receipt_response":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReadReceiptResponse parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"report_junk_selected":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ReportJunkSelected parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"send_address_default":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SendAddressDefault parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"show_conversation_as_tree":                    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowConversationAsTree parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_inline_previews":                         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowInlinePreviews parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_notification_bar":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowNotificationBar parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_preview_text_in_list_view":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowPreviewTextInListView parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_reading_pane_on_first_load":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowReadingPaneOnFirstLoad parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_sender_on_top_in_list_view":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowSenderOnTopInListView parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"show_up_next":                                 schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ShowUpNext parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"signature_html":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SignatureHtml parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signature_html_body":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SignatureHtmlBody parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signature_name":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SignatureName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signature_text":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SignatureText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signature_text_on_mobile":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SignatureTextOnMobile parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signing_certificate_id":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SigningCertificateId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"signing_certificate_subject":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SigningCertificateSubject parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"smime_encrypt":                                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SmimeEncrypt parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"smime_sign":                                   schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SmimeSign parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"use_default_signature_on_mobile":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseDefaultSignatureOnMobile parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"web_suggested_replies_enabled_for_user":       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -WebSuggestedRepliesEnabledForUser parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *mailboxMessageConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *mailboxMessageConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mailboxMessageConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var config mailboxMessageConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetMailboxMessageConfigurationParams{}
	sp.Identity = plan.Identity.ValueString()
	if v := config.AfterMoveOrDeleteBehavior.ValueString(); v != "" {
		sp.AfterMoveOrDeleteBehavior = objectParam(v)
	}
	if !config.AlwaysShowBcc.IsNull() {
		if !plan.AlwaysShowBcc.IsUnknown() {
			sp.AlwaysShowBcc = plan.AlwaysShowBcc.ValueBoolPointer()
		}
	}
	if !config.AlwaysShowFrom.IsNull() {
		if !plan.AlwaysShowFrom.IsUnknown() {
			sp.AlwaysShowFrom = plan.AlwaysShowFrom.ValueBoolPointer()
		}
	}
	if !config.AutoAddSignature.IsNull() {
		if !plan.AutoAddSignature.IsUnknown() {
			sp.AutoAddSignature = plan.AutoAddSignature.ValueBoolPointer()
		}
	}
	if !config.AutoAddSignatureOnMobile.IsNull() {
		if !plan.AutoAddSignatureOnMobile.IsUnknown() {
			sp.AutoAddSignatureOnMobile = plan.AutoAddSignatureOnMobile.ValueBoolPointer()
		}
	}
	if !config.AutoAddSignatureOnReply.IsNull() {
		if !plan.AutoAddSignatureOnReply.IsUnknown() {
			sp.AutoAddSignatureOnReply = plan.AutoAddSignatureOnReply.ValueBoolPointer()
		}
	}
	if !config.CheckForForgottenAttachments.IsNull() {
		if !plan.CheckForForgottenAttachments.IsUnknown() {
			sp.CheckForForgottenAttachments = plan.CheckForForgottenAttachments.ValueBoolPointer()
		}
	}
	if !config.CheckForReportJunkDialog.IsNull() {
		if !plan.CheckForReportJunkDialog.IsUnknown() {
			sp.CheckForReportJunkDialog = plan.CheckForReportJunkDialog.ValueBoolPointer()
		}
	}
	if v := config.ConversationSortOrder.ValueString(); v != "" {
		sp.ConversationSortOrder = objectParam(v)
	}
	if !config.DefaultFontColor.IsNull() {
		sp.DefaultFontColor = plan.DefaultFontColor.ValueString()
	}
	if v := config.DefaultFontFlags.ValueString(); v != "" {
		sp.DefaultFontFlags = objectParam(v)
	}
	if !config.DefaultFontName.IsNull() {
		sp.DefaultFontName = plan.DefaultFontName.ValueString()
	}
	if !config.DefaultFontSize.IsNull() {
		if !plan.DefaultFontSize.IsUnknown() {
			sp.DefaultFontSize = plan.DefaultFontSize.ValueInt64Pointer()
		}
	}
	if v := config.DefaultFormat.ValueString(); v != "" {
		sp.DefaultFormat = objectParam(v)
	}
	if !config.DefaultSignature.IsNull() {
		sp.DefaultSignature = plan.DefaultSignature.ValueString()
	}
	if !config.DefaultSignatureOnReply.IsNull() {
		sp.DefaultSignatureOnReply = plan.DefaultSignatureOnReply.ValueString()
	}
	if !config.DeleteSignatureName.IsNull() {
		sp.DeleteSignatureName = plan.DeleteSignatureName.ValueString()
	}
	if v := config.DisplayDensityMode.ValueString(); v != "" {
		sp.DisplayDensityMode = objectParam(v)
	}
	if !config.EchoGroupMessageBackToSubscribedSender.IsNull() {
		if !plan.EchoGroupMessageBackToSubscribedSender.IsUnknown() {
			sp.EchoGroupMessageBackToSubscribedSender = plan.EchoGroupMessageBackToSubscribedSender.ValueBoolPointer()
		}
	}
	if v := config.EmailComposeMode.ValueString(); v != "" {
		sp.EmailComposeMode = objectParam(v)
	}
	if !config.EmptyDeletedItemsOnLogoff.IsNull() {
		if !plan.EmptyDeletedItemsOnLogoff.IsUnknown() {
			sp.EmptyDeletedItemsOnLogoff = plan.EmptyDeletedItemsOnLogoff.ValueBoolPointer()
		}
	}
	if !config.FavoritesBitFlags.IsNull() {
		if !plan.FavoritesBitFlags.IsUnknown() {
			sp.FavoritesBitFlags = plan.FavoritesBitFlags.ValueInt64Pointer()
		}
	}
	if v := config.GlobalReadingPanePosition.ValueString(); v != "" {
		sp.GlobalReadingPanePosition = objectParam(v)
	}
	if !config.HideDeletedItems.IsNull() {
		if !plan.HideDeletedItems.IsUnknown() {
			sp.HideDeletedItems = plan.HideDeletedItems.ValueBoolPointer()
		}
	}
	if !config.IsDarkModeTheme.IsNull() {
		if !plan.IsDarkModeTheme.IsUnknown() {
			sp.IsDarkModeTheme = plan.IsDarkModeTheme.ValueBoolPointer()
		}
	}
	if !config.IsFavoritesFolderTreeCollapsed.IsNull() {
		if !plan.IsFavoritesFolderTreeCollapsed.IsUnknown() {
			sp.IsFavoritesFolderTreeCollapsed = plan.IsFavoritesFolderTreeCollapsed.ValueBoolPointer()
		}
	}
	if !config.IsFocusedInboxEnabled.IsNull() {
		if !plan.IsFocusedInboxEnabled.IsUnknown() {
			sp.IsFocusedInboxEnabled = plan.IsFocusedInboxEnabled.ValueBoolPointer()
		}
	}
	if !config.IsMailRootFolderTreeCollapsed.IsNull() {
		if !plan.IsMailRootFolderTreeCollapsed.IsUnknown() {
			sp.IsMailRootFolderTreeCollapsed = plan.IsMailRootFolderTreeCollapsed.ValueBoolPointer()
		}
	}
	if !config.IsReplyAllTheDefaultResponse.IsNull() {
		if !plan.IsReplyAllTheDefaultResponse.IsUnknown() {
			sp.IsReplyAllTheDefaultResponse = plan.IsReplyAllTheDefaultResponse.ValueBoolPointer()
		}
	}
	if !config.LinkPreviewEnabled.IsNull() {
		if !plan.LinkPreviewEnabled.IsUnknown() {
			sp.LinkPreviewEnabled = plan.LinkPreviewEnabled.ValueBoolPointer()
		}
	}
	if !config.MailFolderPaneExpanded.IsNull() {
		if !plan.MailFolderPaneExpanded.IsUnknown() {
			sp.MailFolderPaneExpanded = plan.MailFolderPaneExpanded.ValueBoolPointer()
		}
	}
	if !config.MailSendUndoInterval.IsNull() {
		if !plan.MailSendUndoInterval.IsUnknown() {
			sp.MailSendUndoInterval = plan.MailSendUndoInterval.ValueInt64Pointer()
		}
	}
	if !config.ManuallyPickCertificate.IsNull() {
		if !plan.ManuallyPickCertificate.IsUnknown() {
			sp.ManuallyPickCertificate = plan.ManuallyPickCertificate.ValueBoolPointer()
		}
	}
	if !config.NavigationBarWidth.IsNull() {
		if !plan.NavigationBarWidth.IsUnknown() {
			sp.NavigationBarWidth = plan.NavigationBarWidth.ValueInt64Pointer()
		}
	}
	if v := config.NavigationPaneViewOption.ValueString(); v != "" {
		sp.NavigationPaneViewOption = objectParam(v)
	}
	if v := config.NewEnabledPonts.ValueString(); v != "" {
		sp.NewEnabledPonts = objectParam(v)
	}
	if v := config.NewItemNotification.ValueString(); v != "" {
		sp.NewItemNotification = objectParam(v)
	}
	if !config.PreferAccessibleContent.IsNull() {
		if !plan.PreferAccessibleContent.IsUnknown() {
			sp.PreferAccessibleContent = plan.PreferAccessibleContent.ValueBoolPointer()
		}
	}
	if v := config.PreviewMarkAsReadBehavior.ValueString(); v != "" {
		sp.PreviewMarkAsReadBehavior = objectParam(v)
	}
	if !config.PreviewMarkAsReadDelaytime.IsNull() {
		if !plan.PreviewMarkAsReadDelaytime.IsUnknown() {
			sp.PreviewMarkAsReadDelaytime = plan.PreviewMarkAsReadDelaytime.ValueInt64Pointer()
		}
	}
	if v := config.ReadReceiptResponse.ValueString(); v != "" {
		sp.ReadReceiptResponse = objectParam(v)
	}
	if !config.ReportJunkSelected.IsNull() {
		if !plan.ReportJunkSelected.IsUnknown() {
			sp.ReportJunkSelected = plan.ReportJunkSelected.ValueBoolPointer()
		}
	}
	if !config.SendAddressDefault.IsNull() {
		sp.SendAddressDefault = plan.SendAddressDefault.ValueString()
	}
	if !config.ShowConversationAsTree.IsNull() {
		if !plan.ShowConversationAsTree.IsUnknown() {
			sp.ShowConversationAsTree = plan.ShowConversationAsTree.ValueBoolPointer()
		}
	}
	if !config.ShowInlinePreviews.IsNull() {
		if !plan.ShowInlinePreviews.IsUnknown() {
			sp.ShowInlinePreviews = plan.ShowInlinePreviews.ValueBoolPointer()
		}
	}
	if !config.ShowNotificationBar.IsNull() {
		if !plan.ShowNotificationBar.IsUnknown() {
			sp.ShowNotificationBar = plan.ShowNotificationBar.ValueBoolPointer()
		}
	}
	if !config.ShowPreviewTextInListView.IsNull() {
		if !plan.ShowPreviewTextInListView.IsUnknown() {
			sp.ShowPreviewTextInListView = plan.ShowPreviewTextInListView.ValueBoolPointer()
		}
	}
	if !config.ShowReadingPaneOnFirstLoad.IsNull() {
		if !plan.ShowReadingPaneOnFirstLoad.IsUnknown() {
			sp.ShowReadingPaneOnFirstLoad = plan.ShowReadingPaneOnFirstLoad.ValueBoolPointer()
		}
	}
	if !config.ShowSenderOnTopInListView.IsNull() {
		if !plan.ShowSenderOnTopInListView.IsUnknown() {
			sp.ShowSenderOnTopInListView = plan.ShowSenderOnTopInListView.ValueBoolPointer()
		}
	}
	if !config.ShowUpNext.IsNull() {
		if !plan.ShowUpNext.IsUnknown() {
			sp.ShowUpNext = plan.ShowUpNext.ValueBoolPointer()
		}
	}
	if !config.SignatureHtml.IsNull() {
		sp.SignatureHtml = plan.SignatureHtml.ValueString()
	}
	if !config.SignatureHtmlBody.IsNull() {
		sp.SignatureHtmlBody = plan.SignatureHtmlBody.ValueString()
	}
	if !config.SignatureName.IsNull() {
		sp.SignatureName = plan.SignatureName.ValueString()
	}
	if !config.SignatureText.IsNull() {
		sp.SignatureText = plan.SignatureText.ValueString()
	}
	if !config.SignatureTextOnMobile.IsNull() {
		sp.SignatureTextOnMobile = plan.SignatureTextOnMobile.ValueString()
	}
	if !config.SigningCertificateId.IsNull() {
		sp.SigningCertificateId = plan.SigningCertificateId.ValueString()
	}
	if !config.SigningCertificateSubject.IsNull() {
		sp.SigningCertificateSubject = plan.SigningCertificateSubject.ValueString()
	}
	if !config.SmimeEncrypt.IsNull() {
		if !plan.SmimeEncrypt.IsUnknown() {
			sp.SmimeEncrypt = plan.SmimeEncrypt.ValueBoolPointer()
		}
	}
	if !config.SmimeSign.IsNull() {
		if !plan.SmimeSign.IsUnknown() {
			sp.SmimeSign = plan.SmimeSign.ValueBoolPointer()
		}
	}
	if !config.UseDefaultSignatureOnMobile.IsNull() {
		if !plan.UseDefaultSignatureOnMobile.IsUnknown() {
			sp.UseDefaultSignatureOnMobile = plan.UseDefaultSignatureOnMobile.ValueBoolPointer()
		}
	}
	if !config.WebSuggestedRepliesEnabledForUser.IsNull() {
		if !plan.WebSuggestedRepliesEnabledForUser.IsUnknown() {
			sp.WebSuggestedRepliesEnabledForUser = plan.WebSuggestedRepliesEnabledForUser.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetMailboxMessageConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MailboxMessageConfiguration failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailboxMessageConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mailboxMessageConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mailboxMessageConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state mailboxMessageConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetMailboxMessageConfigurationParams{}
	sp.Identity = id
	if v := plan.AfterMoveOrDeleteBehavior.ValueString(); v != "" {
		sp.AfterMoveOrDeleteBehavior = objectParam(v)
	}
	if !plan.AlwaysShowBcc.Equal(state.AlwaysShowBcc) {
		if !plan.AlwaysShowBcc.IsUnknown() {
			sp.AlwaysShowBcc = plan.AlwaysShowBcc.ValueBoolPointer()
		}
	}
	if !plan.AlwaysShowFrom.Equal(state.AlwaysShowFrom) {
		if !plan.AlwaysShowFrom.IsUnknown() {
			sp.AlwaysShowFrom = plan.AlwaysShowFrom.ValueBoolPointer()
		}
	}
	if !plan.AutoAddSignature.Equal(state.AutoAddSignature) {
		if !plan.AutoAddSignature.IsUnknown() {
			sp.AutoAddSignature = plan.AutoAddSignature.ValueBoolPointer()
		}
	}
	if !plan.AutoAddSignatureOnMobile.Equal(state.AutoAddSignatureOnMobile) {
		if !plan.AutoAddSignatureOnMobile.IsUnknown() {
			sp.AutoAddSignatureOnMobile = plan.AutoAddSignatureOnMobile.ValueBoolPointer()
		}
	}
	if !plan.AutoAddSignatureOnReply.Equal(state.AutoAddSignatureOnReply) {
		if !plan.AutoAddSignatureOnReply.IsUnknown() {
			sp.AutoAddSignatureOnReply = plan.AutoAddSignatureOnReply.ValueBoolPointer()
		}
	}
	if !plan.CheckForForgottenAttachments.Equal(state.CheckForForgottenAttachments) {
		if !plan.CheckForForgottenAttachments.IsUnknown() {
			sp.CheckForForgottenAttachments = plan.CheckForForgottenAttachments.ValueBoolPointer()
		}
	}
	if !plan.CheckForReportJunkDialog.Equal(state.CheckForReportJunkDialog) {
		if !plan.CheckForReportJunkDialog.IsUnknown() {
			sp.CheckForReportJunkDialog = plan.CheckForReportJunkDialog.ValueBoolPointer()
		}
	}
	if v := plan.ConversationSortOrder.ValueString(); v != "" {
		sp.ConversationSortOrder = objectParam(v)
	}
	if !plan.DefaultFontColor.Equal(state.DefaultFontColor) {
		sp.DefaultFontColor = plan.DefaultFontColor.ValueString()
	}
	if v := plan.DefaultFontFlags.ValueString(); v != "" {
		sp.DefaultFontFlags = objectParam(v)
	}
	if !plan.DefaultFontName.Equal(state.DefaultFontName) {
		sp.DefaultFontName = plan.DefaultFontName.ValueString()
	}
	if !plan.DefaultFontSize.Equal(state.DefaultFontSize) {
		if !plan.DefaultFontSize.IsUnknown() {
			sp.DefaultFontSize = plan.DefaultFontSize.ValueInt64Pointer()
		}
	}
	if v := plan.DefaultFormat.ValueString(); v != "" {
		sp.DefaultFormat = objectParam(v)
	}
	if !plan.DefaultSignature.Equal(state.DefaultSignature) {
		sp.DefaultSignature = plan.DefaultSignature.ValueString()
	}
	if !plan.DefaultSignatureOnReply.Equal(state.DefaultSignatureOnReply) {
		sp.DefaultSignatureOnReply = plan.DefaultSignatureOnReply.ValueString()
	}
	if !plan.DeleteSignatureName.Equal(state.DeleteSignatureName) {
		sp.DeleteSignatureName = plan.DeleteSignatureName.ValueString()
	}
	if v := plan.DisplayDensityMode.ValueString(); v != "" {
		sp.DisplayDensityMode = objectParam(v)
	}
	if !plan.EchoGroupMessageBackToSubscribedSender.Equal(state.EchoGroupMessageBackToSubscribedSender) {
		if !plan.EchoGroupMessageBackToSubscribedSender.IsUnknown() {
			sp.EchoGroupMessageBackToSubscribedSender = plan.EchoGroupMessageBackToSubscribedSender.ValueBoolPointer()
		}
	}
	if v := plan.EmailComposeMode.ValueString(); v != "" {
		sp.EmailComposeMode = objectParam(v)
	}
	if !plan.EmptyDeletedItemsOnLogoff.Equal(state.EmptyDeletedItemsOnLogoff) {
		if !plan.EmptyDeletedItemsOnLogoff.IsUnknown() {
			sp.EmptyDeletedItemsOnLogoff = plan.EmptyDeletedItemsOnLogoff.ValueBoolPointer()
		}
	}
	if !plan.FavoritesBitFlags.Equal(state.FavoritesBitFlags) {
		if !plan.FavoritesBitFlags.IsUnknown() {
			sp.FavoritesBitFlags = plan.FavoritesBitFlags.ValueInt64Pointer()
		}
	}
	if v := plan.GlobalReadingPanePosition.ValueString(); v != "" {
		sp.GlobalReadingPanePosition = objectParam(v)
	}
	if !plan.HideDeletedItems.Equal(state.HideDeletedItems) {
		if !plan.HideDeletedItems.IsUnknown() {
			sp.HideDeletedItems = plan.HideDeletedItems.ValueBoolPointer()
		}
	}
	if !plan.IsDarkModeTheme.Equal(state.IsDarkModeTheme) {
		if !plan.IsDarkModeTheme.IsUnknown() {
			sp.IsDarkModeTheme = plan.IsDarkModeTheme.ValueBoolPointer()
		}
	}
	if !plan.IsFavoritesFolderTreeCollapsed.Equal(state.IsFavoritesFolderTreeCollapsed) {
		if !plan.IsFavoritesFolderTreeCollapsed.IsUnknown() {
			sp.IsFavoritesFolderTreeCollapsed = plan.IsFavoritesFolderTreeCollapsed.ValueBoolPointer()
		}
	}
	if !plan.IsFocusedInboxEnabled.Equal(state.IsFocusedInboxEnabled) {
		if !plan.IsFocusedInboxEnabled.IsUnknown() {
			sp.IsFocusedInboxEnabled = plan.IsFocusedInboxEnabled.ValueBoolPointer()
		}
	}
	if !plan.IsMailRootFolderTreeCollapsed.Equal(state.IsMailRootFolderTreeCollapsed) {
		if !plan.IsMailRootFolderTreeCollapsed.IsUnknown() {
			sp.IsMailRootFolderTreeCollapsed = plan.IsMailRootFolderTreeCollapsed.ValueBoolPointer()
		}
	}
	if !plan.IsReplyAllTheDefaultResponse.Equal(state.IsReplyAllTheDefaultResponse) {
		if !plan.IsReplyAllTheDefaultResponse.IsUnknown() {
			sp.IsReplyAllTheDefaultResponse = plan.IsReplyAllTheDefaultResponse.ValueBoolPointer()
		}
	}
	if !plan.LinkPreviewEnabled.Equal(state.LinkPreviewEnabled) {
		if !plan.LinkPreviewEnabled.IsUnknown() {
			sp.LinkPreviewEnabled = plan.LinkPreviewEnabled.ValueBoolPointer()
		}
	}
	if !plan.MailFolderPaneExpanded.Equal(state.MailFolderPaneExpanded) {
		if !plan.MailFolderPaneExpanded.IsUnknown() {
			sp.MailFolderPaneExpanded = plan.MailFolderPaneExpanded.ValueBoolPointer()
		}
	}
	if !plan.MailSendUndoInterval.Equal(state.MailSendUndoInterval) {
		if !plan.MailSendUndoInterval.IsUnknown() {
			sp.MailSendUndoInterval = plan.MailSendUndoInterval.ValueInt64Pointer()
		}
	}
	if !plan.ManuallyPickCertificate.Equal(state.ManuallyPickCertificate) {
		if !plan.ManuallyPickCertificate.IsUnknown() {
			sp.ManuallyPickCertificate = plan.ManuallyPickCertificate.ValueBoolPointer()
		}
	}
	if !plan.NavigationBarWidth.Equal(state.NavigationBarWidth) {
		if !plan.NavigationBarWidth.IsUnknown() {
			sp.NavigationBarWidth = plan.NavigationBarWidth.ValueInt64Pointer()
		}
	}
	if v := plan.NavigationPaneViewOption.ValueString(); v != "" {
		sp.NavigationPaneViewOption = objectParam(v)
	}
	if v := plan.NewEnabledPonts.ValueString(); v != "" {
		sp.NewEnabledPonts = objectParam(v)
	}
	if v := plan.NewItemNotification.ValueString(); v != "" {
		sp.NewItemNotification = objectParam(v)
	}
	if !plan.PreferAccessibleContent.Equal(state.PreferAccessibleContent) {
		if !plan.PreferAccessibleContent.IsUnknown() {
			sp.PreferAccessibleContent = plan.PreferAccessibleContent.ValueBoolPointer()
		}
	}
	if v := plan.PreviewMarkAsReadBehavior.ValueString(); v != "" {
		sp.PreviewMarkAsReadBehavior = objectParam(v)
	}
	if !plan.PreviewMarkAsReadDelaytime.Equal(state.PreviewMarkAsReadDelaytime) {
		if !plan.PreviewMarkAsReadDelaytime.IsUnknown() {
			sp.PreviewMarkAsReadDelaytime = plan.PreviewMarkAsReadDelaytime.ValueInt64Pointer()
		}
	}
	if v := plan.ReadReceiptResponse.ValueString(); v != "" {
		sp.ReadReceiptResponse = objectParam(v)
	}
	if !plan.ReportJunkSelected.Equal(state.ReportJunkSelected) {
		if !plan.ReportJunkSelected.IsUnknown() {
			sp.ReportJunkSelected = plan.ReportJunkSelected.ValueBoolPointer()
		}
	}
	if !plan.SendAddressDefault.Equal(state.SendAddressDefault) {
		sp.SendAddressDefault = plan.SendAddressDefault.ValueString()
	}
	if !plan.ShowConversationAsTree.Equal(state.ShowConversationAsTree) {
		if !plan.ShowConversationAsTree.IsUnknown() {
			sp.ShowConversationAsTree = plan.ShowConversationAsTree.ValueBoolPointer()
		}
	}
	if !plan.ShowInlinePreviews.Equal(state.ShowInlinePreviews) {
		if !plan.ShowInlinePreviews.IsUnknown() {
			sp.ShowInlinePreviews = plan.ShowInlinePreviews.ValueBoolPointer()
		}
	}
	if !plan.ShowNotificationBar.Equal(state.ShowNotificationBar) {
		if !plan.ShowNotificationBar.IsUnknown() {
			sp.ShowNotificationBar = plan.ShowNotificationBar.ValueBoolPointer()
		}
	}
	if !plan.ShowPreviewTextInListView.Equal(state.ShowPreviewTextInListView) {
		if !plan.ShowPreviewTextInListView.IsUnknown() {
			sp.ShowPreviewTextInListView = plan.ShowPreviewTextInListView.ValueBoolPointer()
		}
	}
	if !plan.ShowReadingPaneOnFirstLoad.Equal(state.ShowReadingPaneOnFirstLoad) {
		if !plan.ShowReadingPaneOnFirstLoad.IsUnknown() {
			sp.ShowReadingPaneOnFirstLoad = plan.ShowReadingPaneOnFirstLoad.ValueBoolPointer()
		}
	}
	if !plan.ShowSenderOnTopInListView.Equal(state.ShowSenderOnTopInListView) {
		if !plan.ShowSenderOnTopInListView.IsUnknown() {
			sp.ShowSenderOnTopInListView = plan.ShowSenderOnTopInListView.ValueBoolPointer()
		}
	}
	if !plan.ShowUpNext.Equal(state.ShowUpNext) {
		if !plan.ShowUpNext.IsUnknown() {
			sp.ShowUpNext = plan.ShowUpNext.ValueBoolPointer()
		}
	}
	if !plan.SignatureHtml.Equal(state.SignatureHtml) {
		sp.SignatureHtml = plan.SignatureHtml.ValueString()
	}
	if !plan.SignatureHtmlBody.Equal(state.SignatureHtmlBody) {
		sp.SignatureHtmlBody = plan.SignatureHtmlBody.ValueString()
	}
	if !plan.SignatureName.Equal(state.SignatureName) {
		sp.SignatureName = plan.SignatureName.ValueString()
	}
	if !plan.SignatureText.Equal(state.SignatureText) {
		sp.SignatureText = plan.SignatureText.ValueString()
	}
	if !plan.SignatureTextOnMobile.Equal(state.SignatureTextOnMobile) {
		sp.SignatureTextOnMobile = plan.SignatureTextOnMobile.ValueString()
	}
	if !plan.SigningCertificateId.Equal(state.SigningCertificateId) {
		sp.SigningCertificateId = plan.SigningCertificateId.ValueString()
	}
	if !plan.SigningCertificateSubject.Equal(state.SigningCertificateSubject) {
		sp.SigningCertificateSubject = plan.SigningCertificateSubject.ValueString()
	}
	if !plan.SmimeEncrypt.Equal(state.SmimeEncrypt) {
		if !plan.SmimeEncrypt.IsUnknown() {
			sp.SmimeEncrypt = plan.SmimeEncrypt.ValueBoolPointer()
		}
	}
	if !plan.SmimeSign.Equal(state.SmimeSign) {
		if !plan.SmimeSign.IsUnknown() {
			sp.SmimeSign = plan.SmimeSign.ValueBoolPointer()
		}
	}
	if !plan.UseDefaultSignatureOnMobile.Equal(state.UseDefaultSignatureOnMobile) {
		if !plan.UseDefaultSignatureOnMobile.IsUnknown() {
			sp.UseDefaultSignatureOnMobile = plan.UseDefaultSignatureOnMobile.ValueBoolPointer()
		}
	}
	if !plan.WebSuggestedRepliesEnabledForUser.Equal(state.WebSuggestedRepliesEnabledForUser) {
		if !plan.WebSuggestedRepliesEnabledForUser.IsUnknown() {
			sp.WebSuggestedRepliesEnabledForUser = plan.WebSuggestedRepliesEnabledForUser.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetMailboxMessageConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MailboxMessageConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DefaultFontColor":          cfg.DefaultFontColor,
		"DefaultFontName":           cfg.DefaultFontName,
		"DefaultSignature":          cfg.DefaultSignature,
		"DefaultSignatureOnReply":   cfg.DefaultSignatureOnReply,
		"DeleteSignatureName":       cfg.DeleteSignatureName,
		"SendAddressDefault":        cfg.SendAddressDefault,
		"SignatureHtml":             cfg.SignatureHtml,
		"SignatureHtmlBody":         cfg.SignatureHtmlBody,
		"SignatureName":             cfg.SignatureName,
		"SignatureText":             cfg.SignatureText,
		"SignatureTextOnMobile":     cfg.SignatureTextOnMobile,
		"SigningCertificateId":      cfg.SigningCertificateId,
		"SigningCertificateSubject": cfg.SigningCertificateSubject,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mailboxMessageConfigurationResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("MailboxMessageConfiguration configuration not deleted", "This resource manages an existing MailboxMessageConfiguration configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *mailboxMessageConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *mailboxMessageConfigurationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() || !req.State.Raw.IsNull() || r.client == nil {
		return
	}
	var plan mailboxMessageConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := plan.Identity.ValueString()
	if identity == "" {
		return
	}
	res, err := r.client.EXO.GetMailboxMessageConfiguration(ctx, exo.GetMailboxMessageConfigurationParams{Identity: identity})
	if err != nil {
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		return
	}
	var cur mailboxMessageConfigurationModel
	readMailboxMessageConfiguration(ctx, obj, &cur)
	if plan.ID.IsUnknown() {
		plan.ID = cur.ID
	}
	if plan.Identity.IsUnknown() {
		plan.Identity = cur.Identity
	}
	if plan.AfterMoveOrDeleteBehavior.IsUnknown() {
		plan.AfterMoveOrDeleteBehavior = cur.AfterMoveOrDeleteBehavior
	}
	if plan.AlwaysShowBcc.IsUnknown() {
		plan.AlwaysShowBcc = cur.AlwaysShowBcc
	}
	if plan.AlwaysShowFrom.IsUnknown() {
		plan.AlwaysShowFrom = cur.AlwaysShowFrom
	}
	if plan.AutoAddSignature.IsUnknown() {
		plan.AutoAddSignature = cur.AutoAddSignature
	}
	if plan.AutoAddSignatureOnMobile.IsUnknown() {
		plan.AutoAddSignatureOnMobile = cur.AutoAddSignatureOnMobile
	}
	if plan.AutoAddSignatureOnReply.IsUnknown() {
		plan.AutoAddSignatureOnReply = cur.AutoAddSignatureOnReply
	}
	if plan.CheckForForgottenAttachments.IsUnknown() {
		plan.CheckForForgottenAttachments = cur.CheckForForgottenAttachments
	}
	if plan.CheckForReportJunkDialog.IsUnknown() {
		plan.CheckForReportJunkDialog = cur.CheckForReportJunkDialog
	}
	if plan.ConversationSortOrder.IsUnknown() {
		plan.ConversationSortOrder = cur.ConversationSortOrder
	}
	if plan.DefaultFontColor.IsUnknown() {
		plan.DefaultFontColor = cur.DefaultFontColor
	}
	if plan.DefaultFontFlags.IsUnknown() {
		plan.DefaultFontFlags = cur.DefaultFontFlags
	}
	if plan.DefaultFontName.IsUnknown() {
		plan.DefaultFontName = cur.DefaultFontName
	}
	if plan.DefaultFontSize.IsUnknown() {
		plan.DefaultFontSize = cur.DefaultFontSize
	}
	if plan.DefaultFormat.IsUnknown() {
		plan.DefaultFormat = cur.DefaultFormat
	}
	if plan.DefaultSignature.IsUnknown() {
		plan.DefaultSignature = cur.DefaultSignature
	}
	if plan.DefaultSignatureOnReply.IsUnknown() {
		plan.DefaultSignatureOnReply = cur.DefaultSignatureOnReply
	}
	if plan.DeleteSignatureName.IsUnknown() {
		plan.DeleteSignatureName = cur.DeleteSignatureName
	}
	if plan.DisplayDensityMode.IsUnknown() {
		plan.DisplayDensityMode = cur.DisplayDensityMode
	}
	if plan.EchoGroupMessageBackToSubscribedSender.IsUnknown() {
		plan.EchoGroupMessageBackToSubscribedSender = cur.EchoGroupMessageBackToSubscribedSender
	}
	if plan.EmailComposeMode.IsUnknown() {
		plan.EmailComposeMode = cur.EmailComposeMode
	}
	if plan.EmptyDeletedItemsOnLogoff.IsUnknown() {
		plan.EmptyDeletedItemsOnLogoff = cur.EmptyDeletedItemsOnLogoff
	}
	if plan.FavoritesBitFlags.IsUnknown() {
		plan.FavoritesBitFlags = cur.FavoritesBitFlags
	}
	if plan.GlobalReadingPanePosition.IsUnknown() {
		plan.GlobalReadingPanePosition = cur.GlobalReadingPanePosition
	}
	if plan.HideDeletedItems.IsUnknown() {
		plan.HideDeletedItems = cur.HideDeletedItems
	}
	if plan.IsDarkModeTheme.IsUnknown() {
		plan.IsDarkModeTheme = cur.IsDarkModeTheme
	}
	if plan.IsFavoritesFolderTreeCollapsed.IsUnknown() {
		plan.IsFavoritesFolderTreeCollapsed = cur.IsFavoritesFolderTreeCollapsed
	}
	if plan.IsFocusedInboxEnabled.IsUnknown() {
		plan.IsFocusedInboxEnabled = cur.IsFocusedInboxEnabled
	}
	if plan.IsMailRootFolderTreeCollapsed.IsUnknown() {
		plan.IsMailRootFolderTreeCollapsed = cur.IsMailRootFolderTreeCollapsed
	}
	if plan.IsReplyAllTheDefaultResponse.IsUnknown() {
		plan.IsReplyAllTheDefaultResponse = cur.IsReplyAllTheDefaultResponse
	}
	if plan.LinkPreviewEnabled.IsUnknown() {
		plan.LinkPreviewEnabled = cur.LinkPreviewEnabled
	}
	if plan.MailFolderPaneExpanded.IsUnknown() {
		plan.MailFolderPaneExpanded = cur.MailFolderPaneExpanded
	}
	if plan.MailSendUndoInterval.IsUnknown() {
		plan.MailSendUndoInterval = cur.MailSendUndoInterval
	}
	if plan.ManuallyPickCertificate.IsUnknown() {
		plan.ManuallyPickCertificate = cur.ManuallyPickCertificate
	}
	if plan.NavigationBarWidth.IsUnknown() {
		plan.NavigationBarWidth = cur.NavigationBarWidth
	}
	if plan.NavigationPaneViewOption.IsUnknown() {
		plan.NavigationPaneViewOption = cur.NavigationPaneViewOption
	}
	if plan.NewEnabledPonts.IsUnknown() {
		plan.NewEnabledPonts = cur.NewEnabledPonts
	}
	if plan.NewItemNotification.IsUnknown() {
		plan.NewItemNotification = cur.NewItemNotification
	}
	if plan.PreferAccessibleContent.IsUnknown() {
		plan.PreferAccessibleContent = cur.PreferAccessibleContent
	}
	if plan.PreviewMarkAsReadBehavior.IsUnknown() {
		plan.PreviewMarkAsReadBehavior = cur.PreviewMarkAsReadBehavior
	}
	if plan.PreviewMarkAsReadDelaytime.IsUnknown() {
		plan.PreviewMarkAsReadDelaytime = cur.PreviewMarkAsReadDelaytime
	}
	if plan.ReadReceiptResponse.IsUnknown() {
		plan.ReadReceiptResponse = cur.ReadReceiptResponse
	}
	if plan.ReportJunkSelected.IsUnknown() {
		plan.ReportJunkSelected = cur.ReportJunkSelected
	}
	if plan.SendAddressDefault.IsUnknown() {
		plan.SendAddressDefault = cur.SendAddressDefault
	}
	if plan.ShowConversationAsTree.IsUnknown() {
		plan.ShowConversationAsTree = cur.ShowConversationAsTree
	}
	if plan.ShowInlinePreviews.IsUnknown() {
		plan.ShowInlinePreviews = cur.ShowInlinePreviews
	}
	if plan.ShowNotificationBar.IsUnknown() {
		plan.ShowNotificationBar = cur.ShowNotificationBar
	}
	if plan.ShowPreviewTextInListView.IsUnknown() {
		plan.ShowPreviewTextInListView = cur.ShowPreviewTextInListView
	}
	if plan.ShowReadingPaneOnFirstLoad.IsUnknown() {
		plan.ShowReadingPaneOnFirstLoad = cur.ShowReadingPaneOnFirstLoad
	}
	if plan.ShowSenderOnTopInListView.IsUnknown() {
		plan.ShowSenderOnTopInListView = cur.ShowSenderOnTopInListView
	}
	if plan.ShowUpNext.IsUnknown() {
		plan.ShowUpNext = cur.ShowUpNext
	}
	if plan.SignatureHtml.IsUnknown() {
		plan.SignatureHtml = cur.SignatureHtml
	}
	if plan.SignatureHtmlBody.IsUnknown() {
		plan.SignatureHtmlBody = cur.SignatureHtmlBody
	}
	if plan.SignatureName.IsUnknown() {
		plan.SignatureName = cur.SignatureName
	}
	if plan.SignatureText.IsUnknown() {
		plan.SignatureText = cur.SignatureText
	}
	if plan.SignatureTextOnMobile.IsUnknown() {
		plan.SignatureTextOnMobile = cur.SignatureTextOnMobile
	}
	if plan.SigningCertificateId.IsUnknown() {
		plan.SigningCertificateId = cur.SigningCertificateId
	}
	if plan.SigningCertificateSubject.IsUnknown() {
		plan.SigningCertificateSubject = cur.SigningCertificateSubject
	}
	if plan.SmimeEncrypt.IsUnknown() {
		plan.SmimeEncrypt = cur.SmimeEncrypt
	}
	if plan.SmimeSign.IsUnknown() {
		plan.SmimeSign = cur.SmimeSign
	}
	if plan.UseDefaultSignatureOnMobile.IsUnknown() {
		plan.UseDefaultSignatureOnMobile = cur.UseDefaultSignatureOnMobile
	}
	if plan.WebSuggestedRepliesEnabledForUser.IsUnknown() {
		plan.WebSuggestedRepliesEnabledForUser = cur.WebSuggestedRepliesEnabledForUser
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *mailboxMessageConfigurationResource) identityOf(m mailboxMessageConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *mailboxMessageConfigurationResource) refresh(ctx context.Context, identity string, m *mailboxMessageConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetMailboxMessageConfiguration(ctx, exo.GetMailboxMessageConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MailboxMessageConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMailboxMessageConfiguration(ctx, obj, m)
	return true
}

func readMailboxMessageConfiguration(ctx context.Context, obj map[string]any, m *mailboxMessageConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AfterMoveOrDeleteBehavior = types.StringValue(getObjectJSON(obj, "AfterMoveOrDeleteBehavior"))
	m.AlwaysShowBcc = types.BoolValue(getBool(obj, "AlwaysShowBcc"))
	m.AlwaysShowFrom = types.BoolValue(getBool(obj, "AlwaysShowFrom"))
	m.AutoAddSignature = types.BoolValue(getBool(obj, "AutoAddSignature"))
	m.AutoAddSignatureOnMobile = types.BoolValue(getBool(obj, "AutoAddSignatureOnMobile"))
	m.AutoAddSignatureOnReply = types.BoolValue(getBool(obj, "AutoAddSignatureOnReply"))
	m.CheckForForgottenAttachments = types.BoolValue(getBool(obj, "CheckForForgottenAttachments"))
	m.CheckForReportJunkDialog = types.BoolValue(getBool(obj, "CheckForReportJunkDialog"))
	m.ConversationSortOrder = types.StringValue(getObjectJSON(obj, "ConversationSortOrder"))
	m.DefaultFontColor = types.StringValue(getString(obj, "DefaultFontColor"))
	m.DefaultFontFlags = types.StringValue(getObjectJSON(obj, "DefaultFontFlags"))
	m.DefaultFontName = types.StringValue(getString(obj, "DefaultFontName"))
	m.DefaultFontSize = types.Int64Value(getInt(obj, "DefaultFontSize"))
	m.DefaultFormat = types.StringValue(getObjectJSON(obj, "DefaultFormat"))
	m.DefaultSignature = types.StringValue(getString(obj, "DefaultSignature"))
	m.DefaultSignatureOnReply = types.StringValue(getString(obj, "DefaultSignatureOnReply"))
	m.DeleteSignatureName = types.StringValue(getString(obj, "DeleteSignatureName"))
	m.DisplayDensityMode = types.StringValue(getObjectJSON(obj, "DisplayDensityMode"))
	m.EchoGroupMessageBackToSubscribedSender = types.BoolValue(getBool(obj, "EchoGroupMessageBackToSubscribedSender"))
	m.EmailComposeMode = types.StringValue(getObjectJSON(obj, "EmailComposeMode"))
	m.EmptyDeletedItemsOnLogoff = types.BoolValue(getBool(obj, "EmptyDeletedItemsOnLogoff"))
	m.FavoritesBitFlags = types.Int64Value(getInt(obj, "FavoritesBitFlags"))
	m.GlobalReadingPanePosition = types.StringValue(getObjectJSON(obj, "GlobalReadingPanePosition"))
	m.HideDeletedItems = types.BoolValue(getBool(obj, "HideDeletedItems"))
	m.IsDarkModeTheme = types.BoolValue(getBool(obj, "IsDarkModeTheme"))
	m.IsFavoritesFolderTreeCollapsed = types.BoolValue(getBool(obj, "IsFavoritesFolderTreeCollapsed"))
	m.IsFocusedInboxEnabled = types.BoolValue(getBool(obj, "IsFocusedInboxEnabled"))
	m.IsMailRootFolderTreeCollapsed = types.BoolValue(getBool(obj, "IsMailRootFolderTreeCollapsed"))
	m.IsReplyAllTheDefaultResponse = types.BoolValue(getBool(obj, "IsReplyAllTheDefaultResponse"))
	m.LinkPreviewEnabled = types.BoolValue(getBool(obj, "LinkPreviewEnabled"))
	m.MailFolderPaneExpanded = types.BoolValue(getBool(obj, "MailFolderPaneExpanded"))
	m.MailSendUndoInterval = types.Int64Value(getInt(obj, "MailSendUndoInterval"))
	m.ManuallyPickCertificate = types.BoolValue(getBool(obj, "ManuallyPickCertificate"))
	m.NavigationBarWidth = types.Int64Value(getInt(obj, "NavigationBarWidth"))
	m.NavigationPaneViewOption = types.StringValue(getObjectJSON(obj, "NavigationPaneViewOption"))
	m.NewEnabledPonts = types.StringValue(getObjectJSON(obj, "NewEnabledPonts"))
	m.NewItemNotification = types.StringValue(getObjectJSON(obj, "NewItemNotification"))
	m.PreferAccessibleContent = types.BoolValue(getBool(obj, "PreferAccessibleContent"))
	m.PreviewMarkAsReadBehavior = types.StringValue(getObjectJSON(obj, "PreviewMarkAsReadBehavior"))
	m.PreviewMarkAsReadDelaytime = types.Int64Value(getInt(obj, "PreviewMarkAsReadDelaytime"))
	m.ReadReceiptResponse = types.StringValue(getObjectJSON(obj, "ReadReceiptResponse"))
	m.ReportJunkSelected = types.BoolValue(getBool(obj, "ReportJunkSelected"))
	m.SendAddressDefault = types.StringValue(getString(obj, "SendAddressDefault"))
	m.ShowConversationAsTree = types.BoolValue(getBool(obj, "ShowConversationAsTree"))
	m.ShowInlinePreviews = types.BoolValue(getBool(obj, "ShowInlinePreviews"))
	m.ShowNotificationBar = types.BoolValue(getBool(obj, "ShowNotificationBar"))
	m.ShowPreviewTextInListView = types.BoolValue(getBool(obj, "ShowPreviewTextInListView"))
	m.ShowReadingPaneOnFirstLoad = types.BoolValue(getBool(obj, "ShowReadingPaneOnFirstLoad"))
	m.ShowSenderOnTopInListView = types.BoolValue(getBool(obj, "ShowSenderOnTopInListView"))
	m.ShowUpNext = types.BoolValue(getBool(obj, "ShowUpNext"))
	m.SignatureHtml = types.StringValue(getString(obj, "SignatureHtml"))
	m.SignatureHtmlBody = types.StringValue(getString(obj, "SignatureHtmlBody"))
	m.SignatureName = types.StringValue(getString(obj, "SignatureName"))
	m.SignatureText = types.StringValue(getString(obj, "SignatureText"))
	m.SignatureTextOnMobile = types.StringValue(getString(obj, "SignatureTextOnMobile"))
	m.SigningCertificateId = types.StringValue(getString(obj, "SigningCertificateId"))
	m.SigningCertificateSubject = types.StringValue(getString(obj, "SigningCertificateSubject"))
	m.SmimeEncrypt = types.BoolValue(getBool(obj, "SmimeEncrypt"))
	m.SmimeSign = types.BoolValue(getBool(obj, "SmimeSign"))
	m.UseDefaultSignatureOnMobile = types.BoolValue(getBool(obj, "UseDefaultSignatureOnMobile"))
	m.WebSuggestedRepliesEnabledForUser = types.BoolValue(getBool(obj, "WebSuggestedRepliesEnabledForUser"))
	_ = ctx
}

func (r *mailboxMessageConfigurationResource) reconcileState(cfg, read *mailboxMessageConfigurationModel) {
	read.AfterMoveOrDeleteBehavior = reconcile.KeepStr(cfg.AfterMoveOrDeleteBehavior, read.AfterMoveOrDeleteBehavior)
	read.AlwaysShowBcc = reconcile.KeepBool(cfg.AlwaysShowBcc, read.AlwaysShowBcc)
	read.AlwaysShowFrom = reconcile.KeepBool(cfg.AlwaysShowFrom, read.AlwaysShowFrom)
	read.AutoAddSignature = reconcile.KeepBool(cfg.AutoAddSignature, read.AutoAddSignature)
	read.AutoAddSignatureOnMobile = reconcile.KeepBool(cfg.AutoAddSignatureOnMobile, read.AutoAddSignatureOnMobile)
	read.AutoAddSignatureOnReply = reconcile.KeepBool(cfg.AutoAddSignatureOnReply, read.AutoAddSignatureOnReply)
	read.CheckForForgottenAttachments = reconcile.KeepBool(cfg.CheckForForgottenAttachments, read.CheckForForgottenAttachments)
	read.CheckForReportJunkDialog = reconcile.KeepBool(cfg.CheckForReportJunkDialog, read.CheckForReportJunkDialog)
	read.ConversationSortOrder = reconcile.KeepStr(cfg.ConversationSortOrder, read.ConversationSortOrder)
	read.DefaultFontColor = reconcile.KeepStr(cfg.DefaultFontColor, read.DefaultFontColor)
	read.DefaultFontFlags = reconcile.KeepStr(cfg.DefaultFontFlags, read.DefaultFontFlags)
	read.DefaultFontName = reconcile.KeepStr(cfg.DefaultFontName, read.DefaultFontName)
	read.DefaultFontSize = reconcile.KeepInt64(cfg.DefaultFontSize, read.DefaultFontSize)
	read.DefaultFormat = reconcile.KeepStr(cfg.DefaultFormat, read.DefaultFormat)
	read.DefaultSignature = reconcile.KeepStr(cfg.DefaultSignature, read.DefaultSignature)
	read.DefaultSignatureOnReply = reconcile.KeepStr(cfg.DefaultSignatureOnReply, read.DefaultSignatureOnReply)
	read.DeleteSignatureName = reconcile.KeepStr(cfg.DeleteSignatureName, read.DeleteSignatureName)
	read.DisplayDensityMode = reconcile.KeepStr(cfg.DisplayDensityMode, read.DisplayDensityMode)
	read.EchoGroupMessageBackToSubscribedSender = reconcile.KeepBool(cfg.EchoGroupMessageBackToSubscribedSender, read.EchoGroupMessageBackToSubscribedSender)
	read.EmailComposeMode = reconcile.KeepStr(cfg.EmailComposeMode, read.EmailComposeMode)
	read.EmptyDeletedItemsOnLogoff = reconcile.KeepBool(cfg.EmptyDeletedItemsOnLogoff, read.EmptyDeletedItemsOnLogoff)
	read.FavoritesBitFlags = reconcile.KeepInt64(cfg.FavoritesBitFlags, read.FavoritesBitFlags)
	read.GlobalReadingPanePosition = reconcile.KeepStr(cfg.GlobalReadingPanePosition, read.GlobalReadingPanePosition)
	read.HideDeletedItems = reconcile.KeepBool(cfg.HideDeletedItems, read.HideDeletedItems)
	read.IsDarkModeTheme = reconcile.KeepBool(cfg.IsDarkModeTheme, read.IsDarkModeTheme)
	read.IsFavoritesFolderTreeCollapsed = reconcile.KeepBool(cfg.IsFavoritesFolderTreeCollapsed, read.IsFavoritesFolderTreeCollapsed)
	read.IsFocusedInboxEnabled = reconcile.KeepBool(cfg.IsFocusedInboxEnabled, read.IsFocusedInboxEnabled)
	read.IsMailRootFolderTreeCollapsed = reconcile.KeepBool(cfg.IsMailRootFolderTreeCollapsed, read.IsMailRootFolderTreeCollapsed)
	read.IsReplyAllTheDefaultResponse = reconcile.KeepBool(cfg.IsReplyAllTheDefaultResponse, read.IsReplyAllTheDefaultResponse)
	read.LinkPreviewEnabled = reconcile.KeepBool(cfg.LinkPreviewEnabled, read.LinkPreviewEnabled)
	read.MailFolderPaneExpanded = reconcile.KeepBool(cfg.MailFolderPaneExpanded, read.MailFolderPaneExpanded)
	read.MailSendUndoInterval = reconcile.KeepInt64(cfg.MailSendUndoInterval, read.MailSendUndoInterval)
	read.ManuallyPickCertificate = reconcile.KeepBool(cfg.ManuallyPickCertificate, read.ManuallyPickCertificate)
	read.NavigationBarWidth = reconcile.KeepInt64(cfg.NavigationBarWidth, read.NavigationBarWidth)
	read.NavigationPaneViewOption = reconcile.KeepStr(cfg.NavigationPaneViewOption, read.NavigationPaneViewOption)
	read.NewEnabledPonts = reconcile.KeepStr(cfg.NewEnabledPonts, read.NewEnabledPonts)
	read.NewItemNotification = reconcile.KeepStr(cfg.NewItemNotification, read.NewItemNotification)
	read.PreferAccessibleContent = reconcile.KeepBool(cfg.PreferAccessibleContent, read.PreferAccessibleContent)
	read.PreviewMarkAsReadBehavior = reconcile.KeepStr(cfg.PreviewMarkAsReadBehavior, read.PreviewMarkAsReadBehavior)
	read.PreviewMarkAsReadDelaytime = reconcile.KeepInt64(cfg.PreviewMarkAsReadDelaytime, read.PreviewMarkAsReadDelaytime)
	read.ReadReceiptResponse = reconcile.KeepStr(cfg.ReadReceiptResponse, read.ReadReceiptResponse)
	read.ReportJunkSelected = reconcile.KeepBool(cfg.ReportJunkSelected, read.ReportJunkSelected)
	read.SendAddressDefault = reconcile.KeepStr(cfg.SendAddressDefault, read.SendAddressDefault)
	read.ShowConversationAsTree = reconcile.KeepBool(cfg.ShowConversationAsTree, read.ShowConversationAsTree)
	read.ShowInlinePreviews = reconcile.KeepBool(cfg.ShowInlinePreviews, read.ShowInlinePreviews)
	read.ShowNotificationBar = reconcile.KeepBool(cfg.ShowNotificationBar, read.ShowNotificationBar)
	read.ShowPreviewTextInListView = reconcile.KeepBool(cfg.ShowPreviewTextInListView, read.ShowPreviewTextInListView)
	read.ShowReadingPaneOnFirstLoad = reconcile.KeepBool(cfg.ShowReadingPaneOnFirstLoad, read.ShowReadingPaneOnFirstLoad)
	read.ShowSenderOnTopInListView = reconcile.KeepBool(cfg.ShowSenderOnTopInListView, read.ShowSenderOnTopInListView)
	read.ShowUpNext = reconcile.KeepBool(cfg.ShowUpNext, read.ShowUpNext)
	read.SignatureHtml = reconcile.KeepStr(cfg.SignatureHtml, read.SignatureHtml)
	read.SignatureHtmlBody = reconcile.KeepStr(cfg.SignatureHtmlBody, read.SignatureHtmlBody)
	read.SignatureName = reconcile.KeepStr(cfg.SignatureName, read.SignatureName)
	read.SignatureText = reconcile.KeepStr(cfg.SignatureText, read.SignatureText)
	read.SignatureTextOnMobile = reconcile.KeepStr(cfg.SignatureTextOnMobile, read.SignatureTextOnMobile)
	read.SigningCertificateId = reconcile.KeepStr(cfg.SigningCertificateId, read.SigningCertificateId)
	read.SigningCertificateSubject = reconcile.KeepStr(cfg.SigningCertificateSubject, read.SigningCertificateSubject)
	read.SmimeEncrypt = reconcile.KeepBool(cfg.SmimeEncrypt, read.SmimeEncrypt)
	read.SmimeSign = reconcile.KeepBool(cfg.SmimeSign, read.SmimeSign)
	read.UseDefaultSignatureOnMobile = reconcile.KeepBool(cfg.UseDefaultSignatureOnMobile, read.UseDefaultSignatureOnMobile)
	read.WebSuggestedRepliesEnabledForUser = reconcile.KeepBool(cfg.WebSuggestedRepliesEnabledForUser, read.WebSuggestedRepliesEnabledForUser)
}
