// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &managementRoleEntryResource{}
	_ resource.ResourceWithConfigure   = &managementRoleEntryResource{}
	_ resource.ResourceWithImportState = &managementRoleEntryResource{}
)

type managementRoleEntryResource struct{ client *clients.Client }

// NewManagementRoleEntryResource manages the ManagementRoleEntry configuration (Get-ManagementRoleEntry / Set-ManagementRoleEntry); it adopts the existing object and is not deleted on destroy.
func NewManagementRoleEntryResource() resource.Resource { return &managementRoleEntryResource{} }

type managementRoleEntryModel struct {
	ID              types.String `tfsdk:"id"`
	Identity        types.String `tfsdk:"identity"`
	AddParameter    types.Bool   `tfsdk:"add_parameter"`
	Parameters      types.Set    `tfsdk:"parameters"`
	RemoveParameter types.Bool   `tfsdk:"remove_parameter"`
}

func (r *managementRoleEntryResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_management_role_entry"
}

func (r *managementRoleEntryResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ManagementRoleEntry configuration via Set-ManagementRoleEntry.",
		Attributes: map[string]schema.Attribute{
			"id":               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":         schema.StringAttribute{Required: true, Description: "Identity of the existing object whose configuration is managed.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"add_parameter":    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AddParameter parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"parameters":       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -Parameters parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_parameter": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveParameter parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *managementRoleEntryResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *managementRoleEntryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan managementRoleEntryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := exo.SetManagementRoleEntryParams{}
	sp.Identity = plan.Identity.ValueString()
	sp.AddParameter = plan.AddParameter.ValueBool()
	sp.Parameters = toStringSlice(ctx, plan.Parameters, &resp.Diagnostics)
	sp.RemoveParameter = plan.RemoveParameter.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetManagementRoleEntry(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ManagementRoleEntry failed", err.Error())
		return
	}
	cfg := plan
	identity := plan.Identity.ValueString()
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *managementRoleEntryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state managementRoleEntryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *managementRoleEntryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state managementRoleEntryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetManagementRoleEntryParams{}
	sp.Identity = id
	sp.AddParameter = plan.AddParameter.ValueBool()
	sp.Parameters = toStringSlice(ctx, plan.Parameters, &resp.Diagnostics)
	sp.RemoveParameter = plan.RemoveParameter.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetManagementRoleEntry(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ManagementRoleEntry failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *managementRoleEntryResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("ManagementRoleEntry configuration not deleted", "This resource manages an existing ManagementRoleEntry configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *managementRoleEntryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *managementRoleEntryResource) identityOf(m managementRoleEntryModel) any {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *managementRoleEntryResource) refresh(ctx context.Context, identity any, m *managementRoleEntryModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetManagementRoleEntry(ctx, exo.GetManagementRoleEntryParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ManagementRoleEntry failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readManagementRoleEntry(ctx, obj, m)
	return true
}

func readManagementRoleEntry(ctx context.Context, obj map[string]any, m *managementRoleEntryModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.AddParameter = types.BoolValue(getBool(obj, "AddParameter"))
	m.Parameters = stringSetValue(ctx, getStringSlice(obj, "Parameters"))
	m.RemoveParameter = types.BoolValue(getBool(obj, "RemoveParameter"))
	_ = ctx
}

func (r *managementRoleEntryResource) reconcileState(cfg, read *managementRoleEntryModel) {
	read.AddParameter = reconcile.KeepBool(cfg.AddParameter, read.AddParameter)
	read.Parameters = reconcile.KeepSet(cfg.Parameters, read.Parameters)
	read.RemoveParameter = reconcile.KeepBool(cfg.RemoveParameter, read.RemoveParameter)
}
