// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &migrationEndpointResource{}
	_ resource.ResourceWithConfigure   = &migrationEndpointResource{}
	_ resource.ResourceWithImportState = &migrationEndpointResource{}
)

type migrationEndpointResource struct{ client *clients.Client }

// NewMigrationEndpointResource manages the MigrationEndpoint object (New-MigrationEndpoint / Get-MigrationEndpoint / Set-MigrationEndpoint / Remove-MigrationEndpoint).
func NewMigrationEndpointResource() resource.Resource { return &migrationEndpointResource{} }

type migrationEndpointModel struct {
	ID                                 types.String `tfsdk:"id"`
	Identity                           types.String `tfsdk:"identity"`
	AcceptUntrustedCertificates        types.Bool   `tfsdk:"accept_untrusted_certificates"`
	AppSecretKeyVaultUrl               types.String `tfsdk:"app_secret_key_vault_url"`
	ApplicationId                      types.String `tfsdk:"application_id"`
	Authentication                     types.String `tfsdk:"authentication"`
	Autodiscover                       types.Bool   `tfsdk:"autodiscover"`
	Compliance                         types.Bool   `tfsdk:"compliance"`
	Credentials                        types.String `tfsdk:"credentials"`
	EmailAddress                       types.String `tfsdk:"email_address"`
	ExchangeOutlookAnywhere            types.Bool   `tfsdk:"exchange_outlook_anywhere"`
	ExchangeRemoteMove                 types.Bool   `tfsdk:"exchange_remote_move"`
	ExchangeServer                     types.String `tfsdk:"exchange_server"`
	Gmail                              types.Bool   `tfsdk:"gmail"`
	IMAP                               types.Bool   `tfsdk:"imap"`
	MailboxPermission                  types.String `tfsdk:"mailbox_permission"`
	MaxConcurrentIncrementalSyncs      types.String `tfsdk:"max_concurrent_incremental_syncs"`
	MaxConcurrentMigrations            types.String `tfsdk:"max_concurrent_migrations"`
	Name                               types.String `tfsdk:"name"`
	NspiServer                         types.String `tfsdk:"nspi_server"`
	OAuthCode                          types.String `tfsdk:"o_auth_code"`
	Partition                          types.String `tfsdk:"partition"`
	PublicFolder                       types.Bool   `tfsdk:"public_folder"`
	PublicFolderDatabaseServerLegacyDN types.String `tfsdk:"public_folder_database_server_legacy_dn"`
	PublicFolderToUnifiedGroup         types.Bool   `tfsdk:"public_folder_to_unified_group"`
	RPCProxyServer                     types.String `tfsdk:"rpc_proxy_server"`
	RedirectUri                        types.String `tfsdk:"redirect_uri"`
	RemoteServer                       types.String `tfsdk:"remote_server"`
	RemoteTenant                       types.String `tfsdk:"remote_tenant"`
	Security                           types.String `tfsdk:"security"`
	ServiceAccountKeyFileData          types.Set    `tfsdk:"service_account_key_file_data"`
	SkipVerification                   types.Bool   `tfsdk:"skip_verification"`
	SourceMailboxLegacyDN              types.String `tfsdk:"source_mailbox_legacy_dn"`
	TestMailbox                        types.String `tfsdk:"test_mailbox"`
}

func (r *migrationEndpointResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_migration_endpoint"
}

func (r *migrationEndpointResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MigrationEndpoint object via New-MigrationEndpoint / Get-MigrationEndpoint / Set-MigrationEndpoint / Remove-MigrationEndpoint.",
		Attributes: map[string]schema.Attribute{
			"id":                               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                         schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"accept_untrusted_certificates":    schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AcceptUntrustedCertificates parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"app_secret_key_vault_url":         schema.StringAttribute{Optional: true, Computed: true, Sensitive: true, Description: "Maps to the -AppSecretKeyVaultUrl parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"application_id":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplicationId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"authentication":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Authentication parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"autodiscover":                     schema.BoolAttribute{Required: true, Description: "Maps to the -Autodiscover parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"compliance":                       schema.BoolAttribute{Required: true, Description: "Maps to the -Compliance parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"credentials":                      schema.StringAttribute{Required: true, Sensitive: true, Description: "Maps to the -Credentials parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"email_address":                    schema.StringAttribute{Required: true, Description: "Maps to the -EmailAddress parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"exchange_outlook_anywhere":        schema.BoolAttribute{Required: true, Description: "Maps to the -ExchangeOutlookAnywhere parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"exchange_remote_move":             schema.BoolAttribute{Required: true, Description: "Maps to the -ExchangeRemoteMove parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"exchange_server":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExchangeServer parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"gmail":                            schema.BoolAttribute{Required: true, Description: "Maps to the -Gmail parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"imap":                             schema.BoolAttribute{Required: true, Description: "Maps to the -IMAP parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"mailbox_permission":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MailboxPermission parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"max_concurrent_incremental_syncs": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MaxConcurrentIncrementalSyncs parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"max_concurrent_migrations":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MaxConcurrentMigrations parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":                             schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"nspi_server":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NspiServer parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"o_auth_code":                      schema.StringAttribute{Required: true, Description: "Maps to the -OAuthCode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"partition":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Partition parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"public_folder":                    schema.BoolAttribute{Required: true, Description: "Maps to the -PublicFolder parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"public_folder_database_server_legacy_dn": schema.StringAttribute{Required: true, Description: "Maps to the -PublicFolderDatabaseServerLegacyDN parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"public_folder_to_unified_group":          schema.BoolAttribute{Required: true, Description: "Maps to the -PublicFolderToUnifiedGroup parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace()}},
			"rpc_proxy_server":                        schema.StringAttribute{Required: true, Description: "Maps to the -RPCProxyServer parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"redirect_uri":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RedirectUri parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"remote_server":                           schema.StringAttribute{Required: true, Description: "Maps to the -RemoteServer parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"remote_tenant":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoteTenant parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"security":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Security parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"service_account_key_file_data":           schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "Maps to the -ServiceAccountKeyFileData parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace()}},
			"skip_verification":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SkipVerification parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"source_mailbox_legacy_dn":                schema.StringAttribute{Required: true, Description: "Maps to the -SourceMailboxLegacyDN parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"test_mailbox":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TestMailbox parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *migrationEndpointResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *migrationEndpointResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan migrationEndpointModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewMigrationEndpointParams{
		AcceptUntrustedCertificates:        plan.AcceptUntrustedCertificates.ValueBool(),
		AppSecretKeyVaultUrl:               plan.AppSecretKeyVaultUrl.ValueString(),
		ApplicationId:                      plan.ApplicationId.ValueString(),
		Autodiscover:                       plan.Autodiscover.ValueBool(),
		Compliance:                         plan.Compliance.ValueBool(),
		ExchangeOutlookAnywhere:            plan.ExchangeOutlookAnywhere.ValueBool(),
		ExchangeRemoteMove:                 plan.ExchangeRemoteMove.ValueBool(),
		ExchangeServer:                     plan.ExchangeServer.ValueString(),
		Gmail:                              plan.Gmail.ValueBool(),
		IMAP:                               plan.IMAP.ValueBool(),
		Name:                               plan.Name.ValueString(),
		NspiServer:                         plan.NspiServer.ValueString(),
		PublicFolder:                       plan.PublicFolder.ValueBool(),
		PublicFolderDatabaseServerLegacyDN: plan.PublicFolderDatabaseServerLegacyDN.ValueString(),
		PublicFolderToUnifiedGroup:         plan.PublicFolderToUnifiedGroup.ValueBool(),
		RedirectUri:                        plan.RedirectUri.ValueString(),
		RemoteTenant:                       plan.RemoteTenant.ValueString(),
		ServiceAccountKeyFileData:          toStringSlice(ctx, plan.ServiceAccountKeyFileData, &resp.Diagnostics),
		SkipVerification:                   plan.SkipVerification.ValueBool(),
		SourceMailboxLegacyDN:              plan.SourceMailboxLegacyDN.ValueString(),
	}
	if v := plan.Authentication.ValueString(); v != "" {
		p.Authentication = v
	}
	if v := plan.Credentials.ValueString(); v != "" {
		p.Credentials = v
	}
	if v := plan.EmailAddress.ValueString(); v != "" {
		p.EmailAddress = v
	}
	if v := plan.MailboxPermission.ValueString(); v != "" {
		p.MailboxPermission = v
	}
	if v := plan.MaxConcurrentIncrementalSyncs.ValueString(); v != "" {
		p.MaxConcurrentIncrementalSyncs = v
	}
	if v := plan.MaxConcurrentMigrations.ValueString(); v != "" {
		p.MaxConcurrentMigrations = v
	}
	if v := plan.OAuthCode.ValueString(); v != "" {
		p.OAuthCode = v
	}
	if v := plan.Partition.ValueString(); v != "" {
		p.Partition = v
	}
	if v := plan.RPCProxyServer.ValueString(); v != "" {
		p.RPCProxyServer = v
	}
	if v := plan.RemoteServer.ValueString(); v != "" {
		p.RemoteServer = v
	}
	if v := plan.Security.ValueString(); v != "" {
		p.Security = v
	}
	if v := plan.TestMailbox.ValueString(); v != "" {
		p.TestMailbox = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.NewMigrationEndpoint(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-MigrationEndpoint failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MigrationEndpoint returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMigrationEndpoint(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *migrationEndpointResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state migrationEndpointModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *migrationEndpointResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state migrationEndpointModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetMigrationEndpointParams{}
	sp.Identity = id
	sp.AcceptUntrustedCertificates = plan.AcceptUntrustedCertificates.ValueBool()
	sp.AppSecretKeyVaultUrl = plan.AppSecretKeyVaultUrl.ValueString()
	sp.ApplicationId = plan.ApplicationId.ValueString()
	if v := plan.Authentication.ValueString(); v != "" {
		sp.Authentication = v
	}
	sp.ExchangeServer = plan.ExchangeServer.ValueString()
	if v := plan.MailboxPermission.ValueString(); v != "" {
		sp.MailboxPermission = v
	}
	if v := plan.MaxConcurrentIncrementalSyncs.ValueString(); v != "" {
		sp.MaxConcurrentIncrementalSyncs = v
	}
	if v := plan.MaxConcurrentMigrations.ValueString(); v != "" {
		sp.MaxConcurrentMigrations = v
	}
	sp.NspiServer = plan.NspiServer.ValueString()
	if v := plan.Partition.ValueString(); v != "" {
		sp.Partition = v
	}
	if v := plan.Security.ValueString(); v != "" {
		sp.Security = v
	}
	sp.SkipVerification = plan.SkipVerification.ValueBool()
	if v := plan.TestMailbox.ValueString(); v != "" {
		sp.TestMailbox = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetMigrationEndpoint(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MigrationEndpoint failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AppSecretKeyVaultUrl":          cfg.AppSecretKeyVaultUrl,
		"ApplicationId":                 cfg.ApplicationId,
		"Authentication":                cfg.Authentication,
		"ExchangeServer":                cfg.ExchangeServer,
		"MailboxPermission":             cfg.MailboxPermission,
		"MaxConcurrentIncrementalSyncs": cfg.MaxConcurrentIncrementalSyncs,
		"MaxConcurrentMigrations":       cfg.MaxConcurrentMigrations,
		"NspiServer":                    cfg.NspiServer,
		"Partition":                     cfg.Partition,
		"Security":                      cfg.Security,
		"TestMailbox":                   cfg.TestMailbox,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *migrationEndpointResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state migrationEndpointModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveMigrationEndpoint(ctx, exo.RemoveMigrationEndpointParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MigrationEndpoint failed", err.Error())
		}
	}
}

func (r *migrationEndpointResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *migrationEndpointResource) identityOf(m migrationEndpointModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *migrationEndpointResource) refresh(ctx context.Context, identity string, m *migrationEndpointModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetMigrationEndpoint(ctx, exo.GetMigrationEndpointParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MigrationEndpoint failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMigrationEndpoint(ctx, obj, m)
	return true
}

func readMigrationEndpoint(ctx context.Context, obj map[string]any, m *migrationEndpointModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AcceptUntrustedCertificates = types.BoolValue(getBool(obj, "AcceptUntrustedCertificates"))
	m.AppSecretKeyVaultUrl = types.StringValue(getString(obj, "AppSecretKeyVaultUrl"))
	m.ApplicationId = types.StringValue(getString(obj, "ApplicationId"))
	m.Authentication = types.StringValue(getString(obj, "Authentication"))
	m.Autodiscover = types.BoolValue(getBool(obj, "Autodiscover"))
	m.Compliance = types.BoolValue(getBool(obj, "Compliance"))
	m.Credentials = types.StringValue(getString(obj, "Credentials"))
	m.EmailAddress = types.StringValue(getString(obj, "EmailAddress"))
	m.ExchangeOutlookAnywhere = types.BoolValue(getBool(obj, "ExchangeOutlookAnywhere"))
	m.ExchangeRemoteMove = types.BoolValue(getBool(obj, "ExchangeRemoteMove"))
	m.ExchangeServer = types.StringValue(getString(obj, "ExchangeServer"))
	m.Gmail = types.BoolValue(getBool(obj, "Gmail"))
	m.IMAP = types.BoolValue(getBool(obj, "IMAP"))
	m.MailboxPermission = types.StringValue(getString(obj, "MailboxPermission"))
	m.MaxConcurrentIncrementalSyncs = types.StringValue(getString(obj, "MaxConcurrentIncrementalSyncs"))
	m.MaxConcurrentMigrations = types.StringValue(getString(obj, "MaxConcurrentMigrations"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.NspiServer = types.StringValue(getString(obj, "NspiServer"))
	m.OAuthCode = types.StringValue(getString(obj, "OAuthCode"))
	m.Partition = types.StringValue(getString(obj, "Partition"))
	m.PublicFolder = types.BoolValue(getBool(obj, "PublicFolder"))
	m.PublicFolderDatabaseServerLegacyDN = types.StringValue(getString(obj, "PublicFolderDatabaseServerLegacyDN"))
	m.PublicFolderToUnifiedGroup = types.BoolValue(getBool(obj, "PublicFolderToUnifiedGroup"))
	m.RPCProxyServer = types.StringValue(getString(obj, "RPCProxyServer"))
	m.RedirectUri = types.StringValue(getString(obj, "RedirectUri"))
	m.RemoteServer = types.StringValue(getString(obj, "RemoteServer"))
	m.RemoteTenant = types.StringValue(getString(obj, "RemoteTenant"))
	m.Security = types.StringValue(getString(obj, "Security"))
	m.ServiceAccountKeyFileData = stringSetValue(ctx, getStringSlice(obj, "ServiceAccountKeyFileData"))
	m.SkipVerification = types.BoolValue(getBool(obj, "SkipVerification"))
	m.SourceMailboxLegacyDN = types.StringValue(getString(obj, "SourceMailboxLegacyDN"))
	m.TestMailbox = types.StringValue(getString(obj, "TestMailbox"))
	_ = ctx
}

func (r *migrationEndpointResource) reconcileState(cfg, read *migrationEndpointModel) {
	read.AcceptUntrustedCertificates = reconcile.KeepBool(cfg.AcceptUntrustedCertificates, read.AcceptUntrustedCertificates)
	read.AppSecretKeyVaultUrl = reconcile.KeepStr(cfg.AppSecretKeyVaultUrl, read.AppSecretKeyVaultUrl)
	read.ApplicationId = reconcile.KeepStr(cfg.ApplicationId, read.ApplicationId)
	read.Authentication = reconcile.KeepStr(cfg.Authentication, read.Authentication)
	read.Autodiscover = reconcile.KeepBool(cfg.Autodiscover, read.Autodiscover)
	read.Compliance = reconcile.KeepBool(cfg.Compliance, read.Compliance)
	read.Credentials = reconcile.KeepStr(cfg.Credentials, read.Credentials)
	read.EmailAddress = reconcile.KeepStr(cfg.EmailAddress, read.EmailAddress)
	read.ExchangeOutlookAnywhere = reconcile.KeepBool(cfg.ExchangeOutlookAnywhere, read.ExchangeOutlookAnywhere)
	read.ExchangeRemoteMove = reconcile.KeepBool(cfg.ExchangeRemoteMove, read.ExchangeRemoteMove)
	read.ExchangeServer = reconcile.KeepStr(cfg.ExchangeServer, read.ExchangeServer)
	read.Gmail = reconcile.KeepBool(cfg.Gmail, read.Gmail)
	read.IMAP = reconcile.KeepBool(cfg.IMAP, read.IMAP)
	read.MailboxPermission = reconcile.KeepStr(cfg.MailboxPermission, read.MailboxPermission)
	read.MaxConcurrentIncrementalSyncs = reconcile.KeepStr(cfg.MaxConcurrentIncrementalSyncs, read.MaxConcurrentIncrementalSyncs)
	read.MaxConcurrentMigrations = reconcile.KeepStr(cfg.MaxConcurrentMigrations, read.MaxConcurrentMigrations)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.NspiServer = reconcile.KeepStr(cfg.NspiServer, read.NspiServer)
	read.OAuthCode = reconcile.KeepStr(cfg.OAuthCode, read.OAuthCode)
	read.Partition = reconcile.KeepStr(cfg.Partition, read.Partition)
	read.PublicFolder = reconcile.KeepBool(cfg.PublicFolder, read.PublicFolder)
	read.PublicFolderDatabaseServerLegacyDN = reconcile.KeepStr(cfg.PublicFolderDatabaseServerLegacyDN, read.PublicFolderDatabaseServerLegacyDN)
	read.PublicFolderToUnifiedGroup = reconcile.KeepBool(cfg.PublicFolderToUnifiedGroup, read.PublicFolderToUnifiedGroup)
	read.RPCProxyServer = reconcile.KeepStr(cfg.RPCProxyServer, read.RPCProxyServer)
	read.RedirectUri = reconcile.KeepStr(cfg.RedirectUri, read.RedirectUri)
	read.RemoteServer = reconcile.KeepStr(cfg.RemoteServer, read.RemoteServer)
	read.RemoteTenant = reconcile.KeepStr(cfg.RemoteTenant, read.RemoteTenant)
	read.Security = reconcile.KeepStr(cfg.Security, read.Security)
	read.ServiceAccountKeyFileData = reconcile.KeepSet(cfg.ServiceAccountKeyFileData, read.ServiceAccountKeyFileData)
	read.SkipVerification = reconcile.KeepBool(cfg.SkipVerification, read.SkipVerification)
	read.SourceMailboxLegacyDN = reconcile.KeepStr(cfg.SourceMailboxLegacyDN, read.SourceMailboxLegacyDN)
	read.TestMailbox = reconcile.KeepStr(cfg.TestMailbox, read.TestMailbox)
}
