// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &outboundConnectorResource{}
	_ resource.ResourceWithConfigure   = &outboundConnectorResource{}
	_ resource.ResourceWithImportState = &outboundConnectorResource{}
)

type outboundConnectorResource struct{ client *clients.Client }

// NewOutboundConnectorResource manages the OutboundConnector object (New-OutboundConnector / Get-OutboundConnector / Set-OutboundConnector / Remove-OutboundConnector).
func NewOutboundConnectorResource() resource.Resource { return &outboundConnectorResource{} }

type outboundConnectorModel struct {
	ID                            types.String `tfsdk:"id"`
	Identity                      types.String `tfsdk:"identity"`
	AllAcceptedDomains            types.Bool   `tfsdk:"all_accepted_domains"`
	CloudServicesMailEnabled      types.Bool   `tfsdk:"cloud_services_mail_enabled"`
	Comment                       types.String `tfsdk:"comment"`
	ConnectorSource               types.String `tfsdk:"connector_source"`
	ConnectorType                 types.String `tfsdk:"connector_type"`
	Enabled                       types.Bool   `tfsdk:"enabled"`
	IsTransportRuleScoped         types.Bool   `tfsdk:"is_transport_rule_scoped"`
	IsValidated                   types.Bool   `tfsdk:"is_validated"`
	LastValidationTimestamp       types.String `tfsdk:"last_validation_timestamp"`
	LinkForModifiedConnector      types.String `tfsdk:"link_for_modified_connector"`
	MtaStsMode                    types.String `tfsdk:"mta_sts_mode"`
	Name                          types.String `tfsdk:"name"`
	RecipientDomains              types.String `tfsdk:"recipient_domains"`
	RouteAllMessagesViaOnPremises types.Bool   `tfsdk:"route_all_messages_via_on_premises"`
	SenderRewritingEnabled        types.Bool   `tfsdk:"sender_rewriting_enabled"`
	SmartHosts                    types.String `tfsdk:"smart_hosts"`
	SmtpDaneMode                  types.String `tfsdk:"smtp_dane_mode"`
	TestMode                      types.Bool   `tfsdk:"test_mode"`
	TlsDomain                     types.String `tfsdk:"tls_domain"`
	TlsSettings                   types.String `tfsdk:"tls_settings"`
	UseMXRecord                   types.Bool   `tfsdk:"use_mx_record"`
	ValidationRecipients          types.Set    `tfsdk:"validation_recipients"`
}

func (r *outboundConnectorResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_outbound_connector"
}

func (r *outboundConnectorResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the OutboundConnector object via New-OutboundConnector / Get-OutboundConnector / Set-OutboundConnector / Remove-OutboundConnector.",
		Attributes: map[string]schema.Attribute{
			"id":                                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                           schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"all_accepted_domains":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllAcceptedDomains parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"cloud_services_mail_enabled":        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -CloudServicesMailEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"comment":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"connector_source":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ConnectorSource parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"connector_type":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ConnectorType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":                            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_transport_rule_scoped":           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsTransportRuleScoped parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"is_validated":                       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsValidated parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"last_validation_timestamp":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LastValidationTimestamp parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"link_for_modified_connector":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LinkForModifiedConnector parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"mta_sts_mode":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MtaStsMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":                               schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"recipient_domains":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RecipientDomains parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"route_all_messages_via_on_premises": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RouteAllMessagesViaOnPremises parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"sender_rewriting_enabled":           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -SenderRewritingEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"smart_hosts":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SmartHosts parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"smtp_dane_mode":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SmtpDaneMode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"test_mode":                          schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -TestMode parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"tls_domain":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TlsDomain parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tls_settings":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TlsSettings parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"use_mx_record":                      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseMXRecord parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"validation_recipients":              schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ValidationRecipients parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *outboundConnectorResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *outboundConnectorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan outboundConnectorModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewOutboundConnectorParams{
		AllAcceptedDomains:            plan.AllAcceptedDomains.ValueBool(),
		CloudServicesMailEnabled:      plan.CloudServicesMailEnabled.ValueBool(),
		Comment:                       plan.Comment.ValueString(),
		Enabled:                       plan.Enabled.ValueBool(),
		IsTransportRuleScoped:         plan.IsTransportRuleScoped.ValueBool(),
		Name:                          plan.Name.ValueString(),
		RouteAllMessagesViaOnPremises: plan.RouteAllMessagesViaOnPremises.ValueBool(),
		SenderRewritingEnabled:        plan.SenderRewritingEnabled.ValueBool(),
		TestMode:                      plan.TestMode.ValueBool(),
		UseMXRecord:                   plan.UseMXRecord.ValueBool(),
	}
	if v := plan.ConnectorSource.ValueString(); v != "" {
		p.ConnectorSource = v
	}
	if v := plan.ConnectorType.ValueString(); v != "" {
		p.ConnectorType = v
	}
	if v := plan.LinkForModifiedConnector.ValueString(); v != "" {
		p.LinkForModifiedConnector = v
	}
	if v := plan.MtaStsMode.ValueString(); v != "" {
		p.MtaStsMode = v
	}
	if v := plan.RecipientDomains.ValueString(); v != "" {
		p.RecipientDomains = v
	}
	if v := plan.SmartHosts.ValueString(); v != "" {
		p.SmartHosts = v
	}
	if v := plan.SmtpDaneMode.ValueString(); v != "" {
		p.SmtpDaneMode = v
	}
	if v := plan.TlsDomain.ValueString(); v != "" {
		p.TlsDomain = v
	}
	if v := plan.TlsSettings.ValueString(); v != "" {
		p.TlsSettings = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.NewOutboundConnector(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-OutboundConnector failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-OutboundConnector returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readOutboundConnector(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *outboundConnectorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state outboundConnectorModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *outboundConnectorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state outboundConnectorModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetOutboundConnectorParams{}
	sp.Identity = id
	sp.AllAcceptedDomains = plan.AllAcceptedDomains.ValueBool()
	sp.CloudServicesMailEnabled = plan.CloudServicesMailEnabled.ValueBool()
	sp.Comment = plan.Comment.ValueString()
	if v := plan.ConnectorSource.ValueString(); v != "" {
		sp.ConnectorSource = v
	}
	if v := plan.ConnectorType.ValueString(); v != "" {
		sp.ConnectorType = v
	}
	sp.Enabled = plan.Enabled.ValueBool()
	sp.IsTransportRuleScoped = plan.IsTransportRuleScoped.ValueBool()
	sp.IsValidated = plan.IsValidated.ValueBool()
	if v := plan.LastValidationTimestamp.ValueString(); v != "" {
		sp.LastValidationTimestamp = v
	}
	if v := plan.MtaStsMode.ValueString(); v != "" {
		sp.MtaStsMode = v
	}
	if v := plan.RecipientDomains.ValueString(); v != "" {
		sp.RecipientDomains = v
	}
	sp.RouteAllMessagesViaOnPremises = plan.RouteAllMessagesViaOnPremises.ValueBool()
	sp.SenderRewritingEnabled = plan.SenderRewritingEnabled.ValueBool()
	if v := plan.SmartHosts.ValueString(); v != "" {
		sp.SmartHosts = v
	}
	if v := plan.SmtpDaneMode.ValueString(); v != "" {
		sp.SmtpDaneMode = v
	}
	sp.TestMode = plan.TestMode.ValueBool()
	if v := plan.TlsDomain.ValueString(); v != "" {
		sp.TlsDomain = v
	}
	if v := plan.TlsSettings.ValueString(); v != "" {
		sp.TlsSettings = v
	}
	sp.UseMXRecord = plan.UseMXRecord.ValueBool()
	sp.ValidationRecipients = toStringSlice(ctx, plan.ValidationRecipients, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetOutboundConnector(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-OutboundConnector failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Comment":                 cfg.Comment,
		"ConnectorSource":         cfg.ConnectorSource,
		"ConnectorType":           cfg.ConnectorType,
		"LastValidationTimestamp": cfg.LastValidationTimestamp,
		"MtaStsMode":              cfg.MtaStsMode,
		"RecipientDomains":        cfg.RecipientDomains,
		"SmartHosts":              cfg.SmartHosts,
		"SmtpDaneMode":            cfg.SmtpDaneMode,
		"TlsDomain":               cfg.TlsDomain,
		"TlsSettings":             cfg.TlsSettings,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *outboundConnectorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state outboundConnectorModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveOutboundConnector(ctx, exo.RemoveOutboundConnectorParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-OutboundConnector failed", err.Error())
		}
	}
}

func (r *outboundConnectorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *outboundConnectorResource) identityOf(m outboundConnectorModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *outboundConnectorResource) refresh(ctx context.Context, identity string, m *outboundConnectorModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetOutboundConnector(ctx, exo.GetOutboundConnectorParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-OutboundConnector failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readOutboundConnector(ctx, obj, m)
	return true
}

func readOutboundConnector(ctx context.Context, obj map[string]any, m *outboundConnectorModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AllAcceptedDomains = types.BoolValue(getBool(obj, "AllAcceptedDomains"))
	m.CloudServicesMailEnabled = types.BoolValue(getBool(obj, "CloudServicesMailEnabled"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.ConnectorSource = types.StringValue(getString(obj, "ConnectorSource"))
	m.ConnectorType = types.StringValue(getString(obj, "ConnectorType"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.IsTransportRuleScoped = types.BoolValue(getBool(obj, "IsTransportRuleScoped"))
	m.IsValidated = types.BoolValue(getBool(obj, "IsValidated"))
	m.LastValidationTimestamp = types.StringValue(getString(obj, "LastValidationTimestamp"))
	m.LinkForModifiedConnector = types.StringValue(getString(obj, "LinkForModifiedConnector"))
	m.MtaStsMode = types.StringValue(getString(obj, "MtaStsMode"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.RecipientDomains = types.StringValue(getString(obj, "RecipientDomains"))
	m.RouteAllMessagesViaOnPremises = types.BoolValue(getBool(obj, "RouteAllMessagesViaOnPremises"))
	m.SenderRewritingEnabled = types.BoolValue(getBool(obj, "SenderRewritingEnabled"))
	m.SmartHosts = types.StringValue(getString(obj, "SmartHosts"))
	m.SmtpDaneMode = types.StringValue(getString(obj, "SmtpDaneMode"))
	m.TestMode = types.BoolValue(getBool(obj, "TestMode"))
	m.TlsDomain = types.StringValue(getString(obj, "TlsDomain"))
	m.TlsSettings = types.StringValue(getString(obj, "TlsSettings"))
	m.UseMXRecord = types.BoolValue(getBool(obj, "UseMXRecord"))
	m.ValidationRecipients = stringSetValue(ctx, getStringSlice(obj, "ValidationRecipients"))
	_ = ctx
}

func (r *outboundConnectorResource) reconcileState(cfg, read *outboundConnectorModel) {
	read.AllAcceptedDomains = reconcile.KeepBool(cfg.AllAcceptedDomains, read.AllAcceptedDomains)
	read.CloudServicesMailEnabled = reconcile.KeepBool(cfg.CloudServicesMailEnabled, read.CloudServicesMailEnabled)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.ConnectorSource = reconcile.KeepStr(cfg.ConnectorSource, read.ConnectorSource)
	read.ConnectorType = reconcile.KeepStr(cfg.ConnectorType, read.ConnectorType)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.IsTransportRuleScoped = reconcile.KeepBool(cfg.IsTransportRuleScoped, read.IsTransportRuleScoped)
	read.IsValidated = reconcile.KeepBool(cfg.IsValidated, read.IsValidated)
	read.LastValidationTimestamp = reconcile.KeepStr(cfg.LastValidationTimestamp, read.LastValidationTimestamp)
	read.LinkForModifiedConnector = reconcile.KeepStr(cfg.LinkForModifiedConnector, read.LinkForModifiedConnector)
	read.MtaStsMode = reconcile.KeepStr(cfg.MtaStsMode, read.MtaStsMode)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.RecipientDomains = reconcile.KeepStr(cfg.RecipientDomains, read.RecipientDomains)
	read.RouteAllMessagesViaOnPremises = reconcile.KeepBool(cfg.RouteAllMessagesViaOnPremises, read.RouteAllMessagesViaOnPremises)
	read.SenderRewritingEnabled = reconcile.KeepBool(cfg.SenderRewritingEnabled, read.SenderRewritingEnabled)
	read.SmartHosts = reconcile.KeepStr(cfg.SmartHosts, read.SmartHosts)
	read.SmtpDaneMode = reconcile.KeepStr(cfg.SmtpDaneMode, read.SmtpDaneMode)
	read.TestMode = reconcile.KeepBool(cfg.TestMode, read.TestMode)
	read.TlsDomain = reconcile.KeepStr(cfg.TlsDomain, read.TlsDomain)
	read.TlsSettings = reconcile.KeepStr(cfg.TlsSettings, read.TlsSettings)
	read.UseMXRecord = reconcile.KeepBool(cfg.UseMXRecord, read.UseMXRecord)
	read.ValidationRecipients = reconcile.KeepSet(cfg.ValidationRecipients, read.ValidationRecipients)
}
