// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
)

var (
	_ datasource.DataSource              = &publicFolderClientPermissionListDataSource{}
	_ datasource.DataSourceWithConfigure = &publicFolderClientPermissionListDataSource{}
)

type publicFolderClientPermissionListDataSource struct{ client *clients.Client }

// NewPublicFolderClientPermissionListDataSource lists every PublicFolderClientPermission object (Get-PublicFolderClientPermission).
func NewPublicFolderClientPermissionListDataSource() datasource.DataSource {
	return &publicFolderClientPermissionListDataSource{}
}

type publicFolderClientPermissionListModel struct {
	Items []publicFolderClientPermissionModel `tfsdk:"public_folder_client_permissions"`
}

func (d *publicFolderClientPermissionListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_public_folder_client_permissions"
}

func (d *publicFolderClientPermissionListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every PublicFolderClientPermission object (Get-PublicFolderClientPermission).",
		Attributes: map[string]schema.Attribute{
			"public_folder_client_permissions": schema.ListNestedAttribute{Computed: true, Description: "All PublicFolderClientPermission objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *publicFolderClientPermissionListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *publicFolderClientPermissionListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.EXO.GetPublicFolderClientPermission(ctx, exo.GetPublicFolderClientPermissionParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-PublicFolderClientPermission failed", err.Error())
		return
	}
	var data publicFolderClientPermissionListModel
	for _, obj := range res.Value {
		var e publicFolderClientPermissionModel
		readPublicFolderClientPermission(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
