// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &safeLinksPolicyResource{}
	_ resource.ResourceWithConfigure   = &safeLinksPolicyResource{}
	_ resource.ResourceWithImportState = &safeLinksPolicyResource{}
)

type safeLinksPolicyResource struct{ client *clients.Client }

// NewSafeLinksPolicyResource manages the SafeLinksPolicy object (New-SafeLinksPolicy / Get-SafeLinksPolicy / Set-SafeLinksPolicy / Remove-SafeLinksPolicy).
func NewSafeLinksPolicyResource() resource.Resource { return &safeLinksPolicyResource{} }

type safeLinksPolicyModel struct {
	ID                            types.String `tfsdk:"id"`
	Identity                      types.String `tfsdk:"identity"`
	AdminDisplayName              types.String `tfsdk:"admin_display_name"`
	AllowClickThrough             types.Bool   `tfsdk:"allow_click_through"`
	CustomNotificationText        types.String `tfsdk:"custom_notification_text"`
	CustomUrlList                 types.String `tfsdk:"custom_url_list"`
	DeliverMessageAfterScan       types.Bool   `tfsdk:"deliver_message_after_scan"`
	DisableUrlRewrite             types.Bool   `tfsdk:"disable_url_rewrite"`
	DoNotRewriteUrls              types.Set    `tfsdk:"do_not_rewrite_urls"`
	EnableForInternalSenders      types.Bool   `tfsdk:"enable_for_internal_senders"`
	EnableOrganizationBranding    types.Bool   `tfsdk:"enable_organization_branding"`
	EnableSafeLinksForEmail       types.Bool   `tfsdk:"enable_safe_links_for_email"`
	EnableSafeLinksForOffice      types.Bool   `tfsdk:"enable_safe_links_for_office"`
	EnableSafeLinksForTeams       types.Bool   `tfsdk:"enable_safe_links_for_teams"`
	LocalizedNotificationTextList types.String `tfsdk:"localized_notification_text_list"`
	MakeBuiltInProtection         types.Bool   `tfsdk:"make_built_in_protection"`
	Name                          types.String `tfsdk:"name"`
	RecommendedPolicyType         types.String `tfsdk:"recommended_policy_type"`
	ScanUrls                      types.Bool   `tfsdk:"scan_urls"`
	TrackClicks                   types.Bool   `tfsdk:"track_clicks"`
	UseTranslatedNotificationText types.Bool   `tfsdk:"use_translated_notification_text"`
	UseTranslatedUrlText          types.Bool   `tfsdk:"use_translated_url_text"`
}

func (r *safeLinksPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_safe_links_policy"
}

func (r *safeLinksPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the SafeLinksPolicy object via New-SafeLinksPolicy / Get-SafeLinksPolicy / Set-SafeLinksPolicy / Remove-SafeLinksPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                         schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"admin_display_name":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AdminDisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"allow_click_through":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowClickThrough parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"custom_notification_text":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomNotificationText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"custom_url_list":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -CustomUrlList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deliver_message_after_scan":       schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DeliverMessageAfterScan parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"disable_url_rewrite":              schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -DisableUrlRewrite parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"do_not_rewrite_urls":              schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -DoNotRewriteUrls parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"enable_for_internal_senders":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableForInternalSenders parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_organization_branding":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableOrganizationBranding parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_safe_links_for_email":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableSafeLinksForEmail parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_safe_links_for_office":     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableSafeLinksForOffice parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"enable_safe_links_for_teams":      schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -EnableSafeLinksForTeams parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"localized_notification_text_list": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LocalizedNotificationTextList parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"make_built_in_protection":         schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -MakeBuiltInProtection parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace(), boolplanmodifier.UseStateForUnknown()}},
			"name":                             schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"recommended_policy_type":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RecommendedPolicyType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"scan_urls":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ScanUrls parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"track_clicks":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -TrackClicks parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"use_translated_notification_text": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseTranslatedNotificationText parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"use_translated_url_text":          schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -UseTranslatedUrlText parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *safeLinksPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *safeLinksPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan safeLinksPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var config safeLinksPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewSafeLinksPolicyParams{}
	if !config.AdminDisplayName.IsNull() {
		p.AdminDisplayName = plan.AdminDisplayName.ValueString()
	}
	if !config.AllowClickThrough.IsNull() {
		if !plan.AllowClickThrough.IsUnknown() {
			p.AllowClickThrough = plan.AllowClickThrough.ValueBoolPointer()
		}
	}
	if !config.CustomNotificationText.IsNull() {
		p.CustomNotificationText = plan.CustomNotificationText.ValueString()
	}
	if v := config.CustomUrlList.ValueString(); v != "" {
		p.CustomUrlList = objectParam(v)
	}
	if !config.DeliverMessageAfterScan.IsNull() {
		if !plan.DeliverMessageAfterScan.IsUnknown() {
			p.DeliverMessageAfterScan = plan.DeliverMessageAfterScan.ValueBoolPointer()
		}
	}
	if !config.DisableUrlRewrite.IsNull() {
		if !plan.DisableUrlRewrite.IsUnknown() {
			p.DisableUrlRewrite = plan.DisableUrlRewrite.ValueBoolPointer()
		}
	}
	if !config.DoNotRewriteUrls.IsNull() {
		if v := toStringSlice(ctx, plan.DoNotRewriteUrls, &resp.Diagnostics); len(v) > 0 {
			p.DoNotRewriteUrls = v
		}
	}
	if !config.EnableForInternalSenders.IsNull() {
		if !plan.EnableForInternalSenders.IsUnknown() {
			p.EnableForInternalSenders = plan.EnableForInternalSenders.ValueBoolPointer()
		}
	}
	if !config.EnableOrganizationBranding.IsNull() {
		if !plan.EnableOrganizationBranding.IsUnknown() {
			p.EnableOrganizationBranding = plan.EnableOrganizationBranding.ValueBoolPointer()
		}
	}
	if !config.EnableSafeLinksForEmail.IsNull() {
		if !plan.EnableSafeLinksForEmail.IsUnknown() {
			p.EnableSafeLinksForEmail = plan.EnableSafeLinksForEmail.ValueBoolPointer()
		}
	}
	if !config.EnableSafeLinksForOffice.IsNull() {
		if !plan.EnableSafeLinksForOffice.IsUnknown() {
			p.EnableSafeLinksForOffice = plan.EnableSafeLinksForOffice.ValueBoolPointer()
		}
	}
	if !config.EnableSafeLinksForTeams.IsNull() {
		if !plan.EnableSafeLinksForTeams.IsUnknown() {
			p.EnableSafeLinksForTeams = plan.EnableSafeLinksForTeams.ValueBoolPointer()
		}
	}
	if !config.MakeBuiltInProtection.IsNull() {
		p.MakeBuiltInProtection = plan.MakeBuiltInProtection.ValueBool()
	}
	if !config.Name.IsNull() {
		p.Name = plan.Name.ValueString()
	}
	if v := config.RecommendedPolicyType.ValueString(); v != "" {
		p.RecommendedPolicyType = objectParam(v)
	}
	if !config.ScanUrls.IsNull() {
		if !plan.ScanUrls.IsUnknown() {
			p.ScanUrls = plan.ScanUrls.ValueBoolPointer()
		}
	}
	if !config.TrackClicks.IsNull() {
		if !plan.TrackClicks.IsUnknown() {
			p.TrackClicks = plan.TrackClicks.ValueBoolPointer()
		}
	}
	if !config.UseTranslatedNotificationText.IsNull() {
		if !plan.UseTranslatedNotificationText.IsUnknown() {
			p.UseTranslatedNotificationText = plan.UseTranslatedNotificationText.ValueBoolPointer()
		}
	}
	if !config.UseTranslatedUrlText.IsNull() {
		if !plan.UseTranslatedUrlText.IsUnknown() {
			p.UseTranslatedUrlText = plan.UseTranslatedUrlText.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.NewSafeLinksPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-SafeLinksPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-SafeLinksPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readSafeLinksPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *safeLinksPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state safeLinksPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *safeLinksPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state safeLinksPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetSafeLinksPolicyParams{}
	sp.Identity = id
	var cur *safeLinksPolicyModel
	current := func() *safeLinksPolicyModel {
		if cur == nil {
			var m safeLinksPolicyModel
			if !r.refresh(ctx, id, &m, &resp.Diagnostics, nil) {
				return nil
			}
			cur = &m
		}
		return cur
	}
	if !plan.AdminDisplayName.Equal(state.AdminDisplayName) {
		sp.AdminDisplayName = plan.AdminDisplayName.ValueString()
	}
	if !plan.AllowClickThrough.Equal(state.AllowClickThrough) {
		if !plan.AllowClickThrough.IsUnknown() {
			sp.AllowClickThrough = plan.AllowClickThrough.ValueBoolPointer()
		}
	}
	if !plan.CustomNotificationText.Equal(state.CustomNotificationText) {
		sp.CustomNotificationText = plan.CustomNotificationText.ValueString()
	}
	if v := plan.CustomUrlList.ValueString(); v != "" {
		sp.CustomUrlList = objectParam(v)
	}
	if !plan.DeliverMessageAfterScan.Equal(state.DeliverMessageAfterScan) {
		if !plan.DeliverMessageAfterScan.IsUnknown() {
			sp.DeliverMessageAfterScan = plan.DeliverMessageAfterScan.ValueBoolPointer()
		}
	}
	if !plan.DisableUrlRewrite.Equal(state.DisableUrlRewrite) {
		if !plan.DisableUrlRewrite.IsUnknown() {
			sp.DisableUrlRewrite = plan.DisableUrlRewrite.ValueBoolPointer()
		}
	}
	if !plan.DoNotRewriteUrls.Equal(state.DoNotRewriteUrls) {
		if !plan.DoNotRewriteUrls.IsNull() && !plan.DoNotRewriteUrls.IsUnknown() {
			if v := toStringSlice(ctx, plan.DoNotRewriteUrls, &resp.Diagnostics); len(v) > 0 {
				sp.DoNotRewriteUrls = v
			} else {
				if c := current(); c != nil {
					if rm := toStringSlice(ctx, c.DoNotRewriteUrls, &resp.Diagnostics); len(rm) > 0 {
						sp.DoNotRewriteUrlsDelta = listRemoveDelta(rm)
					}
				}
			}
		}
	}
	if !plan.EnableForInternalSenders.Equal(state.EnableForInternalSenders) {
		if !plan.EnableForInternalSenders.IsUnknown() {
			sp.EnableForInternalSenders = plan.EnableForInternalSenders.ValueBoolPointer()
		}
	}
	if !plan.EnableOrganizationBranding.Equal(state.EnableOrganizationBranding) {
		if !plan.EnableOrganizationBranding.IsUnknown() {
			sp.EnableOrganizationBranding = plan.EnableOrganizationBranding.ValueBoolPointer()
		}
	}
	if !plan.EnableSafeLinksForEmail.Equal(state.EnableSafeLinksForEmail) {
		if !plan.EnableSafeLinksForEmail.IsUnknown() {
			sp.EnableSafeLinksForEmail = plan.EnableSafeLinksForEmail.ValueBoolPointer()
		}
	}
	if !plan.EnableSafeLinksForOffice.Equal(state.EnableSafeLinksForOffice) {
		if !plan.EnableSafeLinksForOffice.IsUnknown() {
			sp.EnableSafeLinksForOffice = plan.EnableSafeLinksForOffice.ValueBoolPointer()
		}
	}
	if !plan.EnableSafeLinksForTeams.Equal(state.EnableSafeLinksForTeams) {
		if !plan.EnableSafeLinksForTeams.IsUnknown() {
			sp.EnableSafeLinksForTeams = plan.EnableSafeLinksForTeams.ValueBoolPointer()
		}
	}
	if v := plan.LocalizedNotificationTextList.ValueString(); v != "" {
		sp.LocalizedNotificationTextList = objectParam(v)
	}
	if !plan.ScanUrls.Equal(state.ScanUrls) {
		if !plan.ScanUrls.IsUnknown() {
			sp.ScanUrls = plan.ScanUrls.ValueBoolPointer()
		}
	}
	if !plan.TrackClicks.Equal(state.TrackClicks) {
		if !plan.TrackClicks.IsUnknown() {
			sp.TrackClicks = plan.TrackClicks.ValueBoolPointer()
		}
	}
	if !plan.UseTranslatedNotificationText.Equal(state.UseTranslatedNotificationText) {
		if !plan.UseTranslatedNotificationText.IsUnknown() {
			sp.UseTranslatedNotificationText = plan.UseTranslatedNotificationText.ValueBoolPointer()
		}
	}
	if !plan.UseTranslatedUrlText.Equal(state.UseTranslatedUrlText) {
		if !plan.UseTranslatedUrlText.IsUnknown() {
			sp.UseTranslatedUrlText = plan.UseTranslatedUrlText.ValueBoolPointer()
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetSafeLinksPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-SafeLinksPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AdminDisplayName":       cfg.AdminDisplayName,
		"CustomNotificationText": cfg.CustomNotificationText,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *safeLinksPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state safeLinksPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveSafeLinksPolicy(ctx, exo.RemoveSafeLinksPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-SafeLinksPolicy failed", err.Error())
		}
	}
}

func (r *safeLinksPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *safeLinksPolicyResource) identityOf(m safeLinksPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *safeLinksPolicyResource) refresh(ctx context.Context, identity string, m *safeLinksPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetSafeLinksPolicy(ctx, exo.GetSafeLinksPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-SafeLinksPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSafeLinksPolicy(ctx, obj, m)
	return true
}

func readSafeLinksPolicy(ctx context.Context, obj map[string]any, m *safeLinksPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AdminDisplayName = types.StringValue(getString(obj, "AdminDisplayName"))
	m.AllowClickThrough = types.BoolValue(getBool(obj, "AllowClickThrough"))
	m.CustomNotificationText = types.StringValue(getString(obj, "CustomNotificationText"))
	m.CustomUrlList = types.StringValue(getObjectJSON(obj, "CustomUrlList"))
	m.DeliverMessageAfterScan = types.BoolValue(getBool(obj, "DeliverMessageAfterScan"))
	m.DisableUrlRewrite = types.BoolValue(getBool(obj, "DisableUrlRewrite"))
	m.DoNotRewriteUrls = stringSetValue(ctx, getStringSlice(obj, "DoNotRewriteUrls"))
	m.EnableForInternalSenders = types.BoolValue(getBool(obj, "EnableForInternalSenders"))
	m.EnableOrganizationBranding = types.BoolValue(getBool(obj, "EnableOrganizationBranding"))
	m.EnableSafeLinksForEmail = types.BoolValue(getBool(obj, "EnableSafeLinksForEmail"))
	m.EnableSafeLinksForOffice = types.BoolValue(getBool(obj, "EnableSafeLinksForOffice"))
	m.EnableSafeLinksForTeams = types.BoolValue(getBool(obj, "EnableSafeLinksForTeams"))
	m.LocalizedNotificationTextList = types.StringValue(getObjectJSON(obj, "LocalizedNotificationTextList"))
	m.MakeBuiltInProtection = types.BoolValue(getBool(obj, "MakeBuiltInProtection"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.RecommendedPolicyType = types.StringValue(getObjectJSON(obj, "RecommendedPolicyType"))
	m.ScanUrls = types.BoolValue(getBool(obj, "ScanUrls"))
	m.TrackClicks = types.BoolValue(getBool(obj, "TrackClicks"))
	m.UseTranslatedNotificationText = types.BoolValue(getBool(obj, "UseTranslatedNotificationText"))
	m.UseTranslatedUrlText = types.BoolValue(getBool(obj, "UseTranslatedUrlText"))
	_ = ctx
}

func (r *safeLinksPolicyResource) reconcileState(cfg, read *safeLinksPolicyModel) {
	read.AdminDisplayName = reconcile.KeepStr(cfg.AdminDisplayName, read.AdminDisplayName)
	read.AllowClickThrough = reconcile.KeepBool(cfg.AllowClickThrough, read.AllowClickThrough)
	read.CustomNotificationText = reconcile.KeepStr(cfg.CustomNotificationText, read.CustomNotificationText)
	read.CustomUrlList = reconcile.KeepStr(cfg.CustomUrlList, read.CustomUrlList)
	read.DeliverMessageAfterScan = reconcile.KeepBool(cfg.DeliverMessageAfterScan, read.DeliverMessageAfterScan)
	read.DisableUrlRewrite = reconcile.KeepBool(cfg.DisableUrlRewrite, read.DisableUrlRewrite)
	read.DoNotRewriteUrls = reconcile.KeepSet(cfg.DoNotRewriteUrls, read.DoNotRewriteUrls)
	read.EnableForInternalSenders = reconcile.KeepBool(cfg.EnableForInternalSenders, read.EnableForInternalSenders)
	read.EnableOrganizationBranding = reconcile.KeepBool(cfg.EnableOrganizationBranding, read.EnableOrganizationBranding)
	read.EnableSafeLinksForEmail = reconcile.KeepBool(cfg.EnableSafeLinksForEmail, read.EnableSafeLinksForEmail)
	read.EnableSafeLinksForOffice = reconcile.KeepBool(cfg.EnableSafeLinksForOffice, read.EnableSafeLinksForOffice)
	read.EnableSafeLinksForTeams = reconcile.KeepBool(cfg.EnableSafeLinksForTeams, read.EnableSafeLinksForTeams)
	read.LocalizedNotificationTextList = reconcile.KeepStr(cfg.LocalizedNotificationTextList, read.LocalizedNotificationTextList)
	read.MakeBuiltInProtection = reconcile.KeepBool(cfg.MakeBuiltInProtection, read.MakeBuiltInProtection)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.RecommendedPolicyType = reconcile.KeepStr(cfg.RecommendedPolicyType, read.RecommendedPolicyType)
	read.ScanUrls = reconcile.KeepBool(cfg.ScanUrls, read.ScanUrls)
	read.TrackClicks = reconcile.KeepBool(cfg.TrackClicks, read.TrackClicks)
	read.UseTranslatedNotificationText = reconcile.KeepBool(cfg.UseTranslatedNotificationText, read.UseTranslatedNotificationText)
	read.UseTranslatedUrlText = reconcile.KeepBool(cfg.UseTranslatedUrlText, read.UseTranslatedUrlText)
}
