// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &secOpsOverridePolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &secOpsOverridePolicyDataSource{}
)

type secOpsOverridePolicyDataSource struct{ client *clients.Client }

// NewSecOpsOverridePolicyDataSource looks up a SecOpsOverridePolicy object (Get-SecOpsOverridePolicy).
func NewSecOpsOverridePolicyDataSource() datasource.DataSource {
	return &secOpsOverridePolicyDataSource{}
}

func (d *secOpsOverridePolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sec_ops_override_policy"
}

func (d *secOpsOverridePolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SecOpsOverridePolicy object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":       schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"add_sent_to":    schema.StringAttribute{Computed: true, Description: "Maps to the -AddSentTo parameter."},
			"comment":        schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"enabled":        schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
			"name":           schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"remove_sent_to": schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveSentTo parameter."},
			"sent_to":        schema.StringAttribute{Computed: true, Description: "Maps to the -SentTo parameter."},
		},
	}
}

func (d *secOpsOverridePolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *secOpsOverridePolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data secOpsOverridePolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.EXO.GetSecOpsOverridePolicy(ctx, exo.GetSecOpsOverridePolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SecOpsOverridePolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SecOpsOverridePolicy not found", "no SecOpsOverridePolicy object for identity "+identity)
		return
	}
	readSecOpsOverridePolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
