// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
)

var (
	_ datasource.DataSource              = &tenantAllowBlockListSpoofItemsListDataSource{}
	_ datasource.DataSourceWithConfigure = &tenantAllowBlockListSpoofItemsListDataSource{}
)

type tenantAllowBlockListSpoofItemsListDataSource struct{ client *clients.Client }

// NewTenantAllowBlockListSpoofItemsListDataSource lists every TenantAllowBlockListSpoofItems object (Get-TenantAllowBlockListSpoofItems).
func NewTenantAllowBlockListSpoofItemsListDataSource() datasource.DataSource {
	return &tenantAllowBlockListSpoofItemsListDataSource{}
}

type tenantAllowBlockListSpoofItemsListModel struct {
	Items []tenantAllowBlockListSpoofItemsModel `tfsdk:"tenant_allow_block_list_spoof_itemses"`
}

func (d *tenantAllowBlockListSpoofItemsListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_allow_block_list_spoof_itemses"
}

func (d *tenantAllowBlockListSpoofItemsListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every TenantAllowBlockListSpoofItems object (Get-TenantAllowBlockListSpoofItems).",
		Attributes: map[string]schema.Attribute{
			"tenant_allow_block_list_spoof_itemses": schema.ListNestedAttribute{Computed: true, Description: "All TenantAllowBlockListSpoofItems objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":               schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"action":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Action parameter."},
				"ids":                    schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -Ids parameter."},
				"sending_infrastructure": schema.StringAttribute{Computed: true, Description: "Maps to the -SendingInfrastructure parameter."},
				"spoof_type":             schema.StringAttribute{Computed: true, Description: "Maps to the -SpoofType parameter."},
				"spoofed_user":           schema.StringAttribute{Computed: true, Description: "Maps to the -SpoofedUser parameter."},
			}}},
		},
	}
}

func (d *tenantAllowBlockListSpoofItemsListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *tenantAllowBlockListSpoofItemsListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.EXO.GetTenantAllowBlockListSpoofItems(ctx, exo.GetTenantAllowBlockListSpoofItemsParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-TenantAllowBlockListSpoofItems failed", err.Error())
		return
	}
	var data tenantAllowBlockListSpoofItemsListModel
	for _, obj := range res.Value {
		var e tenantAllowBlockListSpoofItemsModel
		readTenantAllowBlockListSpoofItems(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
