// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &tenantAllowBlockListSpoofItemsResource{}
	_ resource.ResourceWithConfigure   = &tenantAllowBlockListSpoofItemsResource{}
	_ resource.ResourceWithImportState = &tenantAllowBlockListSpoofItemsResource{}
)

type tenantAllowBlockListSpoofItemsResource struct{ client *clients.Client }

// NewTenantAllowBlockListSpoofItemsResource manages the TenantAllowBlockListSpoofItems object (New-TenantAllowBlockListSpoofItems / Get-TenantAllowBlockListSpoofItems / Set-TenantAllowBlockListSpoofItems / Remove-TenantAllowBlockListSpoofItems).
func NewTenantAllowBlockListSpoofItemsResource() resource.Resource {
	return &tenantAllowBlockListSpoofItemsResource{}
}

type tenantAllowBlockListSpoofItemsModel struct {
	ID                    types.String `tfsdk:"id"`
	Identity              types.String `tfsdk:"identity"`
	Action                types.String `tfsdk:"action"`
	Ids                   types.Set    `tfsdk:"ids"`
	SendingInfrastructure types.String `tfsdk:"sending_infrastructure"`
	SpoofType             types.String `tfsdk:"spoof_type"`
	SpoofedUser           types.String `tfsdk:"spoofed_user"`
}

func (r *tenantAllowBlockListSpoofItemsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_allow_block_list_spoof_items"
}

func (r *tenantAllowBlockListSpoofItemsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the TenantAllowBlockListSpoofItems object via New-TenantAllowBlockListSpoofItems / Get-TenantAllowBlockListSpoofItems / Set-TenantAllowBlockListSpoofItems / Remove-TenantAllowBlockListSpoofItems.",
		Attributes: map[string]schema.Attribute{
			"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":               schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"action":                 schema.StringAttribute{Required: true, Description: "Maps to the -Action parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"ids":                    schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -Ids parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"sending_infrastructure": schema.StringAttribute{Required: true, Description: "Maps to the -SendingInfrastructure parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"spoof_type":             schema.StringAttribute{Required: true, Description: "Maps to the -SpoofType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"spoofed_user":           schema.StringAttribute{Required: true, Description: "Maps to the -SpoofedUser parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *tenantAllowBlockListSpoofItemsResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *tenantAllowBlockListSpoofItemsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan tenantAllowBlockListSpoofItemsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := exo.NewTenantAllowBlockListSpoofItemsParams{
		Action:                plan.Action.ValueString(),
		SendingInfrastructure: plan.SendingInfrastructure.ValueString(),
		SpoofType:             plan.SpoofType.ValueString(),
		SpoofedUser:           plan.SpoofedUser.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.EXO.NewTenantAllowBlockListSpoofItems(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-TenantAllowBlockListSpoofItems failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	if obj == nil {
		resp.Diagnostics.AddError("New-TenantAllowBlockListSpoofItems returned no object", "the cmdlet did not return the created object")
		return
	}
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		readTenantAllowBlockListSpoofItems(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantAllowBlockListSpoofItemsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state tenantAllowBlockListSpoofItemsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *tenantAllowBlockListSpoofItemsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state tenantAllowBlockListSpoofItemsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := exo.SetTenantAllowBlockListSpoofItemsParams{}
	sp.Identity = id
	sp.Ids = toStringSlice(ctx, plan.Ids, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.SetTenantAllowBlockListSpoofItems(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-TenantAllowBlockListSpoofItems failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tenantAllowBlockListSpoofItemsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state tenantAllowBlockListSpoofItemsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.EXO.RemoveTenantAllowBlockListSpoofItems(ctx, exo.RemoveTenantAllowBlockListSpoofItemsParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-TenantAllowBlockListSpoofItems failed", err.Error())
		}
	}
}

func (r *tenantAllowBlockListSpoofItemsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *tenantAllowBlockListSpoofItemsResource) identityOf(m tenantAllowBlockListSpoofItemsModel) any {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *tenantAllowBlockListSpoofItemsResource) refresh(ctx context.Context, identity any, m *tenantAllowBlockListSpoofItemsModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.EXO.GetTenantAllowBlockListSpoofItems(ctx, exo.GetTenantAllowBlockListSpoofItemsParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-TenantAllowBlockListSpoofItems failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readTenantAllowBlockListSpoofItems(ctx, obj, m)
	return true
}

func readTenantAllowBlockListSpoofItems(ctx context.Context, obj map[string]any, m *tenantAllowBlockListSpoofItemsModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Action = types.StringValue(getString(obj, "Action"))
	m.Ids = stringSetValue(ctx, getStringSlice(obj, "Ids"))
	m.SendingInfrastructure = types.StringValue(getString(obj, "SendingInfrastructure"))
	m.SpoofType = types.StringValue(getString(obj, "SpoofType"))
	m.SpoofedUser = types.StringValue(getString(obj, "SpoofedUser"))
	_ = ctx
}

func (r *tenantAllowBlockListSpoofItemsResource) reconcileState(cfg, read *tenantAllowBlockListSpoofItemsModel) {
	read.Action = reconcile.KeepStr(cfg.Action, read.Action)
	read.Ids = reconcile.KeepSet(cfg.Ids, read.Ids)
	read.SendingInfrastructure = reconcile.KeepStr(cfg.SendingInfrastructure, read.SendingInfrastructure)
	read.SpoofType = reconcile.KeepStr(cfg.SpoofType, read.SpoofType)
	read.SpoofedUser = reconcile.KeepStr(cfg.SpoofedUser, read.SpoofedUser)
}
