// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
)

var (
	_ datasource.DataSource              = &unifiedGroupListDataSource{}
	_ datasource.DataSourceWithConfigure = &unifiedGroupListDataSource{}
)

type unifiedGroupListDataSource struct{ client *clients.Client }

// NewUnifiedGroupListDataSource lists every UnifiedGroup object (Get-UnifiedGroup).
func NewUnifiedGroupListDataSource() datasource.DataSource { return &unifiedGroupListDataSource{} }

type unifiedGroupListModel struct {
	Items []unifiedGroupModel `tfsdk:"unified_groups"`
}

func (d *unifiedGroupListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unified_groups"
}

func (d *unifiedGroupListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every UnifiedGroup object (Get-UnifiedGroup).",
		Attributes: map[string]schema.Attribute{
			"unified_groups": schema.ListNestedAttribute{Computed: true, Description: "All UnifiedGroup objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity": schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"accept_messages_only_from_senders_or_members": schema.StringAttribute{Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromSendersOrMembers parameter."},
				"access_type": schema.StringAttribute{Computed: true, Description: "Maps to the -AccessType parameter."},
				"alias_":      schema.StringAttribute{Computed: true, Description: "Maps to the -Alias parameter."},
				"always_subscribe_members_to_calendar_events": schema.BoolAttribute{Computed: true, Description: "Maps to the -AlwaysSubscribeMembersToCalendarEvents parameter."},
				"audit_log_age_limit":                         schema.StringAttribute{Computed: true, Description: "Maps to the -AuditLogAgeLimit parameter."},
				"auto_subscribe_new_members":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -AutoSubscribeNewMembers parameter."},
				"calendar_member_read_only":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -CalendarMemberReadOnly parameter."},
				"classification":                              schema.StringAttribute{Computed: true, Description: "Maps to the -Classification parameter."},
				"connectors_enabled":                          schema.BoolAttribute{Computed: true, Description: "Maps to the -ConnectorsEnabled parameter."},
				"convert_closed_dl_to_private_group":          schema.BoolAttribute{Computed: true, Description: "Maps to the -ConvertClosedDlToPrivateGroup parameter."},
				"custom_attribute1":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute1 parameter."},
				"custom_attribute10":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute10 parameter."},
				"custom_attribute11":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute11 parameter."},
				"custom_attribute12":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute12 parameter."},
				"custom_attribute13":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute13 parameter."},
				"custom_attribute14":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute14 parameter."},
				"custom_attribute15":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute15 parameter."},
				"custom_attribute2":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute2 parameter."},
				"custom_attribute3":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute3 parameter."},
				"custom_attribute4":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute4 parameter."},
				"custom_attribute5":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute5 parameter."},
				"custom_attribute6":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute6 parameter."},
				"custom_attribute7":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute7 parameter."},
				"custom_attribute8":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute8 parameter."},
				"custom_attribute9":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute9 parameter."},
				"data_encryption_policy":                      schema.StringAttribute{Computed: true, Description: "Maps to the -DataEncryptionPolicy parameter."},
				"delete_dl_after_migration":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -DeleteDlAfterMigration parameter."},
				"display_name":                                schema.StringAttribute{Computed: true, Description: "Maps to the -DisplayName parameter."},
				"dl_identity":                                 schema.StringAttribute{Computed: true, Description: "Maps to the -DlIdentity parameter."},
				"email_addresses":                             schema.StringAttribute{Computed: true, Description: "Maps to the -EmailAddresses parameter."},
				"executing_user":                              schema.StringAttribute{Computed: true, Description: "Maps to the -ExecutingUser parameter."},
				"exo_error_as_warning":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -ExoErrorAsWarning parameter."},
				"extension_custom_attribute1":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute1 parameter."},
				"extension_custom_attribute2":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute2 parameter."},
				"extension_custom_attribute3":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute3 parameter."},
				"extension_custom_attribute4":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute4 parameter."},
				"extension_custom_attribute5":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute5 parameter."},
				"force_upgrade":                               schema.BoolAttribute{Computed: true, Description: "Maps to the -ForceUpgrade parameter."},
				"grant_send_on_behalf_to":                     schema.StringAttribute{Computed: true, Description: "Maps to the -GrantSendOnBehalfTo parameter."},
				"hidden_from_address_lists_enabled":           schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenFromAddressListsEnabled parameter."},
				"hidden_from_exchange_clients_enabled":        schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenFromExchangeClientsEnabled parameter."},
				"hidden_group_membership_enabled":             schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenGroupMembershipEnabled parameter."},
				"information_barrier_mode":                    schema.StringAttribute{Computed: true, Description: "Maps to the -InformationBarrierMode parameter."},
				"is_member_allowed_to_edit_content":           schema.StringAttribute{Computed: true, Description: "Maps to the -IsMemberAllowedToEditContent parameter."},
				"language":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -Language parameter."},
				"mail_tip":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -MailTip parameter."},
				"mail_tip_translations":                       schema.StringAttribute{Computed: true, Description: "Maps to the -MailTipTranslations parameter."},
				"mailbox_region":                              schema.StringAttribute{Computed: true, Description: "Maps to the -MailboxRegion parameter."},
				"managed_by":                                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ManagedBy parameter."},
				"max_receive_size":                            schema.StringAttribute{Computed: true, Description: "Maps to the -MaxReceiveSize parameter."},
				"max_send_size":                               schema.StringAttribute{Computed: true, Description: "Maps to the -MaxSendSize parameter."},
				"members":                                     schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -Members parameter."},
				"moderated_by":                                schema.StringAttribute{Computed: true, Description: "Maps to the -ModeratedBy parameter."},
				"moderation_enabled":                          schema.BoolAttribute{Computed: true, Description: "Maps to the -ModerationEnabled parameter."},
				"name":                                        schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"notes":                                       schema.StringAttribute{Computed: true, Description: "Maps to the -Notes parameter."},
				"owner":                                       schema.StringAttribute{Computed: true, Description: "Maps to the -Owner parameter."},
				"primary_smtp_address":                        schema.StringAttribute{Computed: true, Description: "Maps to the -PrimarySmtpAddress parameter."},
				"reject_messages_from_senders_or_members":     schema.StringAttribute{Computed: true, Description: "Maps to the -RejectMessagesFromSendersOrMembers parameter."},
				"require_sender_authentication_enabled":       schema.BoolAttribute{Computed: true, Description: "Maps to the -RequireSenderAuthenticationEnabled parameter."},
				"sensitivity_label_id":                        schema.StringAttribute{Computed: true, Description: "Maps to the -SensitivityLabelId parameter."},
				"subscription_enabled":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -SubscriptionEnabled parameter."},
				"suppress_warmup_message":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -SuppressWarmupMessage parameter."},
				"unified_group_welcome_message_enabled":       schema.BoolAttribute{Computed: true, Description: "Maps to the -UnifiedGroupWelcomeMessageEnabled parameter."},
			}}},
		},
	}
}

func (d *unifiedGroupListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *unifiedGroupListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.EXO.GetUnifiedGroup(ctx, exo.GetUnifiedGroupParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-UnifiedGroup failed", err.Error())
		return
	}
	var data unifiedGroupListModel
	for _, obj := range res.Value {
		var e unifiedGroupModel
		readUnifiedGroup(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
