// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/exo"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-exo/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &unifiedGroupDataSource{}
	_ datasource.DataSourceWithConfigure = &unifiedGroupDataSource{}
)

type unifiedGroupDataSource struct{ client *clients.Client }

// NewUnifiedGroupDataSource looks up a UnifiedGroup object (Get-UnifiedGroup).
func NewUnifiedGroupDataSource() datasource.DataSource { return &unifiedGroupDataSource{} }

func (d *unifiedGroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unified_group"
}

func (d *unifiedGroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing UnifiedGroup object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity": schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"accept_messages_only_from_senders_or_members": schema.StringAttribute{Computed: true, Description: "Maps to the -AcceptMessagesOnlyFromSendersOrMembers parameter."},
			"access_type": schema.StringAttribute{Computed: true, Description: "Maps to the -AccessType parameter."},
			"alias_":      schema.StringAttribute{Computed: true, Description: "Maps to the -Alias parameter."},
			"always_subscribe_members_to_calendar_events": schema.BoolAttribute{Computed: true, Description: "Maps to the -AlwaysSubscribeMembersToCalendarEvents parameter."},
			"audit_log_age_limit":                         schema.StringAttribute{Computed: true, Description: "Maps to the -AuditLogAgeLimit parameter."},
			"auto_subscribe_new_members":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -AutoSubscribeNewMembers parameter."},
			"calendar_member_read_only":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -CalendarMemberReadOnly parameter."},
			"classification":                              schema.StringAttribute{Computed: true, Description: "Maps to the -Classification parameter."},
			"connectors_enabled":                          schema.BoolAttribute{Computed: true, Description: "Maps to the -ConnectorsEnabled parameter."},
			"convert_closed_dl_to_private_group":          schema.BoolAttribute{Computed: true, Description: "Maps to the -ConvertClosedDlToPrivateGroup parameter."},
			"custom_attribute1":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute1 parameter."},
			"custom_attribute10":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute10 parameter."},
			"custom_attribute11":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute11 parameter."},
			"custom_attribute12":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute12 parameter."},
			"custom_attribute13":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute13 parameter."},
			"custom_attribute14":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute14 parameter."},
			"custom_attribute15":                          schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute15 parameter."},
			"custom_attribute2":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute2 parameter."},
			"custom_attribute3":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute3 parameter."},
			"custom_attribute4":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute4 parameter."},
			"custom_attribute5":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute5 parameter."},
			"custom_attribute6":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute6 parameter."},
			"custom_attribute7":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute7 parameter."},
			"custom_attribute8":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute8 parameter."},
			"custom_attribute9":                           schema.StringAttribute{Computed: true, Description: "Maps to the -CustomAttribute9 parameter."},
			"data_encryption_policy":                      schema.StringAttribute{Computed: true, Description: "Maps to the -DataEncryptionPolicy parameter."},
			"delete_dl_after_migration":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -DeleteDlAfterMigration parameter."},
			"display_name":                                schema.StringAttribute{Computed: true, Description: "Maps to the -DisplayName parameter."},
			"dl_identity":                                 schema.StringAttribute{Computed: true, Description: "Maps to the -DlIdentity parameter."},
			"email_addresses":                             schema.StringAttribute{Computed: true, Description: "Maps to the -EmailAddresses parameter."},
			"executing_user":                              schema.StringAttribute{Computed: true, Description: "Maps to the -ExecutingUser parameter."},
			"exo_error_as_warning":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -ExoErrorAsWarning parameter."},
			"extension_custom_attribute1":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute1 parameter."},
			"extension_custom_attribute2":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute2 parameter."},
			"extension_custom_attribute3":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute3 parameter."},
			"extension_custom_attribute4":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute4 parameter."},
			"extension_custom_attribute5":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ExtensionCustomAttribute5 parameter."},
			"force_upgrade":                               schema.BoolAttribute{Computed: true, Description: "Maps to the -ForceUpgrade parameter."},
			"grant_send_on_behalf_to":                     schema.StringAttribute{Computed: true, Description: "Maps to the -GrantSendOnBehalfTo parameter."},
			"hidden_from_address_lists_enabled":           schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenFromAddressListsEnabled parameter."},
			"hidden_from_exchange_clients_enabled":        schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenFromExchangeClientsEnabled parameter."},
			"hidden_group_membership_enabled":             schema.BoolAttribute{Computed: true, Description: "Maps to the -HiddenGroupMembershipEnabled parameter."},
			"information_barrier_mode":                    schema.StringAttribute{Computed: true, Description: "Maps to the -InformationBarrierMode parameter."},
			"is_member_allowed_to_edit_content":           schema.StringAttribute{Computed: true, Description: "Maps to the -IsMemberAllowedToEditContent parameter."},
			"language":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -Language parameter."},
			"mail_tip":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -MailTip parameter."},
			"mail_tip_translations":                       schema.StringAttribute{Computed: true, Description: "Maps to the -MailTipTranslations parameter."},
			"mailbox_region":                              schema.StringAttribute{Computed: true, Description: "Maps to the -MailboxRegion parameter."},
			"managed_by":                                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ManagedBy parameter."},
			"max_receive_size":                            schema.StringAttribute{Computed: true, Description: "Maps to the -MaxReceiveSize parameter."},
			"max_send_size":                               schema.StringAttribute{Computed: true, Description: "Maps to the -MaxSendSize parameter."},
			"members":                                     schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -Members parameter."},
			"moderated_by":                                schema.StringAttribute{Computed: true, Description: "Maps to the -ModeratedBy parameter."},
			"moderation_enabled":                          schema.BoolAttribute{Computed: true, Description: "Maps to the -ModerationEnabled parameter."},
			"name":                                        schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"notes":                                       schema.StringAttribute{Computed: true, Description: "Maps to the -Notes parameter."},
			"owner":                                       schema.StringAttribute{Computed: true, Description: "Maps to the -Owner parameter."},
			"primary_smtp_address":                        schema.StringAttribute{Computed: true, Description: "Maps to the -PrimarySmtpAddress parameter."},
			"reject_messages_from_senders_or_members":     schema.StringAttribute{Computed: true, Description: "Maps to the -RejectMessagesFromSendersOrMembers parameter."},
			"require_sender_authentication_enabled":       schema.BoolAttribute{Computed: true, Description: "Maps to the -RequireSenderAuthenticationEnabled parameter."},
			"sensitivity_label_id":                        schema.StringAttribute{Computed: true, Description: "Maps to the -SensitivityLabelId parameter."},
			"subscription_enabled":                        schema.BoolAttribute{Computed: true, Description: "Maps to the -SubscriptionEnabled parameter."},
			"suppress_warmup_message":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -SuppressWarmupMessage parameter."},
			"unified_group_welcome_message_enabled":       schema.BoolAttribute{Computed: true, Description: "Maps to the -UnifiedGroupWelcomeMessageEnabled parameter."},
		},
	}
}

func (d *unifiedGroupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *unifiedGroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data unifiedGroupModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.EXO.GetUnifiedGroup(ctx, exo.GetUnifiedGroupParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-UnifiedGroup failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("UnifiedGroup not found", "no UnifiedGroup object for identity "+identity)
		return
	}
	readUnifiedGroup(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
